ALTER TABLE `finance_allocation_rules` ADD COLUMN `financial_destination` text NOT NULL DEFAULT 'REPASSAR' CHECK (`financial_destination` IN ('REPASSAR','MANTER_NA_UNIDADE'));
--> statement-breakpoint
ALTER TABLE `finance_period_allocation_rules` ADD COLUMN `financial_destination` text NOT NULL DEFAULT 'REPASSAR' CHECK (`financial_destination` IN ('REPASSAR','MANTER_NA_UNIDADE'));
--> statement-breakpoint
ALTER TABLE `finance_period_allocation_results` ADD COLUMN `financial_destination` text NOT NULL DEFAULT 'REPASSAR' CHECK (`financial_destination` IN ('REPASSAR','MANTER_NA_UNIDADE'));
--> statement-breakpoint
CREATE INDEX `finance_period_allocation_results_destination_idx` ON `finance_period_allocation_results` (`tenant_id`,`period_id`,`closure_version`,`financial_destination`);
--> statement-breakpoint
INSERT INTO `help_articles` (`id`,`tenant_id`,`slug`,`title`,`summary`,`content`,`category`,`display_order`,`target_profiles`,`required_permission`,`related_route`,`published`,`is_new_feature`,`released_at`,`version`,`published_at`,`created_at`,`updated_at`) VALUES
(32001,NULL,'financeiro-reabrir-caixa-versoes','Reabrir Caixa e preservar versões','Corrija um período fechado sem apagar o fechamento anterior.','Escolha um Caixa fechado e use Reabrir Caixa. A operação exige a permissão FINANCEIRO_CAIXA_REABRIR, vínculo válido com a Matriz responsável, confirmação da senha atual e motivo detalhado. O caixa passa a REABERTO; o fechamento anterior permanece preservado e o próximo fechamento gera uma nova versão.','Financeiro',125,'["ADMINISTRADOR","FINANCEIRO"]','FINANCEIRO_CAIXA_REABRIR','/painel/financeiro?aba=caixa',1,1,'2026-08-14','45',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(32002,NULL,'financeiro-rateio-destino-financeiro','Rateio — Repassar ou Permanecer na Unidade','Diferencie obrigações externas da parcela que fica no próprio caixa.','Em cada divisão do Rateio, selecione Repassar quando o valor pertence a outro destinatário ou Permanecer na unidade quando pertence à própria unidade do fechamento. A parcela própria não cria nova entrada e não entra no comprometido a repassar. Saldo Livre Disponível = Saldo Financeiro Atual menos Recursos Vinculados menos Repasse Pendente.','Financeiro',126,'["TODOS"]','FINANCEIRO_RATEIO_VISUALIZAR','/painel/financeiro?aba=rateio',1,1,'2026-08-14','45',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
