import type { BillingPeriod, BillingSettingsPublic, ChargeRecord, CommercialAuditRecord, CommercialDashboard, CommercialProfileRecord, CommercialTenantDetail, PaymentMethod, PlanRecord, SubscriptionRecord, SubscriptionStatus } from "@/lib/billing/types";
import { addDays, isDateOnly, isPaymentIdempotent, paymentRenewal, todayInBrazil } from "@/lib/billing/policy";
import { ApiError, database, refreshTenantLicense } from "@/lib/server/auth";
import { generatedId } from "@/lib/server/admin";
import { requirePlatformOwner } from "@/lib/server/platform";

const periods: BillingPeriod[]=["MENSAL","TRIMESTRAL","SEMESTRAL","ANUAL"];
const statuses: SubscriptionStatus[]=["TESTE","ATIVA","AGUARDANDO_PAGAMENTO","EM_CARENCIA","SUSPENSA","CANCELADA","ENCERRADA","ISENTA"];
const methods: PaymentMethod[]=["PIX","TRANSFERENCIA","DINHEIRO","BOLETO","CARTAO","OUTRO"];
const now=()=>new Date().toISOString();
const text=(value:unknown,max=500)=>typeof value==="string"&&value.trim()?value.trim().slice(0,max):null;
const integer=(value:unknown,min:number,max:number,label:string)=>{const n=Number(value);if(!Number.isInteger(n)||n<min||n>max)throw new ApiError(400,"DADOS_INVALIDOS",`${label} inválido.`);return n;};
function date(value:unknown,label:string):string;
function date(value:unknown,label:string,optional:true):string|null;
function date(value:unknown,label:string,optional=false):string|null {if(optional&&(value===null||value===""||value===undefined))return null;if(!isDateOnly(value))throw new ApiError(400,"DADOS_INVALIDOS",`${label} inválida.`);return value;}
const period=(value:unknown):BillingPeriod=>{if(!periods.includes(value as BillingPeriod))throw new ApiError(400,"DADOS_INVALIDOS","Periodicidade inválida.");return value as BillingPeriod;};

type Actor=Awaited<ReturnType<typeof requirePlatformOwner>>;
async function audit(actor:Actor,tenantId:number,action:string,entityType:string,entityId:number,before:unknown,after:unknown,reason?:unknown){
  if (tenantId <= 0) {
    await database().prepare("INSERT INTO platform_audit (actor_user_id,tenant_id,action,entity_type,entity_id,details,created_at) VALUES (?,NULL,?,?,?,?,?)")
      .bind(actor.session.user.id,action,entityType,entityId,JSON.stringify({before,after,reason:text(reason,500)}),now()).run();
    return;
  }
  await database().prepare("INSERT INTO commercial_audit (actor_user_id,tenant_id,action,entity_type,entity_id,previous_values,new_values,reason,created_at) VALUES (?,?,?,?,?,?,?,?,?)")
    .bind(actor.session.user.id,tenantId,action,entityType,entityId,before?JSON.stringify(before):null,after?JSON.stringify(after):null,text(reason,500),now()).run();
}
const PLAN_SELECT="SELECT id,name,description,price_cents AS priceCents,billing_period AS billingPeriod,default_grace_days AS defaultGraceDays,default_trial_days AS defaultTrialDays,status,created_at AS createdAt,updated_at AS updatedAt FROM saas_plans";
export async function listPlans(request:Request,includeInactive=true):Promise<PlanRecord[]>{await requirePlatformOwner(request);const rows=await database().prepare(`${PLAN_SELECT} ${includeInactive?"":"WHERE status = 'ATIVO'"} ORDER BY status,name COLLATE NOCASE`).all<PlanRecord>();return rows.results;}
export async function savePlan(request:Request,id:number|null,input:Record<string,unknown>):Promise<PlanRecord>{const actor=await requirePlatformOwner(request,true);const name=text(input.name,100);if(!name||name.length<2)throw new ApiError(400,"DADOS_INVALIDOS","Informe o nome do plano.");const description=text(input.description,1000);const priceCents=integer(input.priceCents,0,100_000_000,"Valor");const billingPeriod=period(input.billingPeriod);const grace=integer(input.defaultGraceDays,0,90,"Carência");const trial=integer(input.defaultTrialDays,0,365,"Período de teste");const status=input.status==="INATIVO"?"INATIVO":"ATIVO";const stamp=now();let before:PlanRecord|null=null;let planId=id;
  if(id){before=await database().prepare(`${PLAN_SELECT} WHERE id=?`).bind(id).first<PlanRecord>();if(!before)throw new ApiError(404,"PLANO_NAO_ENCONTRADO","Plano não encontrado.");await database().prepare("UPDATE saas_plans SET name=?,description=?,price_cents=?,billing_period=?,default_grace_days=?,default_trial_days=?,status=?,updated_at=? WHERE id=?").bind(name,description,priceCents,billingPeriod,grace,trial,status,stamp,id).run();}
  else{planId=generatedId();await database().prepare("INSERT INTO saas_plans (id,name,description,price_cents,billing_period,default_grace_days,default_trial_days,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(planId,name,description,priceCents,billingPeriod,grace,trial,status,stamp,stamp).run();}
  const saved=(await database().prepare(`${PLAN_SELECT} WHERE id=?`).bind(planId).first<PlanRecord>())!;await audit(actor,0,id?"PLANO_EDITADO":"PLANO_CRIADO","PLANO",saved.id,before,saved);return saved;
}

export async function getBillingSettings(request:Request):Promise<BillingSettingsPublic>{await requirePlatformOwner(request);const r=await database().prepare("SELECT warning_days AS warningDays,pix_key AS pixKey,pix_key_type AS pixKeyType,payee_name AS payeeName,bank_name AS bankName,bank_agency AS bankAgency,bank_account AS bankAccount,instructions,support_contact AS supportContact FROM billing_settings WHERE singleton_id=1").first<BillingSettingsPublic>();return r??{warningDays:7,pixKey:null,pixKeyType:null,payeeName:null,bankName:null,bankAgency:null,bankAccount:null,instructions:null,supportContact:null};}
export async function saveBillingSettings(request:Request,input:Record<string,unknown>):Promise<BillingSettingsPublic>{const actor=await requirePlatformOwner(request,true);const before=await getBillingSettings(request);const warningDays=integer(input.warningDays,0,90,"Antecedência do aviso");await database().prepare("INSERT INTO billing_settings (singleton_id,warning_days,pix_key,pix_key_type,payee_name,bank_name,bank_agency,bank_account,instructions,support_contact,updated_at) VALUES (1,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(singleton_id) DO UPDATE SET warning_days=excluded.warning_days,pix_key=excluded.pix_key,pix_key_type=excluded.pix_key_type,payee_name=excluded.payee_name,bank_name=excluded.bank_name,bank_agency=excluded.bank_agency,bank_account=excluded.bank_account,instructions=excluded.instructions,support_contact=excluded.support_contact,updated_at=excluded.updated_at")
  .bind(warningDays,text(input.pixKey,200),text(input.pixKeyType,50),text(input.payeeName,150),text(input.bankName,100),text(input.bankAgency,30),text(input.bankAccount,50),text(input.instructions,1500),text(input.supportContact,200),now()).run();const saved=await getBillingSettings(request);await audit(actor,0,"CONFIGURACAO_COBRANCA_EDITADA","CONFIGURACAO",1,before,saved);return saved;}

const SUB_SELECT=`SELECT s.id,s.tenant_id AS tenantId,t.name AS tenantName,t.access_code AS accessCode,s.plan_id AS planId,p.name AS planName,s.contracted_price_cents AS contractedPriceCents,s.custom_price_cents AS customPriceCents,COALESCE(s.custom_price_cents,s.contracted_price_cents) AS effectivePriceCents,s.billing_period AS billingPeriod,s.status,s.start_date AS startDate,s.next_due_date AS nextDueDate,s.due_day AS dueDay,s.grace_days AS graceDays,s.trial_start_date AS trialStartDate,s.trial_end_date AS trialEndDate,s.access_until AS accessUntil,s.auto_renew AS autoRenew,s.notes,s.suspended_reason AS suspendedReason,s.created_at AS createdAt,s.updated_at AS updatedAt FROM tenant_subscriptions s JOIN tenants t ON t.id=s.tenant_id LEFT JOIN saas_plans p ON p.id=s.plan_id`;
async function subscription(tenantId:number):Promise<SubscriptionRecord>{const row=await database().prepare(`${SUB_SELECT} WHERE s.tenant_id=?`).bind(tenantId).first<SubscriptionRecord>();if(!row)throw new ApiError(404,"ASSINATURA_NAO_ENCONTRADA","Assinatura não encontrada.");return {...row,autoRenew:Boolean(row.autoRenew)};}
const PROFILE_SELECT="SELECT tenant_id AS tenantId,person_type AS personType,legal_name AS legalName,document,responsible_name AS responsibleName,phone,billing_email AS billingEmail,notes,customer_since AS customerSince FROM commercial_profiles";
const CHARGE_SELECT="SELECT id,tenant_id AS tenantId,subscription_id AS subscriptionId,competence,description,amount_cents AS amountCents,issued_date AS issuedDate,due_date AS dueDate,status,paid_at AS paidAt,payment_method AS paymentMethod,notes,created_at AS createdAt,updated_at AS updatedAt FROM saas_charges";
export async function commercialDashboard(request:Request):Promise<CommercialDashboard>{await requirePlatformOwner(request);const ids=await database().prepare("SELECT tenant_id FROM tenant_subscriptions").all<{tenant_id:number}>();for(const item of ids.results)await refreshTenantLicense(item.tenant_id);const rows=await database().prepare(`${SUB_SELECT} ORDER BY t.name`).all<SubscriptionRecord>();const today=todayInBrazil();const subscriptions=rows.results.map((r)=>({...r,autoRenew:Boolean(r.autoRenew)}));const warningDays=Number((await database().prepare("SELECT warning_days AS warningDays FROM billing_settings WHERE singleton_id=1").first<{warningDays:number}>())?.warningDays??7);return{counters:{active:subscriptions.filter(x=>x.status==="ATIVA").length,trial:subscriptions.filter(x=>x.status==="TESTE").length,dueSoon:subscriptions.filter(x=>x.nextDueDate&&x.nextDueDate>=today&&x.nextDueDate<=addDays(today,warningDays)).length,overdue:Number((await database().prepare("SELECT COUNT(*) total FROM saas_charges WHERE status='VENCIDA'").first<{total:number}>())?.total??0),grace:subscriptions.filter(x=>x.status==="EM_CARENCIA").length,suspended:subscriptions.filter(x=>x.status==="SUSPENSA").length},subscriptions};}
export async function commercialTenant(request:Request,tenantId:number):Promise<CommercialTenantDetail>{await requirePlatformOwner(request);await refreshTenantLicense(tenantId);const [profile,sub,charges,history,plans,settings]=await Promise.all([database().prepare(`${PROFILE_SELECT} WHERE tenant_id=?`).bind(tenantId).first<CommercialProfileRecord>(),subscription(tenantId),database().prepare(`${CHARGE_SELECT} WHERE tenant_id=? ORDER BY due_date DESC,id DESC LIMIT 60`).bind(tenantId).all<ChargeRecord>(),database().prepare("SELECT a.id,a.action,a.entity_type AS entityType,a.entity_id AS entityId,a.previous_values AS previousValues,a.new_values AS newValues,a.reason,u.name AS actorName,a.created_at AS createdAt FROM commercial_audit a JOIN auth_users u ON u.id=a.actor_user_id WHERE a.tenant_id=? ORDER BY a.id DESC LIMIT 80").bind(tenantId).all<CommercialAuditRecord>(),database().prepare(`${PLAN_SELECT} ORDER BY status,name`).all<PlanRecord>(),getBillingSettings(request)]);if(!profile)throw new ApiError(404,"CLIENTE_NAO_ENCONTRADO","Cadastro comercial não encontrado.");return{profile,subscription:sub,charges:charges.results,history:history.results,plans:plans.results,settings};}

export async function saveCommercialTenant(request:Request,tenantId:number,input:Record<string,unknown>):Promise<CommercialTenantDetail>{const actor=await requirePlatformOwner(request,true);const before=await commercialTenant(request,tenantId);const personType=input.personType==="PESSOA_FISICA"?"PESSOA_FISICA":"PESSOA_JURIDICA";const legalName=text(input.legalName,180);if(!legalName)throw new ApiError(400,"DADOS_INVALIDOS","Informe o nome ou razão social.");const customerSince=date(input.customerSince,"Data de início");const planId=input.planId?integer(input.planId,1,Number.MAX_SAFE_INTEGER,"Plano"):null;const selectedPlan=planId?await database().prepare(`${PLAN_SELECT} WHERE id=?`).bind(planId).first<PlanRecord>():null;if(planId&&!selectedPlan)throw new ApiError(400,"PLANO_INVALIDO","Plano não encontrado.");const status=statuses.includes(input.status as SubscriptionStatus)?input.status as SubscriptionStatus:"TESTE";const billingPeriod=period(input.billingPeriod??selectedPlan?.billingPeriod??"MENSAL");const custom=input.customPriceCents===null||input.customPriceCents===""||input.customPriceCents===undefined?null:integer(input.customPriceCents,0,100_000_000,"Valor personalizado");const contracted=custom??selectedPlan?.priceCents??integer(input.contractedPriceCents??0,0,100_000_000,"Valor contratado");const startDate=date(input.startDate,"Data inicial");const nextDue=date(input.nextDueDate,"Próximo vencimento",true);const dueDay=input.dueDay?integer(input.dueDay,1,31,"Dia de vencimento"):nextDue?Number(nextDue.slice(-2)):null;const grace=integer(input.graceDays??selectedPlan?.defaultGraceDays??5,0,90,"Carência");const trialStart=date(input.trialStartDate,"Início do teste",true);const trialEnd=date(input.trialEndDate,"Fim do teste",true);if(status==="TESTE"&&(!trialStart||!trialEnd))throw new ApiError(400,"DADOS_INVALIDOS","Informe o início e o fim do período de teste.");const stamp=now();
  await database().batch([database().prepare("UPDATE commercial_profiles SET person_type=?,legal_name=?,document=?,responsible_name=?,phone=?,billing_email=?,notes=?,customer_since=?,updated_at=? WHERE tenant_id=?").bind(personType,legalName,text(input.document,20)?.replace(/\D/g,""),text(input.responsibleName,150),text(input.phone,30),text(input.billingEmail,254)?.toLowerCase(),text(input.commercialNotes,1500),customerSince,stamp,tenantId),database().prepare("UPDATE tenant_subscriptions SET plan_id=?,contracted_price_cents=?,custom_price_cents=?,billing_period=?,status=?,start_date=?,next_due_date=?,due_day=?,grace_days=?,trial_start_date=?,trial_end_date=?,access_until=?,auto_renew=?,notes=?,suspended_reason=CASE WHEN ? IN ('ATIVA','TESTE','ISENTA') THEN NULL ELSE suspended_reason END,updated_at=? WHERE tenant_id=?").bind(planId,contracted,custom,billingPeriod,status,startDate,nextDue,dueDay,grace,trialStart,trialEnd,date(input.accessUntil,"Acesso até",true),input.autoRenew===false?0:1,text(input.subscriptionNotes,1500),status,stamp,tenantId)]);
  const after=await commercialTenant(request,tenantId);await audit(actor,tenantId,"CADASTRO_COMERCIAL_EDITADO","ASSINATURA",after.subscription.id,{profile:before.profile,subscription:before.subscription},{profile:after.profile,subscription:after.subscription},input.reason);return after;}

export async function commercialAction(request:Request,tenantId:number,input:Record<string,unknown>):Promise<CommercialTenantDetail>{const actor=await requirePlatformOwner(request,true);const action=String(input.action??"");const before=await subscription(tenantId);const stamp=now();const today=todayInBrazil();
  if(action==="EXTEND_TRIAL"){const end=input.endDate?date(input.endDate,"Fim do teste"):addDays(before.trialEndDate&&before.trialEndDate>=today?before.trialEndDate:today,integer(input.days,1,365,"Dias"));await database().prepare("UPDATE tenant_subscriptions SET status='TESTE',trial_start_date=COALESCE(trial_start_date,?),trial_end_date=?,suspended_reason=NULL,updated_at=? WHERE tenant_id=?").bind(today,end,stamp,tenantId).run();}
  else if(action==="CREATE_CHARGE"){if(before.status==="ISENTA")throw new ApiError(409,"ASSINATURA_ISENTA","Cliente cortesia não precisa de cobrança.");const due=date(input.dueDate,"Vencimento");const amount=integer(input.amountCents??before.effectivePriceCents,0,100_000_000,"Valor");await database().prepare("INSERT INTO saas_charges (id,tenant_id,subscription_id,competence,description,amount_cents,issued_date,due_date,status,notes,payment_provider,external_reference,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,'PENDENTE',?,'MANUAL',?,?,?)").bind(generatedId(),tenantId,before.id,text(input.competence,7)??due.slice(0,7),text(input.description,200)??"Mensalidade NexIgreja",amount,today,due,text(input.notes,800),crypto.randomUUID(),stamp,stamp).run();}
  else if(action==="RECORD_PAYMENT"){const chargeId=integer(input.chargeId,1,Number.MAX_SAFE_INTEGER,"Cobrança");const charge=await database().prepare("SELECT * FROM saas_charges WHERE id=? AND tenant_id=? AND subscription_id=?").bind(chargeId,tenantId,before.id).first<{id:number;status:string;amount_cents:number;due_date:string}>();if(!charge)throw new ApiError(404,"COBRANCA_NAO_ENCONTRADA","Cobrança não encontrada.");const existing=await database().prepare("SELECT 1 found FROM saas_payments WHERE charge_id=?").bind(chargeId).first();if(isPaymentIdempotent(charge.status,Boolean(existing)))throw new ApiError(409,"PAGAMENTO_JA_REGISTRADO","Esta cobrança já foi paga e não será renovada novamente.");const amount=integer(input.amountCents,0,100_000_000,"Valor recebido");if(amount!==charge.amount_cents&&input.confirmDifference!==true)throw new ApiError(409,"CONFIRME_DIFERENCA","O valor recebido difere da cobrança. Confirme explicitamente para continuar.");const method=methods.includes(input.paymentMethod as PaymentMethod)?input.paymentMethod as PaymentMethod:null;if(!method)throw new ApiError(400,"DADOS_INVALIDOS","Forma de pagamento inválida.");const paidDate=date(input.paidDate,"Data do pagamento");const dueDay=before.dueDay??Number(charge.due_date.slice(-2));const renewed=paymentRenewal(paidDate,before.billingPeriod,dueDay);const paymentId=generatedId();await database().batch([database().prepare("INSERT INTO saas_payments (id,tenant_id,subscription_id,charge_id,amount_cents,paid_date,payment_method,notes,payment_provider,external_reference,created_by,created_at) VALUES (?,?,?,?,?,?,?,?,'MANUAL',?,?,?)").bind(paymentId,tenantId,before.id,chargeId,amount,paidDate,method,text(input.notes,800),crypto.randomUUID(),actor.session.user.id,stamp),database().prepare("UPDATE saas_charges SET status='PAGA',paid_at=?,payment_method=?,notes=COALESCE(?,notes),updated_at=? WHERE id=? AND status<>'PAGA'").bind(paidDate,method,text(input.notes,800),stamp,chargeId),database().prepare("UPDATE tenant_subscriptions SET status=?,next_due_date=?,due_day=?,trial_end_date=NULL,suspended_reason=NULL,updated_at=? WHERE id=?").bind(renewed.status,renewed.nextDueDate,dueDay,stamp,before.id)]);}
  else if(action==="SUSPEND"){const reason=text(input.reason,500);if(!reason)throw new ApiError(400,"MOTIVO_OBRIGATORIO","Informe o motivo da suspensão.");await database().prepare("UPDATE tenant_subscriptions SET status='SUSPENSA',suspended_reason=?,updated_at=? WHERE tenant_id=?").bind(reason,stamp,tenantId).run();}
  else if(action==="REACTIVATE"){const reason=text(input.reason,500);const due=date(input.nextDueDate,"Novo vencimento");if(!reason)throw new ApiError(400,"MOTIVO_OBRIGATORIO","Informe o motivo da reativação.");await database().prepare("UPDATE tenant_subscriptions SET status='ATIVA',next_due_date=?,due_day=?,suspended_reason=NULL,updated_at=? WHERE tenant_id=?").bind(due,Number(due.slice(-2)),stamp,tenantId).run();}
  else if(action==="CANCEL_SUBSCRIPTION"){const reason=text(input.reason,500);if(!reason)throw new ApiError(400,"MOTIVO_OBRIGATORIO","Informe o motivo do cancelamento.");await database().prepare("UPDATE tenant_subscriptions SET status='CANCELADA',auto_renew=0,suspended_reason=?,updated_at=? WHERE tenant_id=?").bind(reason,stamp,tenantId).run();}
  else if(action==="COURTESY"){await database().prepare("UPDATE tenant_subscriptions SET status='ISENTA',contracted_price_cents=0,custom_price_cents=0,next_due_date=NULL,grace_days=0,access_until=?,auto_renew=0,suspended_reason=NULL,updated_at=? WHERE tenant_id=?").bind(date(input.accessUntil,"Acesso até",true),stamp,tenantId).run();}
  else if(action==="CANCEL_CHARGE"){const chargeId=integer(input.chargeId,1,Number.MAX_SAFE_INTEGER,"Cobrança");const changed=await database().prepare("UPDATE saas_charges SET status='CANCELADA',notes=COALESCE(?,notes),updated_at=? WHERE id=? AND tenant_id=? AND status IN ('PENDENTE','VENCIDA')").bind(text(input.reason,500),stamp,chargeId,tenantId).run();if(!changed.meta.changes)throw new ApiError(409,"COBRANCA_NAO_CANCELAVEL","A cobrança não pode ser cancelada.");}
  else throw new ApiError(400,"ACAO_INVALIDA","Ação comercial inválida.");
  const after=await subscription(tenantId);await audit(actor,tenantId,action,"ASSINATURA",before.id,before,after,input.reason);return commercialTenant(request,tenantId);
}

export async function tenantBillingDetail(request:Request):Promise<CommercialTenantDetail>{const { administrativeSession }=await import("@/lib/server/auth");const session=await administrativeSession(request,true);const allowed=session.user.isPlatformOwner||session.user.scope==="CONVENCAO"||Boolean(session.user.membershipId&&await database().prepare("SELECT 1 ok FROM membership_permissions WHERE membership_id=? AND permission='ASSINATURA_VISUALIZAR'").bind(session.user.membershipId).first());if(!allowed)throw new ApiError(403,"PERMISSAO_NEGADA","Você não possui permissão para visualizar a assinatura.");await refreshTenantLicense(session.user.tenantId,session.user.membershipId,session.user.scope);const [profile,sub,charges,settings]=await Promise.all([database().prepare(`${PROFILE_SELECT} WHERE tenant_id=?`).bind(session.user.tenantId).first<CommercialProfileRecord>(),subscription(session.user.tenantId),database().prepare(`${CHARGE_SELECT} WHERE tenant_id=? ORDER BY due_date DESC LIMIT 24`).bind(session.user.tenantId).all<ChargeRecord>(),database().prepare("SELECT warning_days AS warningDays,pix_key AS pixKey,pix_key_type AS pixKeyType,payee_name AS payeeName,bank_name AS bankName,bank_agency AS bankAgency,bank_account AS bankAccount,instructions,support_contact AS supportContact FROM billing_settings WHERE singleton_id=1").first<BillingSettingsPublic>()]);if(!profile)throw new ApiError(404,"ASSINATURA_NAO_ENCONTRADA","Assinatura não encontrada.");return{profile,subscription:sub,charges:charges.results,history:[],plans:[],settings:settings!};}
