import { ApiError, database } from "@/lib/server/auth";
import { generatedId, requirePermission } from "@/lib/server/admin";
import type { AdministrativeSession } from "@/lib/types";
import type { PermissionCode } from "@/lib/admin/permissions";
import { canAccessMemberScope, formatMemberCode } from "@/lib/members/policy";
import { canTransfer, contributionIdentity, parseMoneyToCents, splitInstallments, type FinancePrivacy } from "@/lib/finance/policy";
import { assertOpenFinancePeriod, assertOpenFinancePeriodById } from "@/lib/server/finance-periods";
import { validateFinanceCategory } from "@/lib/server/finance-categories";

type Ctx = { session: AdministrativeSession; permissions: Set<PermissionCode> };
type Input = Record<string, unknown>;
const now = () => new Date().toISOString();
const clean = (value: unknown, max = 500) => typeof value === "string" ? value.trim().replace(/[<>]/g, "").slice(0, max) : "";
function positiveId(value:unknown):number;
function positiveId(value:unknown,required:false):number|null;
function positiveId(value:unknown,required=true):number|null{const n=Number(value);if(Number.isInteger(n)&&n>0)return n;if(!required)return null;throw new ApiError(400,"DADOS_INVALIDOS","Registro inválido.");}
const isoDate = (value: unknown, label = "Data") => { const result = clean(value, 10); if (!/^\d{4}-\d{2}-\d{2}$/.test(result)) throw new ApiError(400, "DATA_INVALIDA", `${label} inválida.`); return result; };
const competency = (value: unknown) => { const result = clean(value, 7); if (!/^\d{4}-\d{2}$/.test(result)) throw new ApiError(400, "COMPETENCIA_INVALIDA", "Informe a competência no formato AAAA-MM."); return result; };
const cents = (value: unknown) => { try { return parseMoneyToCents(value); } catch { throw new ApiError(400, "VALOR_INVALIDO", "Informe um valor positivo com até duas casas decimais."); } };

async function context(request: Request, permission: PermissionCode): Promise<Ctx> {
  const { session, permissions } = await requirePermission(request, permission);
  return { session, permissions };
}

function scopeSql(session: AdministrativeSession, column = "unit_id") {
  const unitId=session.activeContext?.unitId??session.user.boundBranchId??session.user.boundMatrixId??session.user.conventionId;
  return { sql: `${column}=?`, args: [unitId] };
}

async function scopedUnit(ctx: Ctx, unitId: number) {
  const row = await database().prepare("SELECT u.id,u.name,u.type,u.parent_id,u.status,u.archived_at,p.parent_id AS convention_id FROM organizational_units u LEFT JOIN organizational_units p ON p.id=u.parent_id AND p.tenant_id=u.tenant_id WHERE u.id=? AND u.tenant_id=?").bind(unitId, ctx.session.user.tenantId).first<{id:number;name:string;type:string;parent_id:number|null;status:string;archived_at:string|null;convention_id:number|null}>();
  if (!row || row.status !== "ATIVO" || row.archived_at || !(["CONVENCAO","MATRIZ","FILIAL"] as string[]).includes(row.type)) throw new ApiError(404, "UNIDADE_NAO_ENCONTRADA", "Unidade financeira não encontrada.");
  if (ctx.session.activeContext?.unitId!==row.id) throw new ApiError(403,"FORA_DO_ESCOPO","Selecione esta unidade no topo antes de realizar a operação.");
  if (row.type === "CONVENCAO") { if (ctx.session.user.scope !== "CONVENCAO") throw new ApiError(403, "FORA_DO_ESCOPO", "Unidade fora do seu escopo."); return row; }
  const matrixId = row.type === "MATRIZ" ? row.id : row.parent_id, branchId = row.type === "FILIAL" ? row.id : null;
  if (!matrixId || !canAccessMemberScope(ctx.session.user, { tenantId: ctx.session.user.tenantId, matrixId, branchId })) throw new ApiError(403, "FORA_DO_ESCOPO", "Unidade fora do seu escopo.");
  return row;
}

async function owned<T>(table: string, ctx: Ctx, entityId: number, extra = "") {
  const safe = new Set(["finance_accounts","finance_categories","finance_payment_methods","finance_cost_centers","finance_funds","finance_campaigns","finance_movements","finance_obligations","finance_installments"]);
  if (!safe.has(table)) throw new Error("Tabela inválida");
  const row = await database().prepare(`SELECT * FROM ${table} WHERE id=? AND tenant_id=? ${extra}`).bind(entityId, ctx.session.user.tenantId).first<T>();
  if (!row) throw new ApiError(404, "REGISTRO_NAO_ENCONTRADO", "Registro financeiro não encontrado.");
  return row;
}

function audit(ctx: Ctx, action: string, entityType: string, entityId: number, unitId: number | null, before: unknown, next: unknown, reason: string | null = null) {
  return database().prepare("INSERT INTO finance_audit(tenant_id,unit_id,actor_user_id,actor_membership_id,action,entity_type,entity_id,previous_values,new_values,reason,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").bind(ctx.session.user.tenantId, unitId, ctx.session.user.id, ctx.session.user.membershipId, action, entityType, entityId, before ? JSON.stringify(before) : null, next ? JSON.stringify(next) : null, reason, now());
}

function movementBalanceCase(alias="m") {
  return `CASE
    WHEN ${alias}.status IN ('CONFIRMADO','ESTORNADO') AND ${alias}.direction IN ('ENTRADA','TRANSFERENCIA_ENTRADA') THEN ${alias}.amount_cents
    WHEN ${alias}.status IN ('CONFIRMADO','ESTORNADO') AND ${alias}.direction IN ('SAIDA','TRANSFERENCIA_SAIDA') THEN -${alias}.amount_cents
    WHEN ${alias}.status='CONFIRMADO' AND ${alias}.direction='AJUSTE' AND ${alias}.adjustment_direction='ENTRADA' THEN ${alias}.amount_cents
    WHEN ${alias}.status='CONFIRMADO' AND ${alias}.direction='AJUSTE' AND ${alias}.adjustment_direction='SAIDA' THEN -${alias}.amount_cents
    WHEN ${alias}.status='CONFIRMADO' AND ${alias}.direction='ESTORNO' AND ${alias}.reversal_direction='ENTRADA' THEN ${alias}.amount_cents
    WHEN ${alias}.status='CONFIRMADO' AND ${alias}.direction='ESTORNO' AND ${alias}.reversal_direction='SAIDA' THEN -${alias}.amount_cents
    ELSE 0 END`;
}

async function accountSnapshot(ctx:Ctx,accountId:number){
  const row=await database().prepare(`SELECT a.*,COUNT(m.id) movement_count,a.initial_balance_cents+COALESCE(SUM(${movementBalanceCase("m")}),0) balance_cents FROM finance_accounts a LEFT JOIN finance_movements m ON m.account_id=a.id AND m.tenant_id=a.tenant_id WHERE a.id=? AND a.tenant_id=? GROUP BY a.id`).bind(accountId,ctx.session.user.tenantId).first<Record<string,unknown>>();
  if(!row)throw new ApiError(404,"REGISTRO_NAO_ENCONTRADO","Conta financeira não encontrada.");
  await scopedUnit(ctx,Number(row.unit_id));
  return row;
}

async function notifyFinance(ctx:Ctx,input:{type:"FINANCEIRO_CONTA_VENCENDO"|"FINANCEIRO_CAMPANHA_META_ATINGIDA";title:string;message:string;route:string;source:string;sourceId:number;unitId:number;groupKey:string}){const existing=await database().prepare("SELECT 1 found FROM notifications WHERE tenant_id=? AND group_key=? LIMIT 1").bind(ctx.session.user.tenantId,input.groupKey).first();if(existing)return;const recipients=await database().prepare("SELECT DISTINCT m.user_id FROM tenant_memberships m JOIN membership_permissions p ON p.membership_id=m.id WHERE m.tenant_id=? AND m.status='ATIVO' AND m.archived_at IS NULL AND p.permission='FINANCEIRO_VISUALIZAR'").bind(ctx.session.user.tenantId).all<{user_id:number}>();if(!recipients.results.length)return;const notificationId=generatedId(),stamp=now();await database().batch([database().prepare("INSERT INTO notifications(id,tenant_id,audience,type,title,message,priority,internal_route,source_entity,source_entity_id,unit_id,group_key,metadata_json,mandatory,created_at,updated_at) VALUES(?,?,'ORGANIZATIONAL',?,?,?,'ATENCAO',?,?,?,?,?,'{}',0,?,?)").bind(notificationId,ctx.session.user.tenantId,input.type,input.title,input.message,input.route,input.source,input.sourceId,input.unitId,input.groupKey,stamp,stamp),...recipients.results.map(recipient=>database().prepare("INSERT INTO notification_recipients(notification_id,user_id,created_at) VALUES(?,?,?)").bind(notificationId,recipient.user_id,stamp))]);}

export async function financeOverview(request: Request, query: Record<string,string>) {
  const ctx = await context(request, "FINANCEIRO_VISUALIZAR"), tenant = ctx.session.user.tenantId;
  const page = Math.max(1, Number(query.page) || 1), limit = Math.min(100, Math.max(10, Number(query.limit) || 25)), offset = (page - 1) * limit;
  const periodScope=scopeSql(ctx.session,"p.unit_id");
  const periods=await database().prepare(`SELECT p.id,p.unit_id,p.competency,p.status,p.lifecycle_state,p.closure_version,u.name unit_name,u.type unit_type
    FROM finance_periods p JOIN organizational_units u ON u.id=p.unit_id AND u.tenant_id=p.tenant_id
    WHERE p.tenant_id=? AND ${periodScope.sql}
    ORDER BY CASE WHEN p.status='ABERTO' THEN 0 ELSE 1 END,COALESCE(p.reopened_at,p.opened_at) DESC,p.competency DESC,p.id DESC LIMIT 240`).bind(tenant,...periodScope.args).all<Record<string,unknown>>();
  const availablePeriods=periods.results;
  const requested=query.periodId?.trim();
  let selectedPeriodId:number|null=null;
  if(requested==="all") selectedPeriodId=null;
  else if(requested){
    const id=Number(requested);
    if(!Number.isInteger(id)||id<=0||!availablePeriods.some(period=>Number(period.id)===id))throw new ApiError(404,"PERIODO_NAO_ENCONTRADO","Caixa financeiro não encontrado no seu escopo.");
    selectedPeriodId=id;
  }else selectedPeriodId=availablePeriods.length?Number(availablePeriods[0].id):null;
  const scope = scopeSql(ctx.session, "m.unit_id"),periodFilter=selectedPeriodId?" AND m.period_id=?":"",movementArgs=[tenant,...scope.args,...(selectedPeriodId?[selectedPeriodId]:[])];
  const accountScope=scopeSql(ctx.session,"a.unit_id"),centerScope=scopeSql(ctx.session,"c.unit_id"),fundScope=scopeSql(ctx.session,"f.unit_id"),campaignScope=scopeSql(ctx.session,"c.unit_id"),obligationScope=scopeSql(ctx.session,"o.unit_id"),transferScope=scopeSql(ctx.session,"t.unit_id");
  const [summary, movements, movementCount, accounts, categories, methods, centers, funds, campaigns, obligations, installments, transfers] = await Promise.all([
    database().prepare(`SELECT COALESCE(SUM(${movementBalanceCase("m")}),0) AS net_cents, COALESCE(SUM(CASE WHEN m.occurred_on=date('now') AND ((m.direction='ENTRADA' AND m.status IN ('CONFIRMADO','ESTORNADO')) OR (m.direction='ESTORNO' AND m.reversal_direction='ENTRADA' AND m.status='CONFIRMADO')) THEN m.amount_cents ELSE 0 END),0) AS today_in_cents, COALESCE(SUM(CASE WHEN m.occurred_on=date('now') AND ((m.direction='SAIDA' AND m.status IN ('CONFIRMADO','ESTORNADO')) OR (m.direction='ESTORNO' AND m.reversal_direction='SAIDA' AND m.status='CONFIRMADO')) THEN m.amount_cents ELSE 0 END),0) AS today_out_cents FROM finance_movements m WHERE m.tenant_id=? AND ${scope.sql}${periodFilter}`).bind(...movementArgs).first(),
    database().prepare(`SELECT m.*,a.name account_name,c.name category_name,p.full_name person_name,cc.name cost_center_name,ca.name campaign_name,f.name fund_name,fc.contribution_type,reverse.id reversal_movement_id,original.description original_description,i.id installment_id,i.installment_number,i.installment_count,o.kind obligation_kind,fp.closure_version period_closure_version,fp.competency period_competency,fp.lifecycle_state period_lifecycle_state,u.name unit_name FROM finance_movements m JOIN finance_accounts a ON a.id=m.account_id AND a.tenant_id=m.tenant_id JOIN organizational_units u ON u.id=m.unit_id AND u.tenant_id=m.tenant_id LEFT JOIN finance_categories c ON c.id=m.category_id AND c.tenant_id=m.tenant_id LEFT JOIN finance_contributions fc ON fc.movement_id=m.id AND fc.tenant_id=m.tenant_id LEFT JOIN people p ON p.id=m.person_id AND p.tenant_id=m.tenant_id LEFT JOIN finance_cost_centers cc ON cc.id=m.cost_center_id AND cc.tenant_id=m.tenant_id LEFT JOIN finance_campaigns ca ON ca.id=m.campaign_id AND ca.tenant_id=m.tenant_id LEFT JOIN finance_funds f ON f.id=m.fund_id AND f.tenant_id=m.tenant_id LEFT JOIN finance_movements reverse ON reverse.original_movement_id=m.id AND reverse.tenant_id=m.tenant_id LEFT JOIN finance_movements original ON original.id=m.original_movement_id AND original.tenant_id=m.tenant_id LEFT JOIN finance_installments i ON i.tenant_id=m.tenant_id AND (i.movement_id=m.id OR i.reversal_movement_id=m.id OR (m.source_entity='PARCELA' AND i.id=m.source_entity_id)) LEFT JOIN finance_obligations o ON o.id=i.obligation_id AND o.tenant_id=i.tenant_id LEFT JOIN finance_periods fp ON fp.id=m.period_id AND fp.tenant_id=m.tenant_id WHERE m.tenant_id=? AND ${scope.sql}${periodFilter} ORDER BY m.occurred_on DESC,m.id DESC LIMIT ? OFFSET ?`).bind(...movementArgs,limit,offset).all(),
    database().prepare(`SELECT COUNT(*) total,COALESCE(SUM(CASE WHEN EXISTS(SELECT 1 FROM finance_contributions fc WHERE fc.tenant_id=m.tenant_id AND fc.movement_id=m.id) THEN 1 ELSE 0 END),0) contributions,COALESCE(SUM(CASE WHEN m.direction='SAIDA' THEN 1 ELSE 0 END),0) expenses FROM finance_movements m WHERE m.tenant_id=? AND ${scope.sql}${periodFilter}`).bind(...movementArgs).first<{total:number;contributions:number;expenses:number}>(),
    database().prepare(`SELECT a.*,COUNT(m.id) movement_count,a.initial_balance_cents+COALESCE(SUM(${movementBalanceCase("m")}),0) balance_cents FROM finance_accounts a LEFT JOIN finance_movements m ON m.account_id=a.id AND m.tenant_id=a.tenant_id WHERE a.tenant_id=? AND ${accountScope.sql} GROUP BY a.id ORDER BY a.name`).bind(tenant,...accountScope.args).all(),
    database().prepare("SELECT * FROM finance_categories WHERE tenant_id=? ORDER BY kind,name").bind(tenant).all(),
    database().prepare("SELECT * FROM finance_payment_methods WHERE tenant_id=? ORDER BY name").bind(tenant).all(),
    database().prepare(`SELECT * FROM finance_cost_centers c WHERE c.tenant_id=? AND ${centerScope.sql} ORDER BY c.name`).bind(tenant,...centerScope.args).all(),
    database().prepare(`SELECT f.*,COALESCE(SUM(CASE WHEN m.status IN ('CONFIRMADO','ESTORNADO') AND m.direction='ENTRADA' THEN m.amount_cents WHEN m.status IN ('CONFIRMADO','ESTORNADO') AND m.direction='SAIDA' THEN -m.amount_cents WHEN m.status='CONFIRMADO' AND m.direction='ESTORNO' AND m.reversal_direction='ENTRADA' THEN m.amount_cents WHEN m.status='CONFIRMADO' AND m.direction='ESTORNO' AND m.reversal_direction='SAIDA' THEN -m.amount_cents ELSE 0 END),0) balance_cents,COUNT(DISTINCT m.id) movement_count,COUNT(DISTINCT ca.id) campaign_count FROM finance_funds f LEFT JOIN finance_movements m ON m.fund_id=f.id AND m.tenant_id=f.tenant_id LEFT JOIN finance_campaigns ca ON ca.fund_id=f.id AND ca.tenant_id=f.tenant_id WHERE f.tenant_id=? AND ${fundScope.sql} GROUP BY f.id ORDER BY f.name`).bind(tenant,...fundScope.args).all(),
    database().prepare(`SELECT c.*,COALESCE(SUM(CASE WHEN m.status IN ('CONFIRMADO','ESTORNADO') AND m.direction='ENTRADA' THEN m.amount_cents WHEN m.status IN ('CONFIRMADO','ESTORNADO') AND m.direction='SAIDA' THEN -m.amount_cents WHEN m.status='CONFIRMADO' AND m.direction='ESTORNO' AND m.reversal_direction='ENTRADA' THEN m.amount_cents WHEN m.status='CONFIRMADO' AND m.direction='ESTORNO' AND m.reversal_direction='SAIDA' THEN -m.amount_cents ELSE 0 END),0) received_cents,(SELECT COALESCE(SUM(p.total_cents),0) FROM finance_campaign_pledges p WHERE p.tenant_id=c.tenant_id AND p.campaign_id=c.id AND p.status<>'CANCELADO') pledged_cents,COUNT(DISTINCT m.id) movement_count,(SELECT COUNT(*) FROM finance_campaign_pledges p WHERE p.tenant_id=c.tenant_id AND p.campaign_id=c.id) pledge_count,(SELECT COUNT(*) FROM finance_obligations o WHERE o.tenant_id=c.tenant_id AND o.campaign_id=c.id) obligation_count FROM finance_campaigns c LEFT JOIN finance_movements m ON m.campaign_id=c.id AND m.tenant_id=c.tenant_id WHERE c.tenant_id=? AND ${campaignScope.sql} GROUP BY c.id ORDER BY c.starts_on DESC`).bind(tenant,...campaignScope.args).all(),
    database().prepare(`SELECT o.*,u.name unit_name,sa.name suggested_account_name,pm.name payment_method_name,COALESCE(SUM(CASE WHEN i.status IN ('PAGA','RECEBIDA') THEN COALESCE(i.settled_amount_cents,i.amount_cents) ELSE 0 END),0) settled_cents,COUNT(i.id) installment_count_total,MIN(CASE WHEN i.status='ABERTA' THEN i.due_on END) next_due_on,(SELECT ii.id FROM finance_installments ii WHERE ii.tenant_id=o.tenant_id AND ii.obligation_id=o.id AND ii.status='ABERTA' ORDER BY ii.due_on,ii.installment_number LIMIT 1) next_installment_id,(SELECT COUNT(*) FROM finance_installments hi WHERE hi.tenant_id=o.tenant_id AND hi.obligation_id=o.id AND hi.movement_id IS NOT NULL) history_count FROM finance_obligations o JOIN organizational_units u ON u.id=o.unit_id AND u.tenant_id=o.tenant_id LEFT JOIN finance_accounts sa ON sa.id=o.suggested_account_id AND sa.tenant_id=o.tenant_id LEFT JOIN finance_payment_methods pm ON pm.id=o.payment_method_id AND pm.tenant_id=o.tenant_id LEFT JOIN finance_installments i ON i.obligation_id=o.id AND i.tenant_id=o.tenant_id WHERE o.tenant_id=? AND ${obligationScope.sql} GROUP BY o.id ORDER BY COALESCE(next_due_on,o.created_at)`).bind(tenant,...obligationScope.args).all(),
    database().prepare(`SELECT i.*,o.kind,o.description obligation_description,o.unit_id,o.suggested_account_id,o.payment_method_id obligation_payment_method_id,a.name settled_account_name,m.status movement_status,m.period_id,p.closure_version,p.lifecycle_state FROM finance_installments i JOIN finance_obligations o ON o.id=i.obligation_id AND o.tenant_id=i.tenant_id LEFT JOIN finance_accounts a ON a.id=i.settled_account_id AND a.tenant_id=i.tenant_id LEFT JOIN finance_movements m ON m.id=i.movement_id AND m.tenant_id=i.tenant_id LEFT JOIN finance_periods p ON p.id=m.period_id AND p.tenant_id=m.tenant_id WHERE i.tenant_id=? AND ${obligationScope.sql} ORDER BY i.due_on,i.installment_number`).bind(tenant,...obligationScope.args).all(),
    database().prepare(`SELECT t.*,oa.name origin_name,da.name destination_name,p.closure_version,p.lifecycle_state FROM finance_transfers t JOIN finance_accounts oa ON oa.id=t.origin_account_id AND oa.tenant_id=t.tenant_id JOIN finance_accounts da ON da.id=t.destination_account_id AND da.tenant_id=t.tenant_id LEFT JOIN finance_movements om ON om.id=t.out_movement_id AND om.tenant_id=t.tenant_id LEFT JOIN finance_periods p ON p.id=om.period_id AND p.tenant_id=t.tenant_id WHERE t.tenant_id=? AND ${transferScope.sql} ORDER BY t.occurred_on DESC LIMIT 100`).bind(tenant,...transferScope.args).all(),
  ]);
  const due = (obligations.results as Array<{status:string;next_due_on:string|null}>).filter(item=>item.status!=="QUITADA"&&item.next_due_on&&item.next_due_on<=new Date().toISOString().slice(0,10)).length;
  return { dashboard: { ...(summary ?? {}), due_count: due }, movements: movements.results, periods: availablePeriods, selectedPeriodId, totalMovements:Number(movementCount?.total||0), totalContributions:Number(movementCount?.contributions||0), totalExpenses:Number(movementCount?.expenses||0), accounts: accounts.results, categories: categories.results, paymentMethods: methods.results, costCenters: centers.results, funds: funds.results, campaigns: campaigns.results, obligations: obligations.results, installments: installments.results, transfers: transfers.results, page, limit };
}

export async function financeOptions(request: Request, query: Record<string, string>) {
  const ctx = await context(request, "FINANCEIRO_VISUALIZAR");
  const scope = scopeSql(ctx.session, "u.id");
  const destinationScope=ctx.session.user.scope==="CONVENCAO"?{sql:"1=1",args:[] as unknown[]}:{sql:"(u.id=? OR u.id=? OR u.parent_id=?)",args:[ctx.session.user.conventionId,ctx.session.user.boundMatrixId,ctx.session.user.boundMatrixId]};
  const search = clean(query.q, 80);
  const requestedUnitId = Number(query.unitId || 0);
  const selectedUnit = requestedUnitId ? await scopedUnit(ctx, requestedUnitId) : null;
  const canIncludeBranches = Boolean(
    selectedUnit?.type === "MATRIZ" &&
      ctx.permissions.has("FINANCEIRO_CONTRIBUINTES_FILIAIS_PESQUISAR"),
  );
  const includeBranches = query.includeBranches === "1" && canIncludeBranches;
  const peopleWhere = ["p.tenant_id=?", "p.status NOT IN ('FALECIDO','TRANSFERIDO','DESLIGADO')"];
  const peopleArgs: unknown[] = [ctx.session.user.tenantId];
  if (selectedUnit?.type === "FILIAL") {
    peopleWhere.push("p.branch_id=?");
    peopleArgs.push(selectedUnit.id);
  } else if (selectedUnit?.type === "MATRIZ") {
    peopleWhere.push(includeBranches ? "p.matrix_id=?" : "p.matrix_id=? AND p.branch_id IS NULL");
    peopleArgs.push(selectedUnit.id);
  } else if (selectedUnit?.type === "CONVENCAO") {
    peopleWhere.push("1=0");
  }
  if (search) {
    if (search.length < 2) return { units: [], destinationUnits: [], people: [], departments: [], canIncludeBranches };
    peopleWhere.push("(p.full_name LIKE ? COLLATE NOCASE OR printf('%06d',p.member_number) LIKE ?)");
    peopleArgs.push(`${search}%`, `%${search.replace(/\D/g, "") || search}%`);
  }
  const [units, destinationUnits, people, departments] = await Promise.all([
    database().prepare(`SELECT u.id,u.name,u.type FROM organizational_units u WHERE u.tenant_id=? AND u.type IN ('CONVENCAO','MATRIZ','FILIAL') AND u.status='ATIVO' AND u.archived_at IS NULL AND ${scope.sql} ORDER BY u.name`).bind(ctx.session.user.tenantId,...scope.args).all(),
    database().prepare(`SELECT u.id,u.name,u.type,u.parent_id FROM organizational_units u WHERE u.tenant_id=? AND u.type IN ('CONVENCAO','MATRIZ','FILIAL') AND u.status='ATIVO' AND u.archived_at IS NULL AND ${destinationScope.sql} ORDER BY CASE u.type WHEN 'CONVENCAO' THEN 0 WHEN 'MATRIZ' THEN 1 ELSE 2 END,u.name`).bind(ctx.session.user.tenantId,...destinationScope.args).all(),
    database().prepare(`SELECT p.id,p.member_number,p.full_name,p.matrix_id,p.branch_id,COALESCE(pref.default_privacy,'IDENTIFICADA') default_privacy,COALESCE(b.name,m.name) unit_name,CASE WHEN b.id IS NULL THEN 'MATRIZ' ELSE 'FILIAL' END unit_type FROM people p JOIN organizational_units m ON m.id=p.matrix_id AND m.tenant_id=p.tenant_id LEFT JOIN organizational_units b ON b.id=p.branch_id AND b.tenant_id=p.tenant_id LEFT JOIN person_financial_preferences pref ON pref.person_id=p.id AND pref.tenant_id=p.tenant_id WHERE ${peopleWhere.join(" AND ")} ORDER BY p.full_name COLLATE NOCASE LIMIT 30`).bind(...peopleArgs).all<{id:number;member_number:number;full_name:string;matrix_id:number;branch_id:number|null;default_privacy:string;unit_name:string;unit_type:string}>(),
    database().prepare("SELECT id,name,unit_id FROM departments WHERE tenant_id=? AND unit_id=? AND status='ATIVO' ORDER BY name LIMIT 100").bind(ctx.session.user.tenantId,ctx.session.activeContext?.unitId).all(),
  ]);
  return {
    units: units.results,
    destinationUnits: destinationUnits.results,
    people: people.results
      .filter((p) => selectedUnit || canAccessMemberScope(ctx.session.user,{tenantId:ctx.session.user.tenantId,matrixId:p.matrix_id,branchId:p.branch_id}))
      .map((p) => ({...p,member_code:formatMemberCode(p.member_number)})),
    departments: departments.results,
    canIncludeBranches,
  };
}

async function validateAccount(ctx: Ctx, accountId: number) {
  const account = await owned<{id:number;unit_id:number;status:string}>("finance_accounts",ctx,accountId);
  await scopedUnit(ctx,account.unit_id); if(account.status!=="ATIVA") throw new ApiError(409,"CONTA_INATIVA","A conta financeira está inativa."); return account;
}

export async function createFinanceRecord(request: Request, input: Input) {
  const type = clean(input.type,40).toUpperCase();
  const permission: PermissionCode = type === "ACCOUNT" ? "FINANCEIRO_CONTAS_CONFIGURAR" : type === "CATEGORY" ? "FINANCEIRO_CATEGORIAS_CONFIGURAR" : type === "CAMPAIGN" || type === "FUND" || type === "PLEDGE" ? "FINANCEIRO_CAMPANHAS_GERENCIAR" : type === "PAYMENT_METHOD" || type === "COST_CENTER" ? "FINANCEIRO_CONFIGURAR" : type === "OBLIGATION" ? (input.kind === "RECEBER" ? "FINANCEIRO_CONTAS_RECEBER_GERENCIAR" : "FINANCEIRO_CONTAS_PAGAR_GERENCIAR") : type === "CONTRIBUTION" ? "FINANCEIRO_CONTRIBUICOES_GERENCIAR" : "FINANCEIRO_LANCAMENTOS_CRIAR";
  const ctx = await context(request,permission), tenant=ctx.session.user.tenantId, stamp=now(), recordId=generatedId();
  if(type==="ACCOUNT") { const unitId=positiveId(input.unitId); await scopedUnit(ctx,unitId); const name=clean(input.name,120), accountType=clean(input.accountType,30); if(!name||!["CAIXA_FISICO","CONTA_CORRENTE","POUPANCA","PIX","COFRE","CARTEIRA","OUTRO"].includes(accountType)) throw new ApiError(400,"DADOS_INVALIDOS","Revise a conta financeira."); const initial=Number(input.initialBalanceCents??0); if(!Number.isSafeInteger(initial)) throw new ApiError(400,"VALOR_INVALIDO","Saldo inicial inválido."); const next={name,description:clean(input.description,300)||null,accountType,institution:clean(input.institution,120)||null,agency:clean(input.agency,30)||null,accountNumber:clean(input.accountNumber,50)||null,pixKey:clean(input.pixKey,160)||null,notes:clean(input.notes,800)||null,initialBalanceCents:initial,initialBalanceDate:isoDate(input.initialBalanceDate)}; await database().batch([database().prepare("INSERT INTO finance_accounts(id,tenant_id,unit_id,name,description,account_type,institution,agency,account_number,pix_key,notes,initial_balance_cents,initial_balance_date,created_by_user_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(recordId,tenant,unitId,next.name,next.description,next.accountType,next.institution,next.agency,next.accountNumber,next.pixKey,next.notes,next.initialBalanceCents,next.initialBalanceDate,ctx.session.user.id,stamp,stamp),audit(ctx,"CRIAR","CONTA",recordId,unitId,null,next)]); return {id:recordId}; }
  if(type==="CATEGORY") { const name=clean(input.name,120),kind=clean(input.kind,10),description=clean(input.description,300)||null; if(!name||!["RECEITA","DESPESA"].includes(kind)) throw new ApiError(400,"DADOS_INVALIDOS","Revise a categoria."); await database().batch([database().prepare("INSERT INTO finance_categories(id,tenant_id,name,description,kind,participates_allocation,requires_fund,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(recordId,tenant,name,description,kind,input.participatesAllocation===true?1:0,input.requiresFund===true?1:0,stamp,stamp),audit(ctx,"CRIAR","CATEGORIA",recordId,null,null,{name,description,kind})]); return {id:recordId}; }
  if(type==="PAYMENT_METHOD") { const name=clean(input.name,80),description=clean(input.description,300)||null;if(!name)throw new ApiError(400,"DADOS_INVALIDOS","Informe a forma de pagamento.");await database().batch([database().prepare("INSERT INTO finance_payment_methods(id,tenant_id,name,description,created_at,updated_at) VALUES(?,?,?,?,?,?)").bind(recordId,tenant,name,description,stamp,stamp),audit(ctx,"CRIAR","FORMA_PAGAMENTO",recordId,null,null,{name,description})]);return{id:recordId};}
  if(type==="COST_CENTER") { const unitId=positiveId(input.unitId),name=clean(input.name,120),centerType=clean(input.centerType,30),description=clean(input.description,300)||null;await scopedUnit(ctx,unitId);if(!name||!["DEPARTAMENTO","MINISTERIO","EBD","SECRETARIA","OUTRO"].includes(centerType))throw new ApiError(400,"DADOS_INVALIDOS","Revise o centro de custo.");await database().batch([database().prepare("INSERT INTO finance_cost_centers(id,tenant_id,unit_id,department_id,name,description,center_type,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(recordId,tenant,unitId,positiveId(input.departmentId,false),name,description,centerType,stamp,stamp),audit(ctx,"CRIAR","CENTRO_CUSTO",recordId,unitId,null,{name,description,centerType})]);return{id:recordId};}
  if(type==="FUND") { const unitId=positiveId(input.unitId),name=clean(input.name,120),description=clean(input.description,500)||null,purpose=clean(input.purpose,500)||null; await scopedUnit(ctx,unitId); if(!name) throw new ApiError(400,"DADOS_INVALIDOS","Informe o fundo."); await database().batch([database().prepare("INSERT INTO finance_funds(id,tenant_id,unit_id,name,restricted,description,purpose,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(recordId,tenant,unitId,name,input.restricted===false?0:1,description,purpose,stamp,stamp),audit(ctx,"CRIAR","FUNDO",recordId,unitId,null,{name,description,purpose,restricted:input.restricted!==false})]); return {id:recordId}; }
  if(type==="CAMPAIGN") { const unitId=positiveId(input.unitId),name=clean(input.name,140),target=input.targetCents?cents(input.targetCents):null,fundId=positiveId(input.fundId,false); await scopedUnit(ctx,unitId); if(!name) throw new ApiError(400,"DADOS_INVALIDOS","Informe a campanha.");if(fundId){const fund=await owned<{unit_id:number;status:string}>("finance_funds",ctx,fundId);if(fund.unit_id!==unitId||fund.status!=="ATIVO")throw new ApiError(403,"FUNDO_FORA_DO_ESCOPO","Selecione um fundo ativo desta unidade.");} await database().batch([database().prepare("INSERT INTO finance_campaigns(id,tenant_id,unit_id,fund_id,name,description,target_cents,starts_on,ends_on,status,created_by_user_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'ATIVA',?,?,?)").bind(recordId,tenant,unitId,fundId,name,clean(input.description,800)||null,target,isoDate(input.startsOn),input.endsOn?isoDate(input.endsOn):null,ctx.session.user.id,stamp,stamp),audit(ctx,"CRIAR","CAMPANHA",recordId,unitId,null,{name,target,fundId})]); return {id:recordId}; }
  if(type==="PLEDGE") {const campaign=await owned<{id:number;unit_id:number;status:string}>("finance_campaigns",ctx,positiveId(input.campaignId));await scopedUnit(ctx,campaign.unit_id);if(campaign.status!=="ATIVA")throw new ApiError(409,"CAMPANHA_INATIVA","A campanha não está ativa.");const total=cents(input.totalCents),count=Math.min(120,Math.max(1,Number(input.installmentCount)||1)),parts=splitInstallments(total,count),first=isoDate(input.firstDueOn),due=new Date(`${first}T12:00:00Z`),personId=positiveId(input.personId,false),supporter=clean(input.supporterName,150)||null;if(!personId&&!supporter)throw new ApiError(400,"DADOS_INVALIDOS","Informe a Pessoa ou o nome do colaborador.");if(personId)await scopedPerson(ctx,personId);const statements=[database().prepare("INSERT INTO finance_campaign_pledges(id,tenant_id,campaign_id,person_id,supporter_name,total_cents,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)").bind(recordId,tenant,campaign.id,personId,supporter,total,stamp,stamp)];for(let index=0;index<count;index++){const itemDue=new Date(due);itemDue.setUTCMonth(itemDue.getUTCMonth()+index);statements.push(database().prepare("INSERT INTO finance_campaign_pledge_installments(id,tenant_id,pledge_id,installment_number,due_on,amount_cents) VALUES(?,?,?,?,?,?)").bind(generatedId()+index,tenant,recordId,index+1,itemDue.toISOString().slice(0,10),parts[index]));}statements.push(audit(ctx,"CRIAR","COMPROMISSO_CAMPANHA",recordId,campaign.unit_id,null,{campaignId:campaign.id,total,count}));await database().batch(statements);return{id:recordId};}
  if(type==="OBLIGATION") return createObligation(ctx,input,recordId,stamp);
  return createMovement(ctx,input,type,recordId,stamp);
}

export async function manageFinanceRegistry(request:Request,input:Input){
  const action=clean(input.action,50).toUpperCase();
  const permission:PermissionCode=action.startsWith("ACCOUNT_")?"FINANCEIRO_CONTAS_CONFIGURAR":action.startsWith("CATEGORY_")?"FINANCEIRO_CATEGORIAS_CONFIGURAR":action.startsWith("CAMPAIGN_")||action.startsWith("FUND_")?"FINANCEIRO_CAMPANHAS_GERENCIAR":"FINANCEIRO_CONFIGURAR";
  const ctx=await context(request,permission),tenant=ctx.session.user.tenantId,stamp=now(),entityId=positiveId(input.id);
  try{
    if(action==="ACCOUNT_UPDATE"){
      const previous=await accountSnapshot(ctx,entityId),name=clean(input.name,120),accountType=clean(input.accountType,30),initial=Number(input.initialBalanceCents);
      if(!name||!["CAIXA_FISICO","CONTA_CORRENTE","POUPANCA","PIX","COFRE","CARTEIRA","OUTRO"].includes(accountType)||!Number.isSafeInteger(initial))throw new ApiError(400,"DADOS_INVALIDOS","Revise os dados da conta.");
      const movementCount=Number(previous.movement_count||0),initialChanged=initial!==Number(previous.initial_balance_cents);
      if(initialChanged&&movementCount>0)throw new ApiError(409,"SALDO_INICIAL_BLOQUEADO","Esta conta já possui movimentações. Use Ajustar saldo para preservar o histórico.");
      const next={name,description:clean(input.description,300)||null,accountType,institution:clean(input.institution,120)||null,agency:clean(input.agency,30)||null,accountNumber:clean(input.accountNumber,50)||null,pixKey:clean(input.pixKey,160)||null,notes:clean(input.notes,800)||null,initialBalanceCents:initial,initialBalanceDate:isoDate(input.initialBalanceDate)};
      const statements=[database().prepare("UPDATE finance_accounts SET name=?,description=?,account_type=?,institution=?,agency=?,account_number=?,pix_key=?,notes=?,initial_balance_cents=?,initial_balance_date=?,updated_at=? WHERE id=? AND tenant_id=?").bind(next.name,next.description,next.accountType,next.institution,next.agency,next.accountNumber,next.pixKey,next.notes,next.initialBalanceCents,next.initialBalanceDate,stamp,entityId,tenant),audit(ctx,"EDITAR","CONTA",entityId,Number(previous.unit_id),previous,next)];
      if(initialChanged)statements.push(audit(ctx,"ALTERAR_SALDO_INICIAL","CONTA",entityId,Number(previous.unit_id),{initialBalanceCents:previous.initial_balance_cents},{initialBalanceCents:initial},clean(input.reason,500)||"Correção antes do primeiro movimento"));
      await database().batch(statements);return{entity:"ACCOUNT",record:await accountSnapshot(ctx,entityId),message:"Conta atualizada com sucesso."};
    }
    if(action==="ACCOUNT_ARCHIVE"||action==="ACCOUNT_RESTORE"){
      const previous=await accountSnapshot(ctx,entityId),archive=action==="ACCOUNT_ARCHIVE",status=archive?"INATIVA":"ATIVA";
      await database().batch([database().prepare("UPDATE finance_accounts SET status=?,archived_at=?,archived_by_user_id=?,updated_at=? WHERE id=? AND tenant_id=?").bind(status,archive?stamp:null,archive?ctx.session.user.id:null,stamp,entityId,tenant),audit(ctx,archive?"ARQUIVAR":"REATIVAR","CONTA",entityId,Number(previous.unit_id),{status:previous.status},{status})]);
      return{entity:"ACCOUNT",record:await accountSnapshot(ctx,entityId),message:archive?"Conta arquivada. O histórico foi preservado.":"Conta reativada com sucesso."};
    }
    if(action==="ACCOUNT_ADJUST"){
      const previous=await accountSnapshot(ctx,entityId),reason=clean(input.reason,500),target=Number(input.correctBalanceCents),occurredOn=isoDate(input.occurredOn);
      if(previous.status!=="ATIVA")throw new ApiError(409,"CONTA_INATIVA","Reative a conta antes de ajustar o saldo.");
      if(Number(previous.movement_count||0)<1)throw new ApiError(409,"USE_SALDO_INICIAL","Esta conta ainda não possui movimentos. Corrija o saldo inicial na edição da conta.");
      if(!Number.isSafeInteger(target))throw new ApiError(400,"VALOR_INVALIDO","Informe o saldo correto.");
      if(reason.length<5)throw new ApiError(400,"MOTIVO_OBRIGATORIO","Informe o motivo do ajuste com pelo menos 5 caracteres.");
      const current=Number(previous.balance_cents),difference=target-current;
      if(!difference)throw new ApiError(409,"AJUSTE_SEM_DIFERENCA","O saldo informado já é o saldo atual da conta.");
      const period=await assertOpenFinancePeriod(ctx.session,Number(previous.unit_id),occurredOn.slice(0,7)),movementId=generatedId(),direction=difference>0?"ENTRADA":"SAIDA";
      await database().batch([database().prepare("INSERT INTO finance_movements(id,tenant_id,unit_id,account_id,direction,adjustment_direction,amount_cents,occurred_on,competency,description,source,source_entity,source_entity_id,privacy,idempotency_key,created_by_user_id,created_at,updated_at,period_id,created_during_reopening) VALUES(?,?,?,?, 'AJUSTE',?,?,?,?,?,'OUTRO','AJUSTE_SALDO',?,'IDENTIFICADA_PRIVADA',?,?,?,?,?,?)").bind(movementId,tenant,Number(previous.unit_id),entityId,direction,Math.abs(difference),occurredOn,occurredOn.slice(0,7),`Ajuste de saldo — ${reason}`,entityId,`balance-adjustment:${movementId}`,ctx.session.user.id,stamp,stamp,period.id,period.closure_version>0?1:0),audit(ctx,"AJUSTAR_SALDO","CONTA",entityId,Number(previous.unit_id),{previousBalanceCents:current},{resultingBalanceCents:target,movementId,adjustmentCents:difference},reason)]);
      return{entity:"ACCOUNT",record:await accountSnapshot(ctx,entityId),message:`Ajuste de ${difference>0?"entrada":"saída"} registrado com histórico.`};
    }
    if(action==="CATEGORY_UPDATE"||action==="CATEGORY_ARCHIVE"||action==="CATEGORY_RESTORE"){
      const previous=await owned<Record<string,unknown>>("finance_categories",ctx,entityId);
      if(action==="CATEGORY_UPDATE"){
        const name=clean(input.name,120),kind=clean(input.kind,10),next={name,description:clean(input.description,300)||null,kind,participatesAllocation:input.participatesAllocation===true?1:0,requiresFund:input.requiresFund===true?1:0};
        if(!name||!["RECEITA","DESPESA"].includes(kind))throw new ApiError(400,"DADOS_INVALIDOS","Revise os dados da categoria.");
        await database().batch([database().prepare("UPDATE finance_categories SET name=?,description=?,kind=?,participates_allocation=?,requires_fund=?,updated_at=? WHERE id=? AND tenant_id=?").bind(next.name,next.description,next.kind,next.participatesAllocation,next.requiresFund,stamp,entityId,tenant),audit(ctx,"EDITAR","CATEGORIA",entityId,null,previous,next)]);
        return{entity:"CATEGORY",record:await owned("finance_categories",ctx,entityId),message:"Categoria atualizada com sucesso."};
      }
      const archive=action==="CATEGORY_ARCHIVE",status=archive?"INATIVA":"ATIVA";
      await database().batch([database().prepare("UPDATE finance_categories SET status=?,archived_at=?,archived_by_user_id=?,updated_at=? WHERE id=? AND tenant_id=?").bind(status,archive?stamp:null,archive?ctx.session.user.id:null,stamp,entityId,tenant),audit(ctx,archive?"ARQUIVAR":"REATIVAR","CATEGORIA",entityId,null,{status:previous.status},{status})]);
      return{entity:"CATEGORY",record:await owned("finance_categories",ctx,entityId),message:archive?"Categoria arquivada. Os lançamentos antigos continuam vinculados.":"Categoria reativada com sucesso."};
    }
    if(action.startsWith("CAMPAIGN_")){
      const previous=await owned<Record<string,unknown>>("finance_campaigns",ctx,entityId);await scopedUnit(ctx,Number(previous.unit_id));
      const usage=await database().prepare("SELECT (SELECT COUNT(*) FROM finance_movements WHERE tenant_id=? AND campaign_id=?)+(SELECT COUNT(*) FROM finance_campaign_pledges WHERE tenant_id=? AND campaign_id=?)+(SELECT COUNT(*) FROM finance_obligations WHERE tenant_id=? AND campaign_id=?) total").bind(tenant,entityId,tenant,entityId,tenant,entityId).first<{total:number}>();
      if(action==="CAMPAIGN_UPDATE"){
        const name=clean(input.name,140),target=input.targetCents?cents(input.targetCents):null,fundId=positiveId(input.fundId,false),status=clean(input.status,20)||String(previous.status),description=clean(input.description,800)||null,startsOn=isoDate(input.startsOn),endsOn=input.endsOn?isoDate(input.endsOn):null;
        if(!name||!(["PLANEJADA","ATIVA","CONCLUIDA","CANCELADA"] as string[]).includes(status))throw new ApiError(400,"DADOS_INVALIDOS","Revise os dados da campanha.");
        if(fundId){const fund=await owned<{unit_id:number;status:string}>("finance_funds",ctx,fundId);if(fund.unit_id!==Number(previous.unit_id)||fund.status!=="ATIVO")throw new ApiError(403,"FUNDO_FORA_DO_ESCOPO","Selecione um fundo ativo desta unidade.");}
        const next={name,description,targetCents:target,startsOn,endsOn,fundId,status};await database().batch([database().prepare("UPDATE finance_campaigns SET name=?,description=?,target_cents=?,starts_on=?,ends_on=?,fund_id=?,status=?,updated_at=? WHERE id=? AND tenant_id=? AND unit_id=?").bind(name,description,target,startsOn,endsOn,fundId,status,stamp,entityId,tenant,previous.unit_id),audit(ctx,"EDITAR_CAMPANHA","CAMPANHA",entityId,Number(previous.unit_id),previous,next)]);return{entity:"CAMPAIGN",record:await owned("finance_campaigns",ctx,entityId),message:"Campanha atualizada."};
      }
      if(action==="CAMPAIGN_DELETE"){
        if(Number(usage?.total||0)>0)throw new ApiError(409,"CAMPANHA_COM_HISTORICO","Esta campanha possui movimentações ou compromissos. Arquive ou encerre para preservar o histórico.");
        await database().batch([audit(ctx,"EXCLUIR_CAMPANHA","CAMPANHA",entityId,Number(previous.unit_id),previous,{deleted:true}),database().prepare("DELETE FROM finance_campaigns WHERE id=? AND tenant_id=? AND unit_id=?").bind(entityId,tenant,previous.unit_id)]);return{entity:"CAMPAIGN",deleted:true,message:"Campanha sem movimentação excluída."};
      }
      const archive=action==="CAMPAIGN_ARCHIVE",complete=action==="CAMPAIGN_COMPLETE",restore=action==="CAMPAIGN_RESTORE";if(!archive&&!complete&&!restore)throw new ApiError(400,"ACAO_INVALIDA","Ação de campanha inválida.");const status=restore?"ATIVA":complete?"CONCLUIDA":"CANCELADA",reason=clean(input.reason,500)||null;
      await database().batch([database().prepare("UPDATE finance_campaigns SET status=?,archived_at=?,archived_by_user_id=?,archive_reason=?,updated_at=? WHERE id=? AND tenant_id=? AND unit_id=?").bind(status,archive?stamp:null,archive?ctx.session.user.id:null,archive?reason:null,stamp,entityId,tenant,previous.unit_id),audit(ctx,restore?"REATIVAR_CAMPANHA":complete?"ENCERRAR_CAMPANHA":"ARQUIVAR_CAMPANHA","CAMPANHA",entityId,Number(previous.unit_id),previous,{status,reason})]);return{entity:"CAMPAIGN",record:await owned("finance_campaigns",ctx,entityId),message:restore?"Campanha reativada.":complete?"Campanha encerrada com histórico preservado.":"Campanha arquivada com histórico preservado."};
    }
    if(action.startsWith("FUND_")){
      const previous=await owned<Record<string,unknown>>("finance_funds",ctx,entityId);await scopedUnit(ctx,Number(previous.unit_id));
      const usage=await database().prepare(`SELECT (SELECT COUNT(*) FROM finance_movements WHERE tenant_id=? AND fund_id=?)+(SELECT COUNT(*) FROM finance_campaigns WHERE tenant_id=? AND fund_id=?)+(SELECT COUNT(*) FROM finance_obligations WHERE tenant_id=? AND fund_id=?) total,COALESCE(SUM(CASE WHEN status IN ('CONFIRMADO','ESTORNADO') AND direction='ENTRADA' THEN amount_cents WHEN status IN ('CONFIRMADO','ESTORNADO') AND direction='SAIDA' THEN -amount_cents WHEN status='CONFIRMADO' AND direction='ESTORNO' AND reversal_direction='ENTRADA' THEN amount_cents WHEN status='CONFIRMADO' AND direction='ESTORNO' AND reversal_direction='SAIDA' THEN -amount_cents ELSE 0 END),0) balance_cents FROM finance_movements WHERE tenant_id=? AND fund_id=?`).bind(tenant,entityId,tenant,entityId,tenant,entityId,tenant,entityId).first<{total:number;balance_cents:number}>();
      if(action==="FUND_UPDATE"){
        const name=clean(input.name,120),description=clean(input.description,500)||null,purpose=clean(input.purpose,500)||null,restricted=input.restricted===true?1:0;if(!name)throw new ApiError(400,"DADOS_INVALIDOS","Informe o nome do fundo.");const next={name,description,purpose,restricted};await database().batch([database().prepare("UPDATE finance_funds SET name=?,description=?,purpose=?,restricted=?,updated_at=? WHERE id=? AND tenant_id=? AND unit_id=?").bind(name,description,purpose,restricted,stamp,entityId,tenant,previous.unit_id),audit(ctx,"EDITAR_FUNDO","FUNDO",entityId,Number(previous.unit_id),previous,next)]);return{entity:"FUND",record:await owned("finance_funds",ctx,entityId),message:"Fundo atualizado."};
      }
      if(action==="FUND_DELETE"){
        if(Number(usage?.total||0)>0||Number(usage?.balance_cents||0)!==0)throw new ApiError(409,"FUNDO_COM_HISTORICO","Este fundo possui uso ou saldo vinculado. Arquive para preservar o histórico.");await database().batch([audit(ctx,"EXCLUIR_FUNDO","FUNDO",entityId,Number(previous.unit_id),previous,{deleted:true}),database().prepare("DELETE FROM finance_funds WHERE id=? AND tenant_id=? AND unit_id=?").bind(entityId,tenant,previous.unit_id)]);return{entity:"FUND",deleted:true,message:"Fundo sem movimentação excluído."};
      }
      const archive=action==="FUND_ARCHIVE",restore=action==="FUND_RESTORE";if(!archive&&!restore)throw new ApiError(400,"ACAO_INVALIDA","Ação de fundo inválida.");const status=archive?"INATIVO":"ATIVO",reason=clean(input.reason,500)||null;await database().batch([database().prepare("UPDATE finance_funds SET status=?,archived_at=?,archived_by_user_id=?,archive_reason=?,updated_at=? WHERE id=? AND tenant_id=? AND unit_id=?").bind(status,archive?stamp:null,archive?ctx.session.user.id:null,archive?reason:null,stamp,entityId,tenant,previous.unit_id),audit(ctx,archive?"ARQUIVAR_FUNDO":"REATIVAR_FUNDO","FUNDO",entityId,Number(previous.unit_id),previous,{status,balanceCents:Number(usage?.balance_cents||0),reason})]);return{entity:"FUND",record:await owned("finance_funds",ctx,entityId),balanceCents:Number(usage?.balance_cents||0),message:archive?"Fundo arquivado para novos lançamentos; saldo e histórico preservados.":"Fundo reativado."};
    }
    if(action==="PAYMENT_METHOD_UPDATE"||action==="PAYMENT_METHOD_ARCHIVE"||action==="PAYMENT_METHOD_RESTORE"){
      const previous=await owned<Record<string,unknown>>("finance_payment_methods",ctx,entityId);
      if(action==="PAYMENT_METHOD_UPDATE"){
        const name=clean(input.name,80),description=clean(input.description,300)||null;if(!name)throw new ApiError(400,"DADOS_INVALIDOS","Informe o nome da forma de pagamento.");
        await database().batch([database().prepare("UPDATE finance_payment_methods SET name=?,description=?,updated_at=? WHERE id=? AND tenant_id=?").bind(name,description,stamp,entityId,tenant),audit(ctx,"EDITAR","FORMA_PAGAMENTO",entityId,null,previous,{name,description})]);
        return{entity:"PAYMENT_METHOD",record:await owned("finance_payment_methods",ctx,entityId),message:"Forma de pagamento atualizada."};
      }
      const archive=action==="PAYMENT_METHOD_ARCHIVE",status=archive?"INATIVO":"ATIVO";
      await database().batch([database().prepare("UPDATE finance_payment_methods SET status=?,archived_at=?,archived_by_user_id=?,updated_at=? WHERE id=? AND tenant_id=?").bind(status,archive?stamp:null,archive?ctx.session.user.id:null,stamp,entityId,tenant),audit(ctx,archive?"ARQUIVAR":"REATIVAR","FORMA_PAGAMENTO",entityId,null,{status:previous.status},{status})]);
      return{entity:"PAYMENT_METHOD",record:await owned("finance_payment_methods",ctx,entityId),message:archive?"Forma de pagamento arquivada.":"Forma de pagamento reativada."};
    }
    if(action==="COST_CENTER_UPDATE"||action==="COST_CENTER_ARCHIVE"||action==="COST_CENTER_RESTORE"){
      const previous=await owned<Record<string,unknown>>("finance_cost_centers",ctx,entityId);await scopedUnit(ctx,Number(previous.unit_id));
      if(action==="COST_CENTER_UPDATE"){
        const name=clean(input.name,120),centerType=clean(input.centerType,30),departmentId=positiveId(input.departmentId,false),description=clean(input.description,300)||null;
        if(!name||!["DEPARTAMENTO","MINISTERIO","EBD","SECRETARIA","OUTRO"].includes(centerType))throw new ApiError(400,"DADOS_INVALIDOS","Revise os dados do centro de custo.");
        await database().batch([database().prepare("UPDATE finance_cost_centers SET name=?,description=?,center_type=?,department_id=?,updated_at=? WHERE id=? AND tenant_id=? AND unit_id=?").bind(name,description,centerType,departmentId,stamp,entityId,tenant,previous.unit_id),audit(ctx,"EDITAR","CENTRO_CUSTO",entityId,Number(previous.unit_id),previous,{name,description,centerType,departmentId})]);
        return{entity:"COST_CENTER",record:await owned("finance_cost_centers",ctx,entityId),message:"Centro de custo atualizado."};
      }
      const archive=action==="COST_CENTER_ARCHIVE",status=archive?"INATIVO":"ATIVO";
      await database().batch([database().prepare("UPDATE finance_cost_centers SET status=?,archived_at=?,archived_by_user_id=?,updated_at=? WHERE id=? AND tenant_id=? AND unit_id=?").bind(status,archive?stamp:null,archive?ctx.session.user.id:null,stamp,entityId,tenant,previous.unit_id),audit(ctx,archive?"ARQUIVAR":"REATIVAR","CENTRO_CUSTO",entityId,Number(previous.unit_id),{status:previous.status},{status})]);
      return{entity:"COST_CENTER",record:await owned("finance_cost_centers",ctx,entityId),message:archive?"Centro de custo arquivado.":"Centro de custo reativado."};
    }
    throw new ApiError(400,"ACAO_INVALIDA","Ação de cadastro financeiro inválida.");
  }catch(error){
    if(error instanceof ApiError)throw error;
    if(error instanceof Error&&/UNIQUE/i.test(error.message))throw new ApiError(409,"CADASTRO_DUPLICADO","Já existe um cadastro com este nome no mesmo escopo.");
    throw error;
  }
}

async function createMovement(ctx:Ctx,input:Input,type:string,movementId:number,stamp:string) {
  const account=await validateAccount(ctx,positiveId(input.accountId)), tenant=ctx.session.user.tenantId, direction=type==="CONTRIBUTION"?"ENTRADA":clean(input.direction,20);
  if(!["ENTRADA","SAIDA"].includes(direction)) throw new ApiError(400,"DADOS_INVALIDOS","Tipo de movimento inválido.");
  const amount=cents(input.amountCents), personId=positiveId(input.personId,false);
  const preferredPrivacy=personId?(await database().prepare("SELECT default_privacy FROM person_financial_preferences WHERE tenant_id=? AND person_id=?").bind(ctx.session.user.tenantId,personId).first<{default_privacy:FinancePrivacy}>())?.default_privacy:null;
  const privacy=(clean(input.privacy,30)||(personId?preferredPrivacy||"IDENTIFICADA":"ANONIMA")) as FinancePrivacy;
  if(personId)await scopedPerson(ctx,personId);
  const categoryId=positiveId(input.categoryId,false),paymentMethodId=positiveId(input.paymentMethodId,false),campaignIdInput=positiveId(input.campaignId,false),fundId=positiveId(input.fundId,false),costCenterId=positiveId(input.costCenterId,false);
  await validateFinanceCategory({tenantId:tenant,categoryId,expectedKind:direction==="ENTRADA"?"RECEITA":"DESPESA",fundId});
  if(paymentMethodId){const method=await owned<{status:string}>("finance_payment_methods",ctx,paymentMethodId);if(method.status!=="ATIVO")throw new ApiError(409,"FORMA_PAGAMENTO_INATIVA","Selecione uma forma de pagamento ativa.");}
  if(campaignIdInput){const campaign=await owned<{unit_id:number;status:string;archived_at:string|null}>("finance_campaigns",ctx,campaignIdInput);if(campaign.unit_id!==account.unit_id)throw new ApiError(403,"FORA_DO_ESCOPO","A campanha não pertence à unidade da conta.");if(campaign.status!=="ATIVA"||campaign.archived_at)throw new ApiError(409,"CAMPANHA_INATIVA","Selecione uma campanha ativa.");}
  if(fundId){const fund=await owned<{unit_id:number;status:string}>("finance_funds",ctx,fundId);if(fund.unit_id!==account.unit_id)throw new ApiError(403,"FORA_DO_ESCOPO","O fundo não pertence à unidade da conta.");if(fund.status!=="ATIVO")throw new ApiError(409,"FUNDO_INATIVO","Selecione um fundo ativo.");}
  if(costCenterId){const center=await owned<{unit_id:number;status:string}>("finance_cost_centers",ctx,costCenterId);if(center.unit_id!==account.unit_id)throw new ApiError(403,"FORA_DO_ESCOPO","O centro de custo não pertence à unidade da conta.");if(center.status!=="ATIVO")throw new ApiError(409,"CENTRO_CUSTO_INATIVO","Selecione um centro de custo ativo.");}
  if(type==="CONTRIBUTION") { try { contributionIdentity(privacy,personId); } catch { throw new ApiError(400,"CONTRIBUINTE_OBRIGATORIO","Selecione uma Pessoa ou marque a contribuição como anônima."); } }
  const description=clean(input.description,300)|| (type==="CONTRIBUTION"?"Contribuição":"Lançamento manual"),movementCompetency=competency(input.competency),period=await assertOpenFinancePeriodById(ctx.session,account.unit_id,input.periodId?positiveId(input.periodId):0),createdDuringReopening=period.closure_version>0?1:0;
  const movement=database().prepare("INSERT INTO finance_movements(id,tenant_id,unit_id,account_id,direction,amount_cents,occurred_on,competency,description,category_id,payment_method_id,person_id,cost_center_id,department_id,campaign_id,fund_id,source,source_entity,source_entity_id,privacy,idempotency_key,created_by_user_id,created_at,updated_at,period_id,created_during_reopening) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(movementId,tenant,account.unit_id,account.id,direction,amount,isoDate(input.occurredOn),movementCompetency,description,categoryId,paymentMethodId,privacy==="ANONIMA"?null:personId,costCenterId,positiveId(input.departmentId,false),campaignIdInput,fundId,["MANUAL","EBD","CAMPANHA","CONTA_RECEBER","OUTRO"].includes(clean(input.source,30))?clean(input.source,30):"MANUAL",clean(input.sourceEntity,60)||null,positiveId(input.sourceEntityId,false),privacy,clean(input.idempotencyKey,100)||null,ctx.session.user.id,stamp,stamp,period.id,createdDuringReopening);
  const statements=[movement];
  if(type==="CONTRIBUTION") { const contributionType=clean(input.contributionType,30); if(!["DIZIMO","OFERTA","VOTO","DOACAO","MISSOES","CAMPANHA","OFERTA_VOLUNTARIA","OUTRA"].includes(contributionType)) throw new ApiError(400,"DADOS_INVALIDOS","Tipo de contribuição inválido."); statements.push(database().prepare("INSERT INTO finance_contributions(id,tenant_id,movement_id,contribution_type,person_id,privacy,created_at) VALUES(?,?,?,?,?,?,?)").bind(generatedId(),tenant,movementId,contributionType,privacy==="ANONIMA"?null:personId,privacy,stamp)); }
  statements.push(audit(ctx,"CRIAR",type==="CONTRIBUTION"?"CONTRIBUICAO":"MOVIMENTO",movementId,account.unit_id,null,{direction,amount,privacy,createdDuringReopening:Boolean(createdDuringReopening),reopeningNumber:period.reopen_count})); await database().batch(statements); const campaignId=positiveId(input.campaignId,false);if(campaignId){const campaign=await database().prepare("SELECT c.name,c.target_cents,COALESCE(SUM(CASE WHEN m.status IN ('CONFIRMADO','ESTORNADO') AND m.direction='ENTRADA' THEN m.amount_cents WHEN m.status IN ('CONFIRMADO','ESTORNADO') AND m.direction='SAIDA' THEN -m.amount_cents WHEN m.status='CONFIRMADO' AND m.direction='ESTORNO' AND m.reversal_direction='ENTRADA' THEN m.amount_cents WHEN m.status='CONFIRMADO' AND m.direction='ESTORNO' AND m.reversal_direction='SAIDA' THEN -m.amount_cents ELSE 0 END),0) received FROM finance_campaigns c LEFT JOIN finance_movements m ON m.campaign_id=c.id AND m.tenant_id=c.tenant_id WHERE c.id=? AND c.tenant_id=? GROUP BY c.id").bind(campaignId,tenant).first<{name:string;target_cents:number|null;received:number}>();if(campaign?.target_cents&&campaign.received>=campaign.target_cents)await notifyFinance(ctx,{type:"FINANCEIRO_CAMPANHA_META_ATINGIDA",title:"Meta de campanha atingida",message:`A campanha ${campaign.name} alcançou a meta definida.`,route:"/painel/financeiro?aba=campanhas",source:"FINANCE_CAMPAIGN",sourceId:campaignId,unitId:account.unit_id,groupKey:`finance-campaign-target:${campaignId}`});} return {id:movementId};
}

async function createObligation(ctx:Ctx,input:Input,obligationId:number,stamp:string) {
  const unitId=positiveId(input.unitId); await scopedUnit(ctx,unitId); const kind=clean(input.kind,10),obligationCompetency=competency(input.competency); if(!["PAGAR","RECEBER"].includes(kind)) throw new ApiError(400,"DADOS_INVALIDOS","Tipo de conta inválido.");await assertOpenFinancePeriod(ctx.session,unitId,obligationCompetency);
  const total=cents(input.totalCents), count=Math.min(120,Math.max(1,Number(input.installmentCount)||1)), parts=splitInstallments(total,count), firstDue=isoDate(input.firstDueOn), due=new Date(`${firstDue}T12:00:00Z`);
  const personId=positiveId(input.personId,false),categoryId=positiveId(input.categoryId,false),costCenterId=positiveId(input.costCenterId,false),campaignId=positiveId(input.campaignId,false),fundId=positiveId(input.fundId,false),suggestedAccountId=positiveId(input.suggestedAccountId,false),paymentMethodId=positiveId(input.paymentMethodId,false);
  if(personId)await scopedPerson(ctx,personId);
  if(categoryId){const row=await owned<{status:string}>("finance_categories",ctx,categoryId);if(row.status!=="ATIVA")throw new ApiError(409,"CATEGORIA_INATIVA","Selecione uma categoria ativa.");}
  if(costCenterId){const row=await owned<{unit_id:number;status:string}>("finance_cost_centers",ctx,costCenterId);if(row.unit_id!==unitId||row.status!=="ATIVO")throw new ApiError(403,"FORA_DO_ESCOPO","Centro de custo inválido para a unidade.");}
  if(campaignId){const row=await owned<{unit_id:number;status:string}>("finance_campaigns",ctx,campaignId);if(row.unit_id!==unitId||row.status!=="ATIVA")throw new ApiError(403,"FORA_DO_ESCOPO","Campanha inválida para a unidade.");}
  if(fundId){const row=await owned<{unit_id:number;status:string}>("finance_funds",ctx,fundId);if(row.unit_id!==unitId||row.status!=="ATIVO")throw new ApiError(403,"FORA_DO_ESCOPO","Fundo inválido para a unidade.");}
  if(suggestedAccountId){const row=await validateAccount(ctx,suggestedAccountId);if(row.unit_id!==unitId)throw new ApiError(403,"FORA_DO_ESCOPO","Conta sugerida inválida para a unidade.");}
  if(paymentMethodId){const row=await owned<{status:string}>("finance_payment_methods",ctx,paymentMethodId);if(row.status!=="ATIVO")throw new ApiError(409,"FORMA_PAGAMENTO_INATIVA","Selecione uma forma de pagamento ativa.");}
  const statements=[database().prepare("INSERT INTO finance_obligations(id,tenant_id,unit_id,kind,description,beneficiary_name,person_id,category_id,cost_center_id,campaign_id,fund_id,total_cents,competency,notes,document_reference,suggested_account_id,payment_method_id,created_by_user_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(obligationId,ctx.session.user.tenantId,unitId,kind,clean(input.description,300)||"Obrigação financeira",clean(input.beneficiaryName,160)||null,personId,categoryId,costCenterId,campaignId,fundId,total,obligationCompetency,clean(input.notes,800)||null,clean(input.documentReference,180)||null,suggestedAccountId,paymentMethodId,ctx.session.user.id,stamp,stamp)];
  for(let index=0;index<count;index++){const itemDue=new Date(due);itemDue.setUTCMonth(itemDue.getUTCMonth()+index);statements.push(database().prepare("INSERT INTO finance_installments(id,tenant_id,obligation_id,installment_number,installment_count,due_on,amount_cents,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(generatedId()+index,ctx.session.user.tenantId,obligationId,index+1,count,itemDue.toISOString().slice(0,10),parts[index],stamp,stamp));}
  statements.push(audit(ctx,"CRIAR","OBRIGACAO",obligationId,unitId,null,{kind,total,count})); await database().batch(statements);const alertLimit=new Date();alertLimit.setUTCDate(alertLimit.getUTCDate()+7);if(firstDue<=alertLimit.toISOString().slice(0,10))await notifyFinance(ctx,{type:"FINANCEIRO_CONTA_VENCENDO",title:`Conta a ${kind==="PAGAR"?"pagar":"receber"} em atenção`,message:`${clean(input.description,160)||"Obrigação financeira"} vence em ${firstDue}.`,route:`/painel/financeiro?aba=${kind==="PAGAR"?"pagar":"receber"}`,source:"FINANCE_OBLIGATION",sourceId:obligationId,unitId,groupKey:`finance-obligation-due:${obligationId}:${firstDue}`}); return {id:obligationId};
}

export async function financeOperation(request:Request,input:Input) {
  const action=clean(input.action,30).toUpperCase(), permission:PermissionCode=action==="TRANSFER"?"FINANCEIRO_TRANSFERENCIAS_GERENCIAR":action==="REVERSE"?"FINANCEIRO_LANCAMENTOS_ESTORNAR":input.kind==="RECEBER"?"FINANCEIRO_CONTAS_RECEBER_GERENCIAR":"FINANCEIRO_CONTAS_PAGAR_GERENCIAR";
  const ctx=await context(request,permission), tenant=ctx.session.user.tenantId, stamp=now();
  if(action==="TRANSFER") { const origin=await validateAccount(ctx,positiveId(input.originAccountId)),destination=await validateAccount(ctx,positiveId(input.destinationAccountId)),amount=cents(input.amountCents); if(origin.unit_id!==destination.unit_id||!canTransfer(origin.id,destination.id,amount)) throw new ApiError(400,"TRANSFERENCIA_INVALIDA","Use contas diferentes da mesma unidade e um valor positivo."); const transferId=generatedId(),outId=generatedId(),inId=generatedId(),day=isoDate(input.occurredOn),comp=day.slice(0,7),description=clean(input.description,300)||"Transferência entre contas",notes=clean(input.notes,800)||null,period=await assertOpenFinancePeriod(ctx.session,origin.unit_id,comp); await database().batch([database().prepare("INSERT INTO finance_movements(id,tenant_id,unit_id,account_id,direction,amount_cents,occurred_on,competency,description,source,privacy,transfer_id,idempotency_key,created_by_user_id,created_at,period_id) VALUES(?,?,?,?,?,?,?,?,?,'MANUAL','IDENTIFICADA_PRIVADA',?,?,?,?,?)").bind(outId,tenant,origin.unit_id,origin.id,"TRANSFERENCIA_SAIDA",amount,day,comp,description,transferId,`transfer:${transferId}:out`,ctx.session.user.id,stamp,period.id),database().prepare("INSERT INTO finance_movements(id,tenant_id,unit_id,account_id,direction,amount_cents,occurred_on,competency,description,source,privacy,transfer_id,idempotency_key,created_by_user_id,created_at,period_id) VALUES(?,?,?,?,?,?,?,?,?,'MANUAL','IDENTIFICADA_PRIVADA',?,?,?,?,?)").bind(inId,tenant,destination.unit_id,destination.id,"TRANSFERENCIA_ENTRADA",amount,day,comp,description,transferId,`transfer:${transferId}:in`,ctx.session.user.id,stamp,period.id),database().prepare("INSERT INTO finance_transfers(id,tenant_id,unit_id,origin_account_id,destination_account_id,amount_cents,occurred_on,out_movement_id,in_movement_id,description,notes,created_by_user_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(transferId,tenant,origin.unit_id,origin.id,destination.id,amount,day,outId,inId,description,notes,ctx.session.user.id,stamp,stamp),audit(ctx,"TRANSFERIR","TRANSFERENCIA",transferId,origin.unit_id,null,{origin:origin.id,destination:destination.id,amount})]); return {id:transferId}; }
  if(action==="REVERSE") {
    const original=await owned<{id:number;unit_id:number;account_id:number;direction:string;amount_cents:number;occurred_on:string;competency:string;description:string;status:string;category_id:number|null;payment_method_id:number|null;person_id:number|null;cost_center_id:number|null;department_id:number|null;campaign_id:number|null;fund_id:number|null;privacy:FinancePrivacy;period_id:number;quick_session_id:number|null;version:number}>("finance_movements",ctx,positiveId(input.movementId));
    await scopedUnit(ctx,original.unit_id);
    const period=await assertOpenFinancePeriodById(ctx.session,original.unit_id,original.period_id);
    if(period.closure_version===0)throw new ApiError(409,"CORRECAO_DIRETA_DISPONIVEL","Este caixa nunca foi fechado. Edite ou exclua o lançamento em vez de gerar estorno.");
    if(original.status!=="CONFIRMADO"||!["ENTRADA","SAIDA"].includes(original.direction))throw new ApiError(409,"ESTORNO_INVALIDO","Este movimento não pode ser estornado.");
    const existing=await database().prepare("SELECT id FROM finance_movements WHERE tenant_id=? AND original_movement_id=? LIMIT 1").bind(tenant,original.id).first<{id:number}>();
    if(existing)throw new ApiError(409,"ESTORNO_DUPLICADO","Este lançamento já possui um estorno.");
    const reason=clean(input.reason,500);if(reason.length<5)throw new ApiError(400,"JUSTIFICATIVA_OBRIGATORIA","Informe a justificativa do estorno.");
    const reverseId=generatedId(),reversalDirection=original.direction==="ENTRADA"?"SAIDA":"ENTRADA";
    await database().batch([
      database().prepare("INSERT INTO finance_movements(id,tenant_id,unit_id,account_id,direction,reversal_direction,amount_cents,occurred_on,competency,description,category_id,payment_method_id,person_id,cost_center_id,department_id,campaign_id,fund_id,source,source_entity,source_entity_id,privacy,original_movement_id,idempotency_key,created_by_user_id,created_at,updated_at,period_id,quick_session_id,created_during_reopening) VALUES(?,?,?,?,'ESTORNO',?,?,?,?,?,?,?,?,?,?,?,?,'OUTRO','ESTORNO',?,?,?,?,?,?,?,?,?,1)").bind(reverseId,tenant,original.unit_id,original.account_id,reversalDirection,original.amount_cents,new Date().toISOString().slice(0,10),original.competency,`Estorno do lançamento #${original.id} — ${original.description}`,original.category_id,original.payment_method_id,original.person_id,original.cost_center_id,original.department_id,original.campaign_id,original.fund_id,original.id,original.privacy,original.id,`reverse:${original.id}`,ctx.session.user.id,stamp,stamp,period.id,original.quick_session_id),
      database().prepare("UPDATE finance_movements SET status='ESTORNADO',version=version+1,updated_at=? WHERE id=? AND tenant_id=? AND status='CONFIRMADO' AND version=?").bind(stamp,original.id,tenant,original.version),
      audit(ctx,"ESTORNAR","MOVIMENTO",original.id,original.unit_id,original,{reverseId,reversalDirection,reopeningNumber:period.reopen_count},reason),
    ]);
    return{id:reverseId,reversalDirection};
  }
  if(action==="SETTLE") { const installment=await owned<{id:number;obligation_id:number;amount_cents:number;status:string;movement_id:number|null}>("finance_installments",ctx,positiveId(input.installmentId)); if(installment.movement_id||installment.status!=="ABERTA") throw new ApiError(409,"PARCELA_JA_BAIXADA","Esta parcela já foi baixada."); const obligation=await owned<{id:number;unit_id:number;kind:string;description:string;category_id:number|null;cost_center_id:number|null;campaign_id:number|null;fund_id:number|null;competency:string}>("finance_obligations",ctx,installment.obligation_id); await scopedUnit(ctx,obligation.unit_id);const period=await assertOpenFinancePeriod(ctx.session,obligation.unit_id,obligation.competency); const account=await validateAccount(ctx,positiveId(input.accountId)); if(account.unit_id!==obligation.unit_id) throw new ApiError(403,"FORA_DO_ESCOPO","A conta não pertence à unidade da obrigação."); const movementId=generatedId(),direction=obligation.kind==="RECEBER"?"ENTRADA":"SAIDA",settledStatus=obligation.kind==="RECEBER"?"RECEBIDA":"PAGA",day=isoDate(input.occurredOn); await database().batch([database().prepare("INSERT INTO finance_movements(id,tenant_id,unit_id,account_id,direction,amount_cents,occurred_on,competency,description,category_id,payment_method_id,cost_center_id,campaign_id,fund_id,source,source_entity,source_entity_id,privacy,idempotency_key,created_by_user_id,created_at,period_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,'CONTA_RECEBER','PARCELA',?,'IDENTIFICADA_PRIVADA',?,?,?,?)").bind(movementId,tenant,obligation.unit_id,account.id,direction,installment.amount_cents,day,obligation.competency,obligation.description,obligation.category_id,positiveId(input.paymentMethodId,false),obligation.cost_center_id,obligation.campaign_id,obligation.fund_id,installment.id,`installment:${installment.id}`,ctx.session.user.id,stamp,period.id),database().prepare("UPDATE finance_installments SET status=?,movement_id=?,settled_at=? WHERE id=? AND tenant_id=? AND movement_id IS NULL AND status='ABERTA'").bind(settledStatus,movementId,stamp,installment.id,tenant),database().prepare("UPDATE finance_obligations SET status=CASE WHEN NOT EXISTS(SELECT 1 FROM finance_installments WHERE obligation_id=? AND tenant_id=? AND status='ABERTA' AND id<>?) THEN 'QUITADA' ELSE 'PARCIAL' END,updated_at=? WHERE id=? AND tenant_id=?").bind(obligation.id,tenant,installment.id,stamp,obligation.id,tenant),audit(ctx,"BAIXAR","PARCELA",installment.id,obligation.unit_id,installment,{movementId,status:settledStatus})]); return {id:movementId}; }
  throw new ApiError(400,"OPERACAO_INVALIDA","Operação financeira inválida.");
}

export async function saveFinanceAttachment(request:Request,form:FormData){ const ctx=await context(request,"FINANCEIRO_LANCAMENTOS_CRIAR"),movementId=positiveId(form.get("movementId")),movement=await owned<{unit_id:number}>("finance_movements",ctx,movementId);await scopedUnit(ctx,movement.unit_id);const file=form.get("file");if(!(file instanceof File)||file.size<1||file.size>5242880||!["image/jpeg","image/png","image/webp","application/pdf"].includes(file.type))throw new ApiError(400,"ANEXO_INVALIDO","Envie JPG, PNG, WebP ou PDF de até 5 MB.");const attachmentId=generatedId(),stamp=now();await database().batch([database().prepare("INSERT INTO finance_attachments(id,tenant_id,movement_id,filename,mime_type,size_bytes,content,uploaded_by_user_id,created_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(attachmentId,ctx.session.user.tenantId,movementId,clean(file.name,180)||"comprovante",file.type,file.size,await file.arrayBuffer(),ctx.session.user.id,stamp),audit(ctx,"ANEXAR","MOVIMENTO",movementId,movement.unit_id,null,{attachmentId,filename:file.name,size:file.size})]);return{id:attachmentId};}

export async function financeAttachment(request:Request,attachmentId:number){const ctx=await context(request,"FINANCEIRO_VISUALIZAR"),row=await database().prepare("SELECT a.filename,a.mime_type,a.content,m.unit_id FROM finance_attachments a JOIN finance_movements m ON m.id=a.movement_id AND m.tenant_id=a.tenant_id WHERE a.id=? AND a.tenant_id=?").bind(attachmentId,ctx.session.user.tenantId).first<{filename:string;mime_type:string;content:ArrayBuffer;unit_id:number}>();if(!row)throw new ApiError(404,"ANEXO_NAO_ENCONTRADO","Comprovante não encontrado.");await scopedUnit(ctx,row.unit_id);return new Response(row.content,{headers:{"Content-Type":row.mime_type,"Content-Disposition":`inline; filename="${row.filename.replace(/[\r\n"]/g,"")}"`,"Cache-Control":"private, no-store","X-Content-Type-Options":"nosniff"}});}

async function scopedPerson(ctx:Ctx,personId:number){const person=await database().prepare("SELECT id,tenant_id,matrix_id,branch_id,full_name FROM people WHERE id=? AND tenant_id=?").bind(personId,ctx.session.user.tenantId).first<{id:number;tenant_id:number;matrix_id:number;branch_id:number|null;full_name:string}>();if(!person||!canAccessMemberScope(ctx.session.user,{tenantId:person.tenant_id,matrixId:person.matrix_id,branchId:person.branch_id}))throw new ApiError(404,"PESSOA_NAO_ENCONTRADA","Pessoa não encontrada.");return person;}

export async function personFinance(request:Request,personId:number){const ctx=await context(request,"FINANCEIRO_CONTRIBUICOES_VISUALIZAR");await scopedPerson(ctx,personId);const [preference,contributions]=await Promise.all([database().prepare("SELECT default_privacy,updated_at FROM person_financial_preferences WHERE tenant_id=? AND person_id=?").bind(ctx.session.user.tenantId,personId).first(),database().prepare("SELECT c.id,c.contribution_type,c.privacy,m.amount_cents,m.occurred_on,m.description,ca.name campaign_name FROM finance_contributions c JOIN finance_movements m ON m.id=c.movement_id AND m.tenant_id=c.tenant_id LEFT JOIN finance_campaigns ca ON ca.id=m.campaign_id AND ca.tenant_id=m.tenant_id WHERE c.tenant_id=? AND c.person_id=? ORDER BY m.occurred_on DESC,m.id DESC LIMIT 50").bind(ctx.session.user.tenantId,personId).all()]);return{preference:preference??{default_privacy:"IDENTIFICADA",updated_at:null},contributions:contributions.results};}

export async function updatePersonFinance(request:Request,personId:number,input:Input){const ctx=await context(request,"FINANCEIRO_CONTRIBUICOES_GERENCIAR"),person=await scopedPerson(ctx,personId),privacy=clean(input.defaultPrivacy,30);if(!["IDENTIFICADA","IDENTIFICADA_PRIVADA"].includes(privacy))throw new ApiError(400,"PRIVACIDADE_INVALIDA","Escolha uma preferência de privacidade válida.");const stamp=now();await database().batch([database().prepare("INSERT INTO person_financial_preferences(tenant_id,person_id,default_privacy,updated_by_user_id,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(tenant_id,person_id) DO UPDATE SET default_privacy=excluded.default_privacy,updated_by_user_id=excluded.updated_by_user_id,updated_at=excluded.updated_at").bind(ctx.session.user.tenantId,personId,privacy,ctx.session.user.id,stamp),audit(ctx,"ALTERAR_PRIVACIDADE","PESSOA",personId,person.branch_id??person.matrix_id,null,{defaultPrivacy:privacy})]);return{defaultPrivacy:privacy};}
