import { ApiError, database } from "@/lib/server/auth";
import { generatedId, requirePermission } from "@/lib/server/admin";
import type { AdministrativeSession } from "@/lib/types";
import type { PermissionCode } from "@/lib/admin/permissions";
import { canAccessMemberScope } from "@/lib/members/policy";
import { calculateAllocation, type AllocationRule } from "@/lib/finance/policy";
import {
  DEFAULT_REPORT_BLOCKS,
  isFinanceReportType,
  normalizeReportBlocks,
  publicContributorName,
  reportBalances,
  type FinanceReportType,
} from "@/lib/finance/report-policy";

type Input=Record<string,unknown>;
type Ctx={session:AdministrativeSession;permissions:Set<PermissionCode>};
type Unit={id:number;name:string;type:"CONVENCAO"|"MATRIZ"|"FILIAL";parent_id:number|null;matrixId:number;branchId:number|null;cnpj:string|null;street:string|null;number:string|null;district:string|null;city:string|null;state:string|null;convention_id:number;convention_name:string};
type ReportModel={id:number;tenant_id:number;unit_id:number|null;name:string;description:string|null;status:string;is_default:number;current_version:number};
const now=()=>new Date().toISOString();
const clean=(value:unknown,max=500)=>typeof value==="string"?value.trim().replace(/[<>]/g,"").slice(0,max):"";
const positive=(value:unknown)=>{const n=Number(value);if(!Number.isInteger(n)||n<=0)throw new ApiError(400,"DADOS_INVALIDOS","Registro inválido.");return n;};
const competency=(value:unknown)=>{const result=clean(value,7);if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(result))throw new ApiError(400,"COMPETENCIA_INVALIDA","Informe uma competência válida.");return result;};
const json=<T>(value:unknown,fallback:T):T=>{try{return typeof value==="string"?JSON.parse(value) as T:fallback;}catch{return fallback;}};

async function context(request:Request,permission:PermissionCode):Promise<Ctx>{const {session,permissions}=await requirePermission(request,permission);return{session,permissions};}

async function scopedUnit(ctx:Ctx,unitId:number):Promise<Unit>{
  const row=await database().prepare(`SELECT u.id,u.name,u.type,u.parent_id,u.street,u.number,u.district,u.city,u.state,
    CASE WHEN u.type='FILIAL' AND u.uses_parent_cnpj=1 THEN p.cnpj ELSE u.cnpj END cnpj,
    CASE WHEN u.type IN ('CONVENCAO','MATRIZ') THEN u.id ELSE u.parent_id END matrix_id,
    CASE WHEN u.type='FILIAL' THEN u.id ELSE NULL END branch_id,
    CASE WHEN u.type='CONVENCAO' THEN u.id WHEN u.type='MATRIZ' THEN p.id ELSE gp.id END convention_id,
    CASE WHEN u.type='CONVENCAO' THEN u.name WHEN u.type='MATRIZ' THEN p.name ELSE gp.name END convention_name,
    u.status,u.archived_at
    FROM organizational_units u
    LEFT JOIN organizational_units p ON p.id=u.parent_id AND p.tenant_id=u.tenant_id
    LEFT JOIN organizational_units gp ON gp.id=p.parent_id AND gp.tenant_id=u.tenant_id
    WHERE u.id=? AND u.tenant_id=?`).bind(unitId,ctx.session.user.tenantId).first<Record<string,unknown>>();
  const matrixId=Number(row?.matrix_id||0),branchId=row?.branch_id?Number(row.branch_id):null;
  if(!row||row.status!=="ATIVO"||row.archived_at||!(row.type==="CONVENCAO"||row.type==="MATRIZ"||row.type==="FILIAL")||!matrixId)throw new ApiError(404,"UNIDADE_NAO_ENCONTRADA","Unidade financeira não encontrada.");
  if(ctx.session.activeContext?.unitId!==Number(row.id))throw new ApiError(403,"FORA_DO_ESCOPO","Selecione esta unidade no topo antes de abrir o relatório.");
  if(row.type!=="CONVENCAO"&&!canAccessMemberScope(ctx.session.user,{tenantId:ctx.session.user.tenantId,matrixId,branchId}))throw new ApiError(403,"FORA_DO_ESCOPO","Unidade fora do seu escopo.");
  return{...row,id:Number(row.id),name:String(row.name),type:row.type as Unit["type"],parent_id:row.parent_id?Number(row.parent_id):null,matrixId,branchId,cnpj:row.cnpj?String(row.cnpj):null,street:row.street?String(row.street):null,number:row.number?String(row.number):null,district:row.district?String(row.district):null,city:row.city?String(row.city):null,state:row.state?String(row.state):null,convention_id:Number(row.convention_id),convention_name:String(row.convention_name||"")} as Unit;
}

function audit(ctx:Ctx,action:string,entityType:string,entityId:number,unitId:number|null,details:unknown){return database().prepare("INSERT INTO finance_audit(tenant_id,unit_id,actor_user_id,actor_membership_id,action,entity_type,entity_id,new_values,created_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(ctx.session.user.tenantId,unitId,ctx.session.user.id,ctx.session.user.membershipId,action,entityType,entityId,JSON.stringify(details),now());}

const DEFAULT_MODEL={id:null,name:"Relatório Oficial Mensal",description:"Modelo padrão seguro do NexIgreja",version:1,title:"PRESTAÇÃO DE CONTAS FINANCEIRA",subtitle:"",logoMode:"UNIT",orientation:"PORTRAIT",margins:"NORMAL",blocks:DEFAULT_REPORT_BLOCKS,signatures:[{name:"",role:"Tesoureiro"},{name:"",role:"Pastor Presidente"}],customText:""};

function normalizeModel(input:Input){
  const orientation=input.orientation==="LANDSCAPE"?"LANDSCAPE":"PORTRAIT";
  const margins=["NORMAL","NARROW","CUSTOM"].includes(String(input.margins))?String(input.margins):"NORMAL";
  const logoMode=["INSTITUTION","UNIT","NONE"].includes(String(input.logoMode))?String(input.logoMode):"UNIT";
  const signatures=Array.isArray(input.signatures)?input.signatures.slice(0,6).map(item=>{const value=item&&typeof item==="object"?item as Input:{};return{name:clean(value.name,100),role:clean(value.role,100)}}).filter(item=>item.name||item.role):[];
  return{title:clean(input.title,120)||"RELATÓRIO FINANCEIRO",subtitle:clean(input.subtitle,180),logoMode,orientation,margins,blocks:normalizeReportBlocks(input.blocks),signatures,customText:clean(input.customText,600)};
}

async function modelSnapshot(ctx:Ctx,modelId:number|null,targetUnitId:number){
  if(!modelId)return DEFAULT_MODEL;
  const model=await database().prepare("SELECT * FROM finance_report_models WHERE id=? AND tenant_id=? AND status='ATIVO'").bind(modelId,ctx.session.user.tenantId).first<ReportModel>();
  if(!model)throw new ApiError(404,"MODELO_NAO_ENCONTRADO","Modelo de relatório não encontrado.");
  if(model.unit_id){await scopedUnit(ctx,model.unit_id);if(model.unit_id!==targetUnitId)throw new ApiError(403,"MODELO_FORA_DO_ESCOPO","O modelo não pertence à unidade selecionada.");}
  const version=await database().prepare("SELECT config_snapshot_json FROM finance_report_model_versions WHERE tenant_id=? AND model_id=? AND version=?").bind(ctx.session.user.tenantId,model.id,model.current_version).first<{config_snapshot_json:string}>();
  return{id:model.id,name:model.name,description:model.description,version:model.current_version,...json(version?.config_snapshot_json,normalizeModel({}))};
}

const movementScope=(accountId:number|null)=>accountId?" AND m.account_id=?":"";
const movementArgs=(tenantId:number,periodId:number,accountId:number|null)=>accountId?[tenantId,periodId,accountId]:[tenantId,periodId];
const openingArgs=(tenantId:number,unitId:number,start:string,accountId:number|null)=>accountId?[tenantId,unitId,accountId,tenantId,unitId,start,accountId]:[tenantId,unitId,tenantId,unitId,start];

async function reportSnapshot(ctx:Ctx,unitId:number,selectedCompetency:string,accountId:number|null,reportType:FinanceReportType){
  const selectedUnit=await scopedUnit(ctx,unitId),tenant=ctx.session.user.tenantId,start=`${selectedCompetency}-01`,endDate=new Date(`${start}T12:00:00Z`);endDate.setUTCMonth(endDate.getUTCMonth()+1);const end=endDate.toISOString().slice(0,10);
  if(accountId){const account=await database().prepare("SELECT id FROM finance_accounts WHERE id=? AND tenant_id=? AND unit_id=?").bind(accountId,tenant,unitId).first();if(!account)throw new ApiError(404,"CONTA_NAO_ENCONTRADA","Conta fora da unidade selecionada.");}
  const period=await database().prepare("SELECT * FROM finance_periods WHERE tenant_id=? AND unit_id=? AND competency=?").bind(tenant,unitId,selectedCompetency).first<Record<string,unknown>>();
  if(!period)throw new ApiError(404,"PERIODO_NAO_ENCONTRADO","Abra o caixa desta competência antes de gerar o relatório.");
  const closure=Number(period.closure_version||0)>0?await database().prepare("SELECT * FROM finance_closure_versions WHERE tenant_id=? AND period_id=? AND version=?").bind(tenant,period.id,period.closure_version).first<Record<string,unknown>>():null;
  const scope=movementScope(accountId),args=movementArgs(tenant,Number(period.id),accountId);
  const [entryGroups,expenseGroups,details,openingRow,physicalRow,linkedRow,allocationRows,transfers,campaigns,funds]=await Promise.all([
    database().prepare(`SELECT COALESCE(c.name,'Outras Entradas') name,SUM(CASE WHEN m.direction='ENTRADA' THEN m.amount_cents WHEN m.direction='ESTORNO' AND m.reversal_direction='SAIDA' THEN -m.amount_cents WHEN m.direction='AJUSTE' AND m.adjustment_direction='ENTRADA' THEN m.amount_cents ELSE 0 END) amount_cents FROM finance_movements m LEFT JOIN finance_categories c ON c.id=m.category_id AND c.tenant_id=m.tenant_id WHERE m.tenant_id=? AND m.period_id=?${scope} AND m.status IN ('CONFIRMADO','ESTORNADO') AND (m.direction='ENTRADA' OR (m.direction='ESTORNO' AND m.reversal_direction='SAIDA') OR (m.direction='AJUSTE' AND m.adjustment_direction='ENTRADA')) GROUP BY COALESCE(c.name,'Outras Entradas') HAVING amount_cents<>0 ORDER BY name`).bind(...args).all(),
    database().prepare(`SELECT COALESCE(c.name,'Outras Saídas') name,SUM(CASE WHEN m.direction='SAIDA' THEN m.amount_cents WHEN m.direction='ESTORNO' AND m.reversal_direction='ENTRADA' THEN -m.amount_cents WHEN m.direction='AJUSTE' AND m.adjustment_direction='SAIDA' THEN m.amount_cents ELSE 0 END) amount_cents FROM finance_movements m LEFT JOIN finance_categories c ON c.id=m.category_id AND c.tenant_id=m.tenant_id WHERE m.tenant_id=? AND m.period_id=?${scope} AND m.status IN ('CONFIRMADO','ESTORNADO') AND (m.direction='SAIDA' OR (m.direction='ESTORNO' AND m.reversal_direction='ENTRADA') OR (m.direction='AJUSTE' AND m.adjustment_direction='SAIDA')) GROUP BY COALESCE(c.name,'Outras Saídas') HAVING amount_cents<>0 ORDER BY name`).bind(...args).all(),
    database().prepare(`SELECT m.id,m.occurred_on,m.description,m.direction,m.reversal_direction,m.adjustment_direction,m.amount_cents,m.privacy,a.name account_name,COALESCE(c.name,'Sem categoria') category_name,fc.contribution_type,p.full_name person_name,cc.name campaign_name FROM finance_movements m JOIN finance_accounts a ON a.id=m.account_id AND a.tenant_id=m.tenant_id LEFT JOIN finance_categories c ON c.id=m.category_id AND c.tenant_id=m.tenant_id LEFT JOIN finance_contributions fc ON fc.movement_id=m.id AND fc.tenant_id=m.tenant_id LEFT JOIN people p ON p.id=m.person_id AND p.tenant_id=m.tenant_id LEFT JOIN finance_campaigns cc ON cc.id=m.campaign_id AND cc.tenant_id=m.tenant_id WHERE m.tenant_id=? AND m.period_id=?${scope} AND m.status IN ('CONFIRMADO','ESTORNADO') ORDER BY m.occurred_on,m.id LIMIT 250`).bind(...args).all<Record<string,unknown>>(),
    database().prepare(`SELECT COALESCE((SELECT SUM(initial_balance_cents) FROM finance_accounts WHERE tenant_id=? AND unit_id=?${accountId?" AND id=?":""}),0)+COALESCE((SELECT SUM(CASE WHEN direction IN ('ENTRADA','TRANSFERENCIA_ENTRADA') OR (direction='AJUSTE' AND adjustment_direction='ENTRADA') OR (direction='ESTORNO' AND reversal_direction='ENTRADA') THEN amount_cents WHEN direction IN ('SAIDA','TRANSFERENCIA_SAIDA') OR (direction='AJUSTE' AND adjustment_direction='SAIDA') OR (direction='ESTORNO' AND reversal_direction='SAIDA') THEN -amount_cents ELSE 0 END) FROM finance_movements m WHERE tenant_id=? AND unit_id=? AND occurred_on<?${accountId?" AND account_id=?":""} AND status IN ('CONFIRMADO','ESTORNADO')),0) amount_cents`).bind(...openingArgs(tenant,unitId,start,accountId)).first<{amount_cents:number}>(),
    database().prepare(`SELECT COALESCE(SUM(CASE WHEN direction IN ('ENTRADA','TRANSFERENCIA_ENTRADA') OR (direction='AJUSTE' AND adjustment_direction='ENTRADA') OR (direction='ESTORNO' AND reversal_direction='ENTRADA') THEN amount_cents WHEN direction IN ('SAIDA','TRANSFERENCIA_SAIDA') OR (direction='AJUSTE' AND adjustment_direction='SAIDA') OR (direction='ESTORNO' AND reversal_direction='SAIDA') THEN -amount_cents ELSE 0 END),0) amount_cents FROM finance_movements m WHERE tenant_id=? AND period_id=?${scope} AND status IN ('CONFIRMADO','ESTORNADO')`).bind(...args).first<{amount_cents:number}>(),
    database().prepare(`SELECT COALESCE(SUM(CASE WHEN m.direction='ENTRADA' OR (m.direction='AJUSTE' AND m.adjustment_direction='ENTRADA') OR (m.direction='ESTORNO' AND m.reversal_direction='ENTRADA') THEN m.amount_cents WHEN m.direction='SAIDA' OR (m.direction='AJUSTE' AND m.adjustment_direction='SAIDA') OR (m.direction='ESTORNO' AND m.reversal_direction='SAIDA') THEN -m.amount_cents ELSE 0 END),0) amount_cents FROM finance_movements m LEFT JOIN finance_funds f ON f.id=m.fund_id AND f.tenant_id=m.tenant_id WHERE m.tenant_id=? AND m.unit_id=? AND m.occurred_on<? AND (m.campaign_id IS NOT NULL OR COALESCE(f.restricted,0)=1) AND m.status IN ('CONFIRMADO','ESTORNADO')`).bind(tenant,unitId,end).first<{amount_cents:number}>(),
    closure?database().prepare("SELECT * FROM finance_period_allocation_results WHERE tenant_id=? AND period_id=? AND closure_version=? ORDER BY display_order").bind(tenant,period.id,period.closure_version).all<Record<string,unknown>>():database().prepare("SELECT * FROM finance_period_allocation_rules WHERE tenant_id=? AND period_id=? ORDER BY display_order").bind(tenant,period.id).all<Record<string,unknown>>(),
    database().prepare("SELECT t.id,t.occurred_on,t.amount_cents,oa.name origin_name,da.name destination_name FROM finance_transfers t JOIN finance_accounts oa ON oa.id=t.origin_account_id AND oa.tenant_id=t.tenant_id JOIN finance_accounts da ON da.id=t.destination_account_id AND da.tenant_id=t.tenant_id WHERE t.tenant_id=? AND t.unit_id=? AND t.occurred_on>=? AND t.occurred_on<? ORDER BY t.occurred_on,t.id").bind(tenant,unitId,start,end).all(),
    database().prepare("SELECT c.id,c.name,c.target_cents,COALESCE(SUM(CASE WHEN m.direction='ENTRADA' THEN m.amount_cents ELSE 0 END),0) received_cents,COALESCE(SUM(CASE WHEN m.direction='SAIDA' THEN m.amount_cents ELSE 0 END),0) spent_cents,COALESCE(SUM(CASE WHEN m.direction='ENTRADA' THEN m.amount_cents WHEN m.direction='SAIDA' THEN -m.amount_cents ELSE 0 END),0) balance_cents,(SELECT COALESCE(SUM(p.total_cents),0) FROM finance_campaign_pledges p WHERE p.tenant_id=c.tenant_id AND p.campaign_id=c.id AND p.status='ATIVO') pledged_cents FROM finance_campaigns c LEFT JOIN finance_movements m ON m.campaign_id=c.id AND m.tenant_id=c.tenant_id AND m.status IN ('CONFIRMADO','ESTORNADO') WHERE c.tenant_id=? AND c.unit_id=? GROUP BY c.id ORDER BY c.name").bind(tenant,unitId).all(),
    database().prepare("SELECT f.id,f.name,f.restricted,COALESCE(SUM(CASE WHEN m.direction='ENTRADA' THEN m.amount_cents ELSE 0 END),0) received_cents,COALESCE(SUM(CASE WHEN m.direction='SAIDA' THEN m.amount_cents ELSE 0 END),0) spent_cents,COALESCE(SUM(CASE WHEN m.direction='ENTRADA' THEN m.amount_cents WHEN m.direction='SAIDA' THEN -m.amount_cents ELSE 0 END),0) balance_cents FROM finance_funds f LEFT JOIN finance_movements m ON m.fund_id=f.id AND m.tenant_id=f.tenant_id AND m.status IN ('CONFIRMADO','ESTORNADO') WHERE f.tenant_id=? AND f.unit_id=? GROUP BY f.id ORDER BY f.name").bind(tenant,unitId).all(),
  ]);
  const entries=entryGroups.results as Array<Record<string,unknown>>,expenses=expenseGroups.results as Array<Record<string,unknown>>;
  const totalEntriesCents=entries.reduce((sum,row)=>sum+Number(row.amount_cents||0),0),totalExpensesCents=expenses.reduce((sum,row)=>sum+Number(row.amount_cents||0),0);
  let eligibleBaseCents=Number(closure?.eligible_base_cents??0),excludedResourcesCents=Number(closure?.excluded_resources_cents??0),allocations:Array<Record<string,unknown>>=[],allocationError:string|null=null;
  if(closure){
    const closureRules=json<Array<Record<string,unknown>>>(closure.rules_snapshot_json,[]),ruleByOrder=new Map(closureRules.map((rule,index)=>[Number(rule.display_order||index+1),rule]));
    if(eligibleBaseCents===0&&totalEntriesCents>0){
      const categoryIds=json<Array<number>>(closureRules[0]?.participating_category_ids_json,[]);
      if(categoryIds.length){const eligible=await database().prepare(`SELECT COALESCE(SUM(CASE WHEN m.direction='ENTRADA' THEN m.amount_cents WHEN m.direction='ESTORNO' AND m.reversal_direction='SAIDA' THEN -m.amount_cents ELSE 0 END),0) value FROM finance_movements m LEFT JOIN finance_funds f ON f.id=m.fund_id AND f.tenant_id=m.tenant_id WHERE m.tenant_id=? AND m.period_id=?${scope} AND m.category_id IN (${categoryIds.map(()=>"?").join(",")}) AND m.campaign_id IS NULL AND (m.fund_id IS NULL OR COALESCE(f.restricted,0)=0) AND m.status IN ('CONFIRMADO','ESTORNADO')`).bind(...args,...categoryIds).first<{value:number}>();eligibleBaseCents=Number(eligible?.value||0);}
    }
    excludedResourcesCents=Number(closure.excluded_resources_cents||Math.max(0,totalEntriesCents-eligibleBaseCents));
    let stored=allocationRows.results as Array<Record<string,unknown>>;
    if(!stored.length)stored=json<Array<Record<string,unknown>>>(closure.allocation_results_json,[]);
    if(!stored.length&&closureRules.length){try{const calculated=calculateAllocation(eligibleBaseCents,closureRules as AllocationRule[]);stored=calculated.results.map((result,index)=>({...ruleByOrder.get(result.displayOrder),recipient_name:result.recipientName,rule_type:result.ruleType,financial_destination:result.financialDestination,calculated_amount_cents:result.calculatedAmountCents,transferred_amount_cents:0,remaining_transfer_cents:result.financialDestination==="REPASSAR"?result.calculatedAmountCents:0,display_order:result.displayOrder,index}));}catch{allocationError="O snapshot histórico do rateio está inválido e precisa de revisão administrativa.";}}
    allocations=stored.map((row,index)=>{const rule=ruleByOrder.get(Number(row.display_order||row.displayOrder||index+1)),financialDestination=String(row.financial_destination||row.financialDestination||rule?.financial_destination||"REPASSAR"),calculated=Number(row.calculated_amount_cents??row.calculatedAmountCents??0),transferred=financialDestination==="REPASSAR"?Number(row.transferred_amount_cents??row.transferredAmountCents??0):0;return{...rule,...row,recipient_name:String(row.recipient_name||row.recipientName||rule?.recipient_name||"Destinatário"),rule_type:String(row.rule_type||row.ruleType||rule?.rule_type||"PERCENTUAL"),financial_destination:financialDestination,percentage_basis_points:Number(row.percentage_basis_points??rule?.percentage_basis_points??0)||null,fixed_amount_cents:Number(row.fixed_amount_cents??rule?.fixed_amount_cents??0)||null,calculated_amount_cents:calculated,transferred_amount_cents:transferred,remaining_transfer_cents:financialDestination==="REPASSAR"?Number(row.remaining_transfer_cents??row.remainingTransferCents??Math.max(0,calculated-transferred)):0,display_order:Number(row.display_order||row.displayOrder||index+1)};});
    if(!allocations.length&&!allocationError)allocationError="Nenhuma regra de rateio foi vinculada a este fechamento.";
  }else{
    const rules=allocationRows.results as Array<Record<string,unknown>>;
    const categoryIds=json<Array<number>>(rules[0]?.participating_category_ids_json,[]);
    const eligible=await database().prepare(`SELECT COALESCE(SUM(CASE WHEN m.direction='ENTRADA' THEN m.amount_cents WHEN m.direction='ESTORNO' AND m.reversal_direction='SAIDA' THEN -m.amount_cents ELSE 0 END),0) value FROM finance_movements m LEFT JOIN finance_funds f ON f.id=m.fund_id AND f.tenant_id=m.tenant_id WHERE m.tenant_id=? AND m.period_id=?${scope} AND m.category_id IN (${categoryIds.length?categoryIds.map(()=>"?").join(","):"NULL"}) AND m.campaign_id IS NULL AND (m.fund_id IS NULL OR COALESCE(f.restricted,0)=0) AND m.status IN ('CONFIRMADO','ESTORNADO')`).bind(...args,...categoryIds).first<{value:number}>();
    eligibleBaseCents=Number(eligible?.value||0);excludedResourcesCents=Math.max(0,totalEntriesCents-eligibleBaseCents);
    try{const calculated=calculateAllocation(eligibleBaseCents,rules as AllocationRule[]);allocations=calculated.results.map((result,index)=>({...rules[index],recipient_name:result.recipientName,rule_type:result.ruleType,financial_destination:result.financialDestination,calculated_amount_cents:result.calculatedAmountCents,transferred_amount_cents:0,remaining_transfer_cents:result.financialDestination==="REPASSAR"?result.calculatedAmountCents:0,display_order:result.displayOrder}));}catch{allocationError=rules.length?"A regra de rateio vinculada ao período é inválida e precisa de revisão administrativa.":"Nenhuma regra de rateio foi vinculada a este período.";}
  }
  const snapshotRules=closure?json<Array<Record<string,unknown>>>(closure.rules_snapshot_json,[]):allocationRows.results as Array<Record<string,unknown>>,participatingCategoryIds=json<Array<number>>(snapshotRules[0]?.participating_category_ids_json,[]);
  const outsideEntries=await database().prepare(`SELECT COALESCE(cc.name,f.name,c.name,'Outras entradas') name,SUM(CASE WHEN m.direction='ENTRADA' THEN m.amount_cents WHEN m.direction='ESTORNO' AND m.reversal_direction='SAIDA' THEN -m.amount_cents ELSE 0 END) amount_cents FROM finance_movements m LEFT JOIN finance_categories c ON c.id=m.category_id AND c.tenant_id=m.tenant_id LEFT JOIN finance_campaigns cc ON cc.id=m.campaign_id AND cc.tenant_id=m.tenant_id LEFT JOIN finance_funds f ON f.id=m.fund_id AND f.tenant_id=m.tenant_id WHERE m.tenant_id=? AND m.period_id=?${scope} AND m.status IN ('CONFIRMADO','ESTORNADO') AND (m.direction='ENTRADA' OR (m.direction='ESTORNO' AND m.reversal_direction='SAIDA')) AND (m.campaign_id IS NOT NULL OR COALESCE(f.restricted,0)=1 OR m.category_id NOT IN (${participatingCategoryIds.length?participatingCategoryIds.map(()=>"?").join(","):"NULL"})) GROUP BY COALESCE(cc.name,f.name,c.name,'Outras entradas') HAVING amount_cents<>0 ORDER BY name`).bind(...args,...participatingCategoryIds).all();
  const allocatedCents=allocations.reduce((sum,row)=>sum+Number(row.calculated_amount_cents||0),0),ownUnitAllocationCents=allocations.filter(row=>row.financial_destination==="MANTER_NA_UNIDADE").reduce((sum,row)=>sum+Number(row.calculated_amount_cents||0),0),calculatedTransferCents=allocations.filter(row=>row.financial_destination!=="MANTER_NA_UNIDADE").reduce((sum,row)=>sum+Number(row.calculated_amount_cents||0),0),transferredCents=allocations.filter(row=>row.financial_destination!=="MANTER_NA_UNIDADE").reduce((sum,row)=>sum+Number(row.transferred_amount_cents||0),0),openingCents=Number(openingRow?.amount_cents||0),physicalCurrentCents=openingCents+Number(physicalRow?.amount_cents||0),linkedCents=Math.max(0,Number(linkedRow?.amount_cents||0));
  const balances={openingCents,linkedCents,...reportBalances({openingCents,entriesCents:totalEntriesCents,expensesCents:totalExpensesCents,linkedCents,calculatedTransferCents,transferredAllocationCents:transferredCents}),currentCents:physicalCurrentCents};balances.freeCents=physicalCurrentCents-linkedCents-balances.remainingTransferCents;
  const safeDetails=(details.results as Array<Record<string,unknown>>).map(row=>({...row,person_name:publicContributorName(String(row.privacy||""),row.person_name?String(row.person_name):null)}));
  return{reportType,period:{id:Number(period.id),status:String(period.status),lifecycleState:String(period.lifecycle_state),competency:selectedCompetency,closureVersion:Number(period.closure_version||0),closureId:closure?Number(closure.id):null},unit:{...selectedUnit,address:[selectedUnit.street,selectedUnit.number,selectedUnit.district,selectedUnit.city,selectedUnit.state].filter(Boolean).join(", "),logoUrl:`/api/media/units/${unitId}/logo`},accountId,generatedBy:ctx.session.user.name,generatedAt:now(),entries,expenses,outsideEntries:outsideEntries.results,totalEntriesCents,totalExpensesCents,excludedResourcesCents,eligibleBaseCents,allocations,allocationError,allocatedCents,ownUnitAllocationCents,calculatedTransferCents,transferredCents,pendingTransferCents:balances.remainingTransferCents,balances,details:safeDetails,transfers:transfers.results,campaigns:campaigns.results,funds:funds.results};
}

export async function financeReportsWorkspace(request:Request,query:Record<string,string>){
  const ctx=await context(request,"FINANCEIRO_RELATORIOS_VISUALIZAR"),tenant=ctx.session.user.tenantId;
  if(query.reportId){const report=await database().prepare("SELECT r.*,u.name unit_name,a.name generated_by_name FROM finance_reports r JOIN organizational_units u ON u.id=r.unit_id AND u.tenant_id=r.tenant_id JOIN auth_users a ON a.id=r.generated_by_user_id WHERE r.id=? AND r.tenant_id=?").bind(positive(query.reportId),tenant).first<Record<string,unknown>>();if(!report)throw new ApiError(404,"RELATORIO_NAO_ENCONTRADO","Relatório não encontrado.");await scopedUnit(ctx,Number(report.unit_id));await database().batch([audit(ctx,"CONSULTAR_RELATORIO","RELATORIO",Number(report.id),Number(report.unit_id),{version:report.version})]);return{savedReport:{...report,snapshot:json(report.report_snapshot_json,{})}};}
  const unitId=positive(query.unitId),selectedCompetency=competency(query.competency),accountId=query.accountId?positive(query.accountId):null,reportType=isFinanceReportType(query.reportType)?query.reportType:"OFICIAL_CAIXA";
  await scopedUnit(ctx,unitId);
  const [preview,models,history,accounts]=await Promise.all([
    reportSnapshot(ctx,unitId,selectedCompetency,accountId,reportType),
    database().prepare("SELECT m.*,v.config_snapshot_json FROM finance_report_models m JOIN finance_report_model_versions v ON v.model_id=m.id AND v.tenant_id=m.tenant_id AND v.version=m.current_version WHERE m.tenant_id=? AND m.status='ATIVO' AND (m.unit_id IS NULL OR m.unit_id=?) ORDER BY m.is_default DESC,m.name LIMIT 100").bind(tenant,unitId).all<Record<string,unknown>>(),
    database().prepare("SELECT r.id,r.report_type,r.version,r.status,r.closure_version,r.model_version,r.generated_at,u.name unit_name,p.competency,a.name generated_by_name,COALESCE(m.name,'Relatório Oficial Mensal') model_name FROM finance_reports r JOIN organizational_units u ON u.id=r.unit_id AND u.tenant_id=r.tenant_id JOIN finance_periods p ON p.id=r.period_id AND p.tenant_id=r.tenant_id JOIN auth_users a ON a.id=r.generated_by_user_id LEFT JOIN finance_report_models m ON m.id=r.model_id AND m.tenant_id=r.tenant_id WHERE r.tenant_id=? AND r.unit_id=? ORDER BY r.generated_at DESC LIMIT 100").bind(tenant,unitId).all(),
    database().prepare("SELECT id,name,status FROM finance_accounts WHERE tenant_id=? AND unit_id=? ORDER BY status,name").bind(tenant,unitId).all(),
  ]);
  return{preview,defaultModel:DEFAULT_MODEL,models:models.results.map(row=>({...row,config:json(row.config_snapshot_json,{})})),history:history.results,accounts:accounts.results,permissions:{canGenerate:ctx.permissions.has("FINANCEIRO_RELATORIOS_GERAR"),canPrint:ctx.permissions.has("FINANCEIRO_RELATORIOS_IMPRIMIR"),canExport:ctx.permissions.has("FINANCEIRO_RELATORIOS_EXPORTAR"),canViewModels:ctx.permissions.has("FINANCEIRO_RELATORIOS_MODELOS_VISUALIZAR"),canConfigureModels:ctx.permissions.has("FINANCEIRO_RELATORIOS_MODELOS_CONFIGURAR")}};
}

export async function financeReportOperation(request:Request,input:Input){
  const action=clean(input.action,30).toUpperCase();
  if(action==="SAVE_MODEL"){
    const ctx=await context(request,"FINANCEIRO_RELATORIOS_MODELOS_CONFIGURAR"),tenant=ctx.session.user.tenantId,id=input.modelId?positive(input.modelId):generatedId(),unitId=input.unitId?positive(input.unitId):null,name=clean(input.name,120),description=clean(input.description,300)||null,config=normalizeModel(input),stamp=now();if(!name)throw new ApiError(400,"MODELO_INVALIDO","Informe o nome do modelo.");if(unitId)await scopedUnit(ctx,unitId);if(!unitId&&ctx.session.user.scope!=="CONVENCAO")throw new ApiError(403,"ESCOPO_MODELO_INVALIDO","Modelos gerais exigem escopo da Convenção.");
    const current=input.modelId?await database().prepare("SELECT * FROM finance_report_models WHERE id=? AND tenant_id=?").bind(id,tenant).first<ReportModel>():null;if(input.modelId&&!current)throw new ApiError(404,"MODELO_NAO_ENCONTRADO","Modelo não encontrado.");if(current?.unit_id)await scopedUnit(ctx,current.unit_id);if(current&&!current.unit_id&&ctx.session.user.scope!=="CONVENCAO")throw new ApiError(403,"ESCOPO_MODELO_INVALIDO","Somente a Convenção pode alterar um modelo geral.");const version=(current?.current_version||0)+1,isDefault=input.isDefault===true?1:0,statements=[];if(isDefault)statements.push(database().prepare("UPDATE finance_report_models SET is_default=0 WHERE tenant_id=? AND COALESCE(unit_id,0)=COALESCE(?,0)").bind(tenant,unitId));if(current)statements.push(database().prepare("UPDATE finance_report_models SET unit_id=?,name=?,description=?,status='ATIVO',is_default=?,current_version=?,updated_by_user_id=?,updated_at=? WHERE id=? AND tenant_id=? AND current_version=?").bind(unitId,name,description,isDefault,version,ctx.session.user.id,stamp,id,tenant,current.current_version));else statements.push(database().prepare("INSERT INTO finance_report_models(id,tenant_id,unit_id,name,description,status,is_default,current_version,created_by_user_id,updated_by_user_id,created_at,updated_at) VALUES(?,?,?,?,?,'ATIVO',?,1,?,?,?,?)").bind(id,tenant,unitId,name,description,isDefault,ctx.session.user.id,ctx.session.user.id,stamp,stamp));statements.push(database().prepare("INSERT INTO finance_report_model_versions(id,tenant_id,model_id,version,config_snapshot_json,created_by_user_id,created_at) VALUES(?,?,?,?,?,?,?)").bind(generatedId(),tenant,id,version,JSON.stringify(config),ctx.session.user.id,stamp),audit(ctx,current?"ALTERAR_MODELO_RELATORIO":"CRIAR_MODELO_RELATORIO","MODELO_RELATORIO",id,unitId,{version,name,config}));await database().batch(statements);return{id,version};
  }
  if(action==="ARCHIVE_MODEL"){const ctx=await context(request,"FINANCEIRO_RELATORIOS_MODELOS_CONFIGURAR"),id=positive(input.modelId),model=await database().prepare("SELECT * FROM finance_report_models WHERE id=? AND tenant_id=?").bind(id,ctx.session.user.tenantId).first<ReportModel>();if(!model)throw new ApiError(404,"MODELO_NAO_ENCONTRADO","Modelo não encontrado.");if(model.unit_id)await scopedUnit(ctx,model.unit_id);await database().batch([database().prepare("UPDATE finance_report_models SET status='ARQUIVADO',is_default=0,updated_by_user_id=?,updated_at=? WHERE id=? AND tenant_id=?").bind(ctx.session.user.id,now(),id,ctx.session.user.tenantId),audit(ctx,"ARQUIVAR_MODELO_RELATORIO","MODELO_RELATORIO",id,model.unit_id,{status:"ARQUIVADO"})]);return{id,status:"ARQUIVADO"};}
  if(action==="AUDIT_OUTPUT"){const kind=clean(input.kind,20).toUpperCase(),permission:PermissionCode=kind==="IMPRIMIR"?"FINANCEIRO_RELATORIOS_IMPRIMIR":kind==="PDF"?"FINANCEIRO_RELATORIOS_GERAR":"FINANCEIRO_RELATORIOS_EXPORTAR",ctx=await context(request,permission),unitId=positive(input.unitId);await scopedUnit(ctx,unitId);await database().batch([audit(ctx,kind==="IMPRIMIR"?"IMPRIMIR_RELATORIO":kind==="PDF"?"GERAR_PDF_RELATORIO":"EXPORTAR_RELATORIO","RELATORIO",Number(input.reportId||0),unitId,{kind,competency:input.competency,reportType:input.reportType})]);return{ok:true};}
  if(action!=="GENERATE")throw new ApiError(400,"OPERACAO_INVALIDA","Operação de relatório inválida.");
  const ctx=await context(request,"FINANCEIRO_RELATORIOS_GERAR"),unitId=positive(input.unitId),selectedCompetency=competency(input.competency),reportType=isFinanceReportType(input.reportType)?input.reportType:"OFICIAL_CAIXA",accountId=input.accountId?positive(input.accountId):null,model=await modelSnapshot(ctx,input.modelId?positive(input.modelId):null,unitId),snapshot=await reportSnapshot(ctx,unitId,selectedCompetency,accountId,reportType),tenant=ctx.session.user.tenantId,period=snapshot.period,status=period.status==="FECHADO"?"OFICIAL":"PRELIMINAR",next=await database().prepare("SELECT COALESCE(MAX(version),0)+1 next_version FROM finance_reports WHERE tenant_id=? AND period_id=? AND report_type=?").bind(tenant,period.id,reportType).first<{next_version:number}>(),version=Number(next?.next_version||1),id=generatedId(),stamp=now(),statements=[];
  if(status==="OFICIAL")statements.push(database().prepare("UPDATE finance_reports SET status='SUBSTITUIDO_POR_NOVA_VERSAO' WHERE tenant_id=? AND period_id=? AND report_type=? AND status='OFICIAL' AND COALESCE(closure_version,0)<?").bind(tenant,period.id,reportType,period.closureVersion));
  statements.push(database().prepare("INSERT INTO finance_reports(id,tenant_id,unit_id,period_id,closure_id,closure_version,report_type,version,status,model_id,model_version,model_snapshot_json,report_snapshot_json,generated_by_user_id,generated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,tenant,unitId,period.id,period.closureId,period.closureVersion||null,reportType,version,status,model.id,model.version,JSON.stringify(model),JSON.stringify(snapshot),ctx.session.user.id,stamp),audit(ctx,status==="OFICIAL"?"GERAR_RELATORIO_OFICIAL":"GERAR_RELATORIO_PRELIMINAR","RELATORIO",id,unitId,{periodId:period.id,closureVersion:period.closureVersion,reportType,version,modelId:model.id,modelVersion:model.version}));await database().batch(statements);return{id,version,status,snapshot,model,filename:`relatorio-${reportType.toLowerCase().replaceAll("_","-")}-${snapshot.unit.name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}-${selectedCompetency.slice(5)}-${selectedCompetency.slice(0,4)}-v${version}.pdf`};
}
