import { generatedId } from "@/lib/server/admin";
import { ApiError,database,me,platformOwnerSession } from "@/lib/server/auth";
import { isSafeNotificationRoute } from "@/lib/notifications/policy";
import type { NotificationAudience,NotificationPage,NotificationPriority,NotificationRecord,NotificationType } from "@/lib/notifications/types";

type NotificationRow={id:number;tenant_id:number|null;audience:NotificationAudience;type:NotificationType;title:string;message:string;priority:NotificationPriority;internal_route:string|null;source_entity:string|null;source_entity_id:number|null;unit_id:number|null;group_key:string|null;read_at:string|null;created_at:string};
const now=()=>new Date().toISOString();
const clean=(value:unknown,max:number)=>typeof value==="string"?value.trim().replace(/[<>]/g,"").slice(0,max):"";
function map(row:NotificationRow,tenantName:string|null):NotificationRecord{return{id:row.id,type:row.type,title:row.title,message:row.message,priority:row.priority,internalRoute:isSafeNotificationRoute(row.internal_route)?row.internal_route:null,sourceEntity:row.source_entity,sourceEntityId:row.source_entity_id,unitId:row.unit_id,groupKey:row.group_key,readAt:row.read_at,createdAt:row.created_at,audience:row.audience,contextLabel:row.audience==="PLATFORM"?"Plataforma NexIgreja":tenantName??"Instituição"};}
async function context(request:Request){const session=await me(request);return{userId:session.user.id,tenantId:session.activeTenant?.id??null,tenantName:session.activeTenant?.name??null,isPlatformOwner:session.user.isPlatformOwner,platformTenantContextActive:session.user.platformTenantContextActive};}
function visibilitySql(ctx:Awaited<ReturnType<typeof context>>){if(ctx.isPlatformOwner&&ctx.platformTenantContextActive)return{sql:"(n.tenant_id=? OR n.audience='PLATFORM')",args:[ctx.tenantId]};if(ctx.isPlatformOwner)return{sql:"n.audience='PLATFORM' AND n.tenant_id IS NULL",args:[]};return{sql:"((n.tenant_id=? AND n.audience='ORGANIZATIONAL') OR n.audience='PLATFORM')",args:[ctx.tenantId]};}
export async function unreadNotificationCount(request:Request){const ctx=await context(request),visible=visibilitySql(ctx);const row=await database().prepare(`SELECT COUNT(*) total FROM notification_recipients r JOIN notifications n ON n.id=r.notification_id WHERE r.user_id=? AND r.read_at IS NULL AND r.archived_at IS NULL AND ${visible.sql}`).bind(ctx.userId,...visible.args).first<{total:number}>();return Number(row?.total??0);}
export async function listNotifications(request:Request,query:Record<string,unknown>):Promise<NotificationPage>{const ctx=await context(request),visible=visibilitySql(ctx),status=query.status==="unread"?"unread":query.status==="read"?"read":"all",page=Math.max(1,Number(query.page)||1),pageSize=Math.min(50,Math.max(5,Number(query.pageSize)||12)),where=["r.user_id=?","r.archived_at IS NULL",visible.sql],args:unknown[]=[ctx.userId,...visible.args];if(status==="unread")where.push("r.read_at IS NULL");if(status==="read")where.push("r.read_at IS NOT NULL");const total=Number((await database().prepare(`SELECT COUNT(*) total FROM notification_recipients r JOIN notifications n ON n.id=r.notification_id WHERE ${where.join(" AND ")}`).bind(...args).first<{total:number}>())?.total??0),unread=await unreadNotificationCount(request);const result=await database().prepare(`SELECT n.*,r.read_at FROM notification_recipients r JOIN notifications n ON n.id=r.notification_id WHERE ${where.join(" AND ")} ORDER BY n.created_at DESC,n.id DESC LIMIT ? OFFSET ?`).bind(...args,pageSize,(page-1)*pageSize).all<NotificationRow>();return{items:result.results.map(row=>map(row,ctx.tenantName)),page,pageSize,total,totalPages:Math.max(1,Math.ceil(total/pageSize)),unread};}
async function assertRecipient(request:Request,id:number){const ctx=await context(request),visible=visibilitySql(ctx),row=await database().prepare(`SELECT n.id,n.internal_route FROM notification_recipients r JOIN notifications n ON n.id=r.notification_id WHERE n.id=? AND r.user_id=? AND r.archived_at IS NULL AND ${visible.sql}`).bind(id,ctx.userId,...visible.args).first<{id:number;internal_route:string|null}>();if(!row)throw new ApiError(404,"NOTIFICACAO_NAO_ENCONTRADA","Notificação não encontrada.");return{ctx,row};}
export async function markNotificationRead(request:Request,id:number){const {ctx,row}=await assertRecipient(request,id);await database().prepare("UPDATE notification_recipients SET read_at=COALESCE(read_at,?) WHERE notification_id=? AND user_id=?").bind(now(),id,ctx.userId).run();return{route:isSafeNotificationRoute(row.internal_route)?row.internal_route:null};}
export async function markAllNotificationsRead(request:Request){const ctx=await context(request),visible=visibilitySql(ctx),time=now();await database().prepare(`UPDATE notification_recipients SET read_at=? WHERE user_id=? AND read_at IS NULL AND archived_at IS NULL AND notification_id IN (SELECT id FROM notifications n WHERE ${visible.sql})`).bind(time,ctx.userId,...visible.args).run();return{readAt:time};}
export async function preRegistrationNotificationStatements(input:{tenantId:number;conventionId:number|null;matrixId:number|null;branchId:number|null;preRegistrationId:number;fullName:string;createdAt:string}):Promise<D1PreparedStatement[]>{const recipients=await database().prepare(`SELECT DISTINCT m.user_id FROM tenant_memberships m JOIN auth_users u ON u.id=m.user_id WHERE m.tenant_id=? AND m.status='ATIVO' AND m.archived_at IS NULL AND u.status='ATIVO' AND u.archived_at IS NULL AND EXISTS(SELECT 1 FROM membership_permissions p WHERE p.membership_id=m.id AND p.permission='PRECADASTROS_VISUALIZAR') AND EXISTS(SELECT 1 FROM membership_permissions p WHERE p.membership_id=m.id AND p.permission='PRECADASTROS_ANALISAR') AND ((? IS NULL AND m.scope='CONVENCAO') OR (? IS NOT NULL AND m.scope='CONVENCAO' AND m.scope_unit_id=?) OR (? IS NOT NULL AND m.scope='MATRIZ' AND m.scope_unit_id=?) OR (? IS NOT NULL AND m.scope='FILIAL' AND m.scope_unit_id=?))`).bind(input.tenantId,input.conventionId,input.conventionId,input.conventionId,input.matrixId,input.matrixId,input.branchId,input.branchId).all<{user_id:number}>();if(!recipients.results.length)return[];const id=generatedId(),unitId=input.branchId??input.matrixId??input.conventionId,title="Novo pré-cadastro recebido",message=`${clean(input.fullName,180)} enviou uma ficha de cadastro.`;return[database().prepare("INSERT INTO notifications(id,tenant_id,audience,type,title,message,priority,internal_route,source_entity,source_entity_id,unit_id,group_key,metadata_json,mandatory,created_at,updated_at) VALUES(?,?,'ORGANIZATIONAL','MEMBRO_PRECADASTRO_RECEBIDO',?,?,'ATENCAO',?,'MEMBRO_PRECADASTRO',?,?, 'MEMBROS_PRECADASTROS_PENDENTES',?,0,?,?)").bind(id,input.tenantId,title,message,`/painel/membros/pre-cadastros?abrir=${input.preRegistrationId}`,input.preRegistrationId,unitId,JSON.stringify({preRegistrationId:input.preRegistrationId}),input.createdAt,input.createdAt),...recipients.results.map(recipient=>database().prepare("INSERT INTO notification_recipients(notification_id,user_id,created_at) VALUES(?,?,?)").bind(id,recipient.user_id,input.createdAt))];}
export async function dispatchSystemNotification(request:Request,input:Record<string,unknown>){const owner=await platformOwnerSession(request);if(!owner.user.isPlatformOwner)throw new ApiError(403,"PERMISSAO_NEGADA","Somente o proprietário da plataforma pode enviar notificações do sistema.");if(owner.user.mustChangePassword)throw new ApiError(403,"TROCA_SENHA_OBRIGATORIA","Troque a senha temporária antes de enviar notificações.");const title=clean(input.title,160),message=clean(input.message,500),route=clean(input.route,240)||null;if(!title||!message)throw new ApiError(400,"DADOS_INVALIDOS","Informe título e mensagem.");if(!isSafeNotificationRoute(route))throw new ApiError(400,"ROTA_INVALIDA","Use somente uma rota interna segura.");const audience=input.audience==="PLATFORM_OWNER"?"PLATFORM_OWNER":input.audience==="ADMINISTRADORES"?"ADMINISTRADORES":"TODOS",id=generatedId(),created=now();let recipients:{user_id:number}[]=[];if(audience==="PLATFORM_OWNER")recipients=(await database().prepare("SELECT o.user_id FROM platform_owners o JOIN auth_users u ON u.id=o.user_id WHERE u.status='ATIVO' AND u.archived_at IS NULL").all<{user_id:number}>()).results;else if(audience==="ADMINISTRADORES")recipients=(await database().prepare("SELECT DISTINCT m.user_id FROM tenant_memberships m JOIN auth_users u ON u.id=m.user_id WHERE m.status='ATIVO' AND m.archived_at IS NULL AND m.role_name LIKE 'Administrador%' AND u.status='ATIVO' AND u.archived_at IS NULL").all<{user_id:number}>()).results;else recipients=(await database().prepare("SELECT id user_id FROM auth_users WHERE status='ATIVO' AND archived_at IS NULL").all<{user_id:number}>()).results;if(!recipients.length)return{recipients:0};await database().batch([database().prepare("INSERT INTO notifications(id,tenant_id,audience,type,title,message,priority,internal_route,group_key,metadata_json,mandatory,created_at,updated_at) VALUES(?,NULL,'PLATFORM','SISTEMA_NOVIDADE',?,?,'INFO',?,'SISTEMA_NOVIDADE',?,0,?,?)").bind(id,title,message,route,JSON.stringify({audience}),created,created),...recipients.map(recipient=>database().prepare("INSERT INTO notification_recipients(notification_id,user_id,created_at) VALUES(?,?,?)").bind(id,recipient.user_id,created))]);return{recipients:recipients.length};}
