import { generatedId, requirePermission } from "@/lib/server/admin";
import { ApiError, database, requestMetadata } from "@/lib/server/auth";
import { validateImageBytes, IMAGE_MAX_BYTES } from "@/lib/image-policy";
import { CONSENT_TEXT, CONSENT_VERSION } from "@/lib/members/custom-fields";
import { canAccessMemberScope, formatMemberCode, maskCpf } from "@/lib/members/policy";
import type { MemberWriteInput } from "@/lib/members/types";
import type { PreRegistrationDetail, PreRegistrationFormRecord, PreRegistrationListItem, PublicPreRegistrationForm } from "@/lib/members/pre-registration-types";
import { customFieldsForTenant, validateCustomValues } from "@/lib/server/member-custom-fields";
import { createMember } from "@/lib/server/members";
import { preRegistrationNotificationStatements } from "@/lib/server/notifications";
import { isValidCpf, normalizeDigits, normalizeEmail, normalizePhone } from "@/lib/server/validation";

const now=()=>new Date().toISOString();
const text=(value:unknown,max:number)=>typeof value==="string"?value.trim().replace(/[<>]/g,"").slice(0,max):"";
const positive=(value:unknown)=>{const n=Number(value);return Number.isInteger(n)&&n>0?n:null;};
async function digest(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,"0")).join("");}
export function createPublicToken(){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return btoa(String.fromCharCode(...bytes)).replaceAll("+","-").replaceAll("/","_").replaceAll("=","");}
const publicUrl=(request:Request,token:string)=>`${new URL(request.url).origin}/cadastro/${token}`;

type UnitRow={id:number;tenant_id:number;type:"CONVENCAO"|"MATRIZ"|"FILIAL";name:string;parent_id:number|null};
async function unitForTenant(id:number,tenantId:number){return database().prepare("SELECT id,tenant_id,type,name,parent_id FROM organizational_units WHERE id=? AND tenant_id=? AND archived_at IS NULL AND status='ATIVO'").bind(id,tenantId).first<UnitRow>();}
function assertUnitScope(session:Awaited<ReturnType<typeof requirePermission>>["session"],unit:UnitRow){const matrixId=unit.type==="MATRIZ"?unit.id:unit.type==="FILIAL"?unit.parent_id:null;const branchId=unit.type==="FILIAL"?unit.id:null;if(unit.type==="CONVENCAO"&&session.user.scope!=="CONVENCAO")throw new ApiError(403,"FORA_DO_ESCOPO","Formulário geral disponível apenas para a Convenção.");if(matrixId&&!canAccessMemberScope(session.user,{tenantId:unit.tenant_id,matrixId,branchId}))throw new ApiError(403,"FORA_DO_ESCOPO","Unidade fora do seu escopo.");}
async function formRowById(id:number,tenantId:number){return database().prepare("SELECT f.*,u.name unit_name,u.type unit_type,u.parent_id unit_parent_id FROM member_pre_registration_forms f LEFT JOIN organizational_units u ON u.id=f.unit_id AND u.tenant_id=f.tenant_id WHERE f.id=? AND f.tenant_id=?").bind(id,tenantId).first<Record<string,unknown>>();}
function assertFormRowScope(session:Awaited<ReturnType<typeof requirePermission>>["session"],row:Record<string,unknown>){const type=row.unit_type as UnitRow["type"]|null,id=positive(row.unit_id),parent=positive(row.unit_parent_id);if(!id){if(session.user.scope!=="CONVENCAO")throw new ApiError(403,"FORA_DO_ESCOPO","Formulário fora do seu escopo.");return;}if(type==="MATRIZ"&&session.user.scope!=="CONVENCAO"&&session.user.boundMatrixId!==id)throw new ApiError(403,"FORA_DO_ESCOPO","Formulário fora do seu escopo.");if(type==="FILIAL"&&!canAccessMemberScope(session.user,{tenantId:session.user.tenantId,matrixId:parent!,branchId:id}))throw new ApiError(403,"FORA_DO_ESCOPO","Formulário fora do seu escopo.");}
function mapForm(row:Record<string,unknown>):PreRegistrationFormRecord{return{id:Number(row.id),tenantId:Number(row.tenant_id),name:String(row.name),status:row.status as "ATIVO"|"INATIVO",unitId:row.unit_id===null?null:Number(row.unit_id),unitName:row.unit_name?String(row.unit_name):null,unitType:(row.unit_type??null) as PreRegistrationFormRecord["unitType"],expiresAt:row.expires_at?String(row.expires_at):null,submissionCount:Number(row.submission_count??0),pendingCount:Number(row.pending_count??0),tokenPrefix:String(row.token_prefix),createdAt:String(row.created_at),updatedAt:String(row.updated_at)};}

export async function listPreRegistrationForms(request:Request){const {session}=await requirePermission(request,"FORMULARIOS_PRECADASTRO_GERENCIAR");const rows=await database().prepare("SELECT f.*,u.name unit_name,u.type unit_type,u.parent_id unit_parent_id,(SELECT COUNT(*) FROM member_pre_registrations r WHERE r.form_id=f.id) submission_count,(SELECT COUNT(*) FROM member_pre_registrations r WHERE r.form_id=f.id AND r.status IN ('PENDENTE','EM_ANALISE')) pending_count FROM member_pre_registration_forms f LEFT JOIN organizational_units u ON u.id=f.unit_id AND u.tenant_id=f.tenant_id WHERE f.tenant_id=? ORDER BY f.id DESC").bind(session.user.tenantId).all<Record<string,unknown>>();return rows.results.filter(row=>{try{assertFormRowScope(session,row);return true;}catch{return false;}}).map(mapForm);}
export async function createPreRegistrationForm(request:Request,input:Record<string,unknown>){const {session,metadata}=await requirePermission(request,"FORMULARIOS_PRECADASTRO_GERENCIAR");const name=text(input.name,120);if(name.length<3)throw new ApiError(400,"DADOS_INVALIDOS","Informe um nome para o formulário.");const unitId=positive(input.unitId);if(!unitId&&session.user.scope!=="CONVENCAO")throw new ApiError(403,"FORA_DO_ESCOPO","Selecione uma unidade do seu escopo.");if(unitId){const unit=await unitForTenant(unitId,session.user.tenantId);if(!unit)throw new ApiError(400,"UNIDADE_INVALIDA","Unidade inválida.");assertUnitScope(session,unit);}const expiresAt=text(input.expiresAt,32)||null;if(expiresAt&&Number.isNaN(Date.parse(expiresAt)))throw new ApiError(400,"DATA_INVALIDA","Validade inválida.");const token=createPublicToken(),id=generatedId(),created=now();await database().batch([database().prepare("INSERT INTO member_pre_registration_forms (id,tenant_id,name,token_hash,token_prefix,unit_id,status,expires_at,created_by_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,'ATIVO',?,?,?,?)").bind(id,session.user.tenantId,name,await digest(token),token.slice(0,8),unitId,expiresAt,session.user.id,created,created),audit(session,metadata,"FORMULARIO_PRECADASTRO_CRIADO","FORMULARIO_PRECADASTRO",id,unitId,{name})]);const result=mapForm((await formRowById(id,session.user.tenantId))!);result.publicUrl=publicUrl(request,token);return result;}
export async function updatePreRegistrationForm(request:Request,id:number,input:Record<string,unknown>){const {session,metadata}=await requirePermission(request,"FORMULARIOS_PRECADASTRO_GERENCIAR");const existing=await formRowById(id,session.user.tenantId);if(!existing)throw new ApiError(404,"NAO_ENCONTRADO","Formulário não encontrado.");const name=text(input.name,120)||String(existing.name);const status=input.status==="INATIVO"?"INATIVO":"ATIVO";const expiresAt=input.expiresAt===null||input.expiresAt===""?null:text(input.expiresAt,32)||(existing.expires_at as string|null);await database().batch([database().prepare("UPDATE member_pre_registration_forms SET name=?,status=?,expires_at=?,updated_at=? WHERE id=? AND tenant_id=?").bind(name,status,expiresAt,now(),id,session.user.tenantId),audit(session,metadata,"FORMULARIO_PRECADASTRO_EDITADO","FORMULARIO_PRECADASTRO",id,positive(existing.unit_id),{name,status})]);return mapForm((await formRowById(id,session.user.tenantId))!);}
export async function rotatePreRegistrationToken(request:Request,id:number){const {session,metadata}=await requirePermission(request,"FORMULARIOS_PRECADASTRO_GERENCIAR");const existing=await formRowById(id,session.user.tenantId);if(!existing)throw new ApiError(404,"NAO_ENCONTRADO","Formulário não encontrado.");const token=createPublicToken();await database().batch([database().prepare("UPDATE member_pre_registration_forms SET token_hash=?,token_prefix=?,updated_at=? WHERE id=? AND tenant_id=?").bind(await digest(token),token.slice(0,8),now(),id,session.user.tenantId),audit(session,metadata,"LINK_PRECADASTRO_RENOVADO","FORMULARIO_PRECADASTRO",id,positive(existing.unit_id),{})]);return{publicUrl:publicUrl(request,token)};}

type PublicFormRow={id:number;tenant_id:number;name:string;expires_at:string|null;unit_id:number|null;unit_name:string|null;unit_type:UnitRow["type"]|null;parent_id:number|null;convention_id:number|null;institution_name:string};
async function activePublicForm(token:string){if(!/^[A-Za-z0-9_-]{43}$/.test(token))throw new ApiError(404,"FORMULARIO_INDISPONIVEL","Este formulário não está disponível.");const row=await database().prepare("SELECT f.id,f.tenant_id,f.name,f.expires_at,f.unit_id,u.name unit_name,u.type unit_type,u.parent_id,CASE WHEN u.type='CONVENCAO' THEN u.id WHEN u.type='MATRIZ' THEN u.parent_id WHEN u.type='FILIAL' THEN parent.parent_id ELSE NULL END convention_id,t.name institution_name FROM member_pre_registration_forms f JOIN tenants t ON t.id=f.tenant_id LEFT JOIN organizational_units u ON u.id=f.unit_id AND u.tenant_id=f.tenant_id LEFT JOIN organizational_units parent ON parent.id=u.parent_id AND parent.tenant_id=f.tenant_id WHERE f.token_hash=? AND f.status='ATIVO' AND t.status='ATIVO'").bind(await digest(token)).first<PublicFormRow>();if(!row||row.expires_at&&row.expires_at<=now())throw new ApiError(404,"FORMULARIO_INDISPONIVEL","Este formulário não está disponível.");return row;}
export async function publicPreRegistrationForm(token:string):Promise<PublicPreRegistrationForm>{const form=await activePublicForm(token);return{name:form.name,institutionName:form.institution_name,unitName:form.unit_name,expiresAt:form.expires_at,customFields:await customFieldsForTenant(form.tenant_id,"public",false)};}
async function enforceRate(request:Request,token:string){const metadata=requestMetadata(request);const key=await digest(`${metadata.ipAddress??"unknown"}:${token.slice(0,12)}`),cutoff=new Date(Date.now()-15*60_000).toISOString(),time=now();const row=await database().prepare("SELECT attempts,window_started_at FROM member_pre_registration_rate_limits WHERE rate_key=?").bind(key).first<{attempts:number;window_started_at:string}>();if(row&&row.window_started_at>cutoff&&row.attempts>=5)throw new ApiError(429,"MUITAS_TENTATIVAS","Muitas tentativas. Aguarde alguns minutos e tente novamente.");await database().prepare("INSERT INTO member_pre_registration_rate_limits (rate_key,attempts,window_started_at,updated_at) VALUES (?,1,?,?) ON CONFLICT(rate_key) DO UPDATE SET attempts=CASE WHEN window_started_at<? THEN 1 ELSE attempts+1 END,window_started_at=CASE WHEN window_started_at<? THEN excluded.window_started_at ELSE window_started_at END,updated_at=excluded.updated_at").bind(key,time,time,cutoff,cutoff).run();return key;}
function publicDate(value:unknown,label:string){const result=text(value,10)||null;if(result&&(!/^\d{4}-\d{2}-\d{2}$/.test(result)||Number.isNaN(Date.parse(`${result}T12:00:00Z`))))throw new ApiError(400,"DATA_INVALIDA",`Informe uma ${label} válida.`);return result;}
function publicChoice(value:unknown,allowed:readonly string[],fallback:string,label:string){const result=text(value,40)||fallback;if(!allowed.includes(result))throw new ApiError(400,"DADOS_INVALIDOS",`${label} inválido.`);return result;}
function publicPayload(raw:Record<string,unknown>):MemberWriteInput{
  const fullName=text(raw.fullName,180);if(fullName.length<3)throw new ApiError(400,"DADOS_INVALIDOS","Informe o nome completo.");
  const cpf=normalizeDigits(raw.cpf);if(cpf&&!isValidCpf(cpf))throw new ApiError(400,"CPF_INVALIDO","Informe um CPF válido.");
  const email=normalizeEmail(raw.email);if(text(raw.email,254)&&!email)throw new ApiError(400,"EMAIL_INVALIDO","Informe um e-mail válido.");
  const phone=normalizePhone(raw.phone);if(normalizeDigits(raw.phone)&&!phone)throw new ApiError(400,"TELEFONE_INVALIDO","Informe um telefone com DDD.");
  const whatsapp=normalizePhone(raw.whatsapp);if(normalizeDigits(raw.whatsapp)&&!whatsapp)throw new ApiError(400,"WHATSAPP_INVALIDO","Informe um WhatsApp com DDD.");
  const voterTitle=normalizeDigits(raw.voterTitle);if(voterTitle&&voterTitle.length>20)throw new ApiError(400,"TITULO_ELEITOR_INVALIDO","Informe somente os números do Título de Eleitor.");
  const postalCode=normalizeDigits(raw.postalCode);if(postalCode&&postalCode.length!==8)throw new ApiError(400,"CEP_INVALIDO","O CEP deve conter 8 dígitos.");
  const childrenCount=Number(raw.childrenCount??0);if(!Number.isInteger(childrenCount)||childrenCount<0||childrenCount>99)throw new ApiError(400,"DADOS_INVALIDOS","Quantidade de filhos inválida.");
  return{fullName,status:"MEMBRO_ATIVO",birthDate:publicDate(raw.birthDate,"data de nascimento"),sex:publicChoice(raw.sex,["MASCULINO","FEMININO","NAO_INFORMADO"],"NAO_INFORMADO","Sexo"),cpf:cpf||null,rg:text(raw.rg,30)||null,voterTitle:voterTitle||null,birthCity:text(raw.birthCity,120)||null,birthState:text(raw.birthState,2).toUpperCase()||null,phone,whatsapp,email,motherName:text(raw.motherName,180)||null,fatherName:text(raw.fatherName,180)||null,maritalStatus:publicChoice(raw.maritalStatus,["SOLTEIRO","CASADO","DIVORCIADO","VIUVO","UNIAO_ESTAVEL","OUTRO","NAO_INFORMADO"],"NAO_INFORMADO","Estado civil"),spouseName:text(raw.spouseName,180)||null,childrenCount,postalCode:postalCode||null,street:text(raw.street,180)||null,addressNumber:text(raw.addressNumber,30)||null,complement:text(raw.complement,120)||null,district:text(raw.district,120)||null,city:text(raw.city,120)||null,state:text(raw.state,2).toUpperCase()||null,profession:text(raw.profession,120)||null,workplace:text(raw.workplace,150)||null,educationLevel:publicChoice(raw.educationLevel,["NAO_INFORMADO","NAO_ALFABETIZADO","FUNDAMENTAL_INCOMPLETO","FUNDAMENTAL_COMPLETO","MEDIO_INCOMPLETO","MEDIO_COMPLETO","SUPERIOR_INCOMPLETO","SUPERIOR_COMPLETO","POS_GRADUACAO","MESTRADO","DOUTORADO"],"NAO_INFORMADO","Escolaridade"),theologicalEducation:publicChoice(raw.theologicalEducation,["NAO_INFORMADO","NENHUMA","BASICO","MEDIO","AVANCADO","OUTRO"],"NAO_INFORMADO","Formação teológica"),churchEntryDate:publicDate(raw.churchEntryDate,"data de entrada"),originChurch:text(raw.originChurch,180)||null,conversionDate:publicDate(raw.conversionDate,"data de conversão"),baptismDate:publicDate(raw.baptismDate,"data de batismo"),consecrationDate:publicDate(raw.consecrationDate,"data de consagração"),customValues:raw.customValues as Record<string,unknown>};
}
export async function submitPreRegistration(request:Request,token:string,raw:Record<string,unknown>,photo:File|null){const form=await activePublicForm(token);const sourceHash=await enforceRate(request,token);if(raw.consent!==true)throw new ApiError(400,"CONSENTIMENTO_OBRIGATORIO","É necessário autorizar o uso dos dados para concluir.");const payload=publicPayload(raw),values=await validateCustomValues(form.tenant_id,payload.customValues,"public");let image:null|{bytes:Uint8Array;mime:string}=null;if(photo&&photo.size){if(photo.size>IMAGE_MAX_BYTES)throw new ApiError(400,"IMAGEM_INVALIDA","A foto deve ter no máximo 2 MB.");const bytes=new Uint8Array(await photo.arrayBuffer()),mime=validateImageBytes(bytes,photo.type);if(!mime)throw new ApiError(400,"IMAGEM_INVALIDA","Envie uma foto PNG, JPG, JPEG ou WebP válida.");image={bytes,mime};}let matrixId:number|null=null,branchId:number|null=null;if(form.unit_type==="MATRIZ")matrixId=form.unit_id;else if(form.unit_type==="FILIAL"){matrixId=form.parent_id;branchId=form.unit_id;}const id=generatedId(),created=now(),statements:D1PreparedStatement[]=[database().prepare("INSERT INTO member_pre_registrations (id,tenant_id,form_id,full_name,birth_date,cpf,phone,whatsapp,email,voter_title,matrix_id,branch_id,status,payload_json,consent_at,consent_version,source_hash,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?, 'PENDENTE',?,?,?,?,?,?)").bind(id,form.tenant_id,form.id,payload.fullName,payload.birthDate??null,payload.cpf??null,payload.phone??null,payload.whatsapp??null,payload.email??null,payload.voterTitle??null,matrixId,branchId,JSON.stringify(payload),created,CONSENT_VERSION,sourceHash,created,created),database().prepare("INSERT INTO audit_logs (user_id,tenant_id,event,reason,matrix_id,branch_id,created_at) VALUES (NULL,?,'PRECADASTRO_RECEBIDO',?,?,?,?)").bind(form.tenant_id,`Consentimento ${CONSENT_VERSION}: ${CONSENT_TEXT}`,matrixId,branchId,created)];for(const value of values)if(value.value!==null)statements.push(database().prepare("INSERT INTO member_pre_registration_custom_values (pre_registration_id,tenant_id,field_id,value_text,created_at) VALUES (?,?,?,?,?)").bind(id,form.tenant_id,value.field.id,value.value,created));if(image)statements.push(database().prepare("INSERT INTO member_pre_registration_photos (pre_registration_id,tenant_id,image_data,mime_type,byte_size,updated_at) VALUES (?,?,?,?,?,?)").bind(id,form.tenant_id,image.bytes.buffer,image.mime,image.bytes.length,created));statements.push(...await preRegistrationNotificationStatements({tenantId:form.tenant_id,conventionId:form.convention_id,matrixId,branchId,preRegistrationId:id,fullName:String(payload.fullName),createdAt:created}));await database().batch(statements);return{id,message:"Pré-cadastro enviado com sucesso. A igreja fará a análise dos dados."};}

function scopeSql(session:Awaited<ReturnType<typeof requirePermission>>["session"]){if(session.user.scope==="MATRIZ")return{sql:" AND r.matrix_id=?",args:[session.user.boundMatrixId]};if(session.user.scope==="FILIAL")return{sql:" AND r.branch_id=?",args:[session.user.boundBranchId]};return{sql:"",args:[]};}
export async function listPreRegistrations(request:Request,query:Record<string,unknown>){const {session}=await requirePermission(request,"PRECADASTROS_VISUALIZAR"),scope=scopeSql(session),status=text(query.status,30),search=text(query.search,120);const where=["r.tenant_id=?"],args:unknown[]=[session.user.tenantId];if(status){where.push("r.status=?");args.push(status);}if(search){where.push("(r.full_name LIKE ? COLLATE NOCASE OR r.cpf LIKE ? OR r.phone LIKE ?)");args.push(`%${search}%`,`%${normalizeDigits(search)}%`,`%${normalizeDigits(search)}%`);}const rows=await database().prepare(`SELECT r.*,COALESCE(b.name,m.name) unit_name,CASE WHEN ph.pre_registration_id IS NULL THEN 0 ELSE 1 END has_photo FROM member_pre_registrations r LEFT JOIN organizational_units m ON m.id=r.matrix_id LEFT JOIN organizational_units b ON b.id=r.branch_id LEFT JOIN member_pre_registration_photos ph ON ph.pre_registration_id=r.id WHERE ${where.join(" AND ")}${scope.sql} ORDER BY r.id DESC LIMIT 200`).bind(...args,...scope.args).all<Record<string,unknown>>();return rows.results.map(mapList);}
function mapList(row:Record<string,unknown>):PreRegistrationListItem{return{id:Number(row.id),fullName:String(row.full_name),maskedCpf:maskCpf(row.cpf?String(row.cpf):null),phone:row.phone?String(row.phone):null,whatsapp:row.whatsapp?String(row.whatsapp):null,status:row.status as PreRegistrationListItem["status"],unitName:row.unit_name?String(row.unit_name):null,photoUrl:Number(row.has_photo)?`/api/admin/pre-registrations/${row.id}/photo`:null,createdAt:String(row.created_at)};}
async function scopedRegistration(session:Awaited<ReturnType<typeof requirePermission>>["session"],id:number){const row=await database().prepare("SELECT r.*,COALESCE(b.name,m.name) unit_name,CASE WHEN ph.pre_registration_id IS NULL THEN 0 ELSE 1 END has_photo FROM member_pre_registrations r LEFT JOIN organizational_units m ON m.id=r.matrix_id LEFT JOIN organizational_units b ON b.id=r.branch_id LEFT JOIN member_pre_registration_photos ph ON ph.pre_registration_id=r.id WHERE r.id=? AND r.tenant_id=?").bind(id,session.user.tenantId).first<Record<string,unknown>>();if(!row)throw new ApiError(404,"NAO_ENCONTRADO","Pré-cadastro não encontrado.");const matrix=positive(row.matrix_id),branch=positive(row.branch_id);if(matrix&&!canAccessMemberScope(session.user,{tenantId:session.user.tenantId,matrixId:matrix,branchId:branch}))throw new ApiError(403,"FORA_DO_ESCOPO","Pré-cadastro fora do seu escopo.");if(!matrix&&session.user.scope!=="CONVENCAO")throw new ApiError(403,"FORA_DO_ESCOPO","Pré-cadastro geral disponível apenas para a Convenção.");return row;}
export async function getPreRegistration(request:Request,id:number):Promise<PreRegistrationDetail>{const {session,permissions}=await requirePermission(request,"PRECADASTROS_VISUALIZAR"),row=await scopedRegistration(session,id);if((row.status==="PENDENTE")&&permissions.has("PRECADASTROS_ANALISAR"))await database().prepare("UPDATE member_pre_registrations SET status='EM_ANALISE',updated_at=? WHERE id=? AND status='PENDENTE'").bind(now(),id).run();const custom=await database().prepare("SELECT field_id,value_text FROM member_pre_registration_custom_values WHERE pre_registration_id=? AND tenant_id=?").bind(id,session.user.tenantId).all<{field_id:number;value_text:string}>();const cpf=row.cpf?String(row.cpf):null;const duplicate=cpf?await database().prepare("SELECT id,member_number,full_name,cpf FROM people WHERE tenant_id=? AND cpf=? LIMIT 1").bind(session.user.tenantId,cpf).first<{id:number;member_number:number;full_name:string;cpf:string}>():null;return{...mapList(row),status:(row.status==="PENDENTE"&&permissions.has("PRECADASTROS_ANALISAR")?"EM_ANALISE":row.status) as PreRegistrationDetail["status"],birthDate:row.birth_date?String(row.birth_date):null,cpf,email:row.email?String(row.email):null,voterTitle:row.voter_title?String(row.voter_title):null,matrixId:positive(row.matrix_id),branchId:positive(row.branch_id),payload:JSON.parse(String(row.payload_json)),customValues:Object.fromEntries(custom.results.map(v=>[String(v.field_id),v.value_text])),consentAt:String(row.consent_at),consentVersion:String(row.consent_version),reviewReason:row.review_reason?String(row.review_reason):null,duplicate:duplicate?{id:duplicate.id,memberCode:formatMemberCode(duplicate.member_number),fullName:duplicate.full_name,maskedCpf:maskCpf(duplicate.cpf)}:null,approvedMemberId:positive(row.approved_member_id)};}
export async function approvePreRegistration(request:Request,id:number,input:MemberWriteInput){const {session,metadata}=await requirePermission(request,"PRECADASTROS_APROVAR"),row=await scopedRegistration(session,id);if(!["PENDENTE","EM_ANALISE","AGUARDANDO_CORRECAO"].includes(String(row.status)))throw new ApiError(409,"SITUACAO_INVALIDA","Este pré-cadastro já foi concluído.");const member=await createMember(request,input);const photo=await database().prepare("SELECT image_data,mime_type,byte_size FROM member_pre_registration_photos WHERE pre_registration_id=? AND tenant_id=?").bind(id,session.user.tenantId).first<{image_data:ArrayBuffer;mime_type:string;byte_size:number}>();const completed=now(),statements:D1PreparedStatement[]=[database().prepare("UPDATE member_pre_registrations SET status='APROVADO',approved_member_id=?,reviewed_by_user_id=?,reviewed_at=?,updated_at=? WHERE id=? AND tenant_id=?").bind(member.id,session.user.id,completed,completed,id,session.user.tenantId),audit(session,metadata,"PRECADASTRO_APROVADO","PRECADASTRO",id,member.branchId??member.matrixId,{memberId:member.id,memberCode:member.memberCode})];if(photo)statements.push(database().prepare("INSERT OR REPLACE INTO member_photos (person_id,tenant_id,image_data,mime_type,byte_size,updated_at) VALUES (?,?,?,?,?,?)").bind(member.id,session.user.tenantId,photo.image_data,photo.mime_type,photo.byte_size,completed));await database().batch(statements);return member;}
export async function rejectPreRegistration(request:Request,id:number,reasonValue:unknown){const {session,metadata}=await requirePermission(request,"PRECADASTROS_RECUSAR"),row=await scopedRegistration(session,id),reason=text(reasonValue,500);if(reason.length<3)throw new ApiError(400,"MOTIVO_OBRIGATORIO","Informe o motivo da recusa.");if(!["PENDENTE","EM_ANALISE","AGUARDANDO_CORRECAO"].includes(String(row.status)))throw new ApiError(409,"SITUACAO_INVALIDA","Este pré-cadastro já foi concluído.");const completed=now();await database().batch([database().prepare("UPDATE member_pre_registrations SET status='RECUSADO',review_reason=?,reviewed_by_user_id=?,reviewed_at=?,updated_at=? WHERE id=? AND tenant_id=?").bind(reason,session.user.id,completed,completed,id,session.user.tenantId),audit(session,metadata,"PRECADASTRO_RECUSADO","PRECADASTRO",id,positive(row.branch_id)??positive(row.matrix_id),{reason})]);return{message:"Pré-cadastro recusado."};}
export async function preRegistrationPhoto(request:Request,id:number){const {session}=await requirePermission(request,"PRECADASTROS_VISUALIZAR");await scopedRegistration(session,id);const photo=await database().prepare("SELECT image_data,mime_type,updated_at FROM member_pre_registration_photos WHERE pre_registration_id=? AND tenant_id=?").bind(id,session.user.tenantId).first<{image_data:ArrayBuffer;mime_type:string;updated_at:string}>();if(!photo)throw new ApiError(404,"FOTO_NAO_ENCONTRADA","Foto não encontrada.");return new Response(photo.image_data,{headers:{"Content-Type":photo.mime_type,"Cache-Control":"private, max-age=300","X-Content-Type-Options":"nosniff"}});}
function audit(session:Awaited<ReturnType<typeof requirePermission>>["session"],metadata:ReturnType<typeof requestMetadata>,action:string,entityType:string,id:number,unitId:number|null,details:unknown){return database().prepare("INSERT INTO administration_audit (actor_user_id,actor_membership_id,tenant_id,convention_id,action,entity_type,entity_id,unit_id,ip_address,user_agent,device_summary,details,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(session.user.id,session.user.membershipId,session.user.tenantId,session.user.conventionId,action,entityType,id,unitId,metadata.ipAddress,metadata.userAgent,metadata.deviceSummary,JSON.stringify(details),now());}
