import assert from "node:assert/strict";
import test from "node:test";
import { allocationPercentageStatus, calculateAllocation, canReopenPeriod, canTransfer, contributionIdentity, moneyDigitsToCents, normalizePastedMoneyToCents, parseMoneyToCents, previousMonthCompetency, splitInstallments, validateAllocationRules } from "../lib/finance/policy.ts";

test("valores financeiros são inteiros em centavos",()=>{assert.equal(parseMoneyToCents("1.234,56"),123456);assert.equal(parseMoneyToCents("0,01"),1);assert.throws(()=>parseMoneyToCents("1,999"));assert.throws(()=>parseMoneyToCents(1.5));});
test("parcelamento preserva exatamente o total",()=>{const parts=splitInstallments(10000,3);assert.deepEqual(parts,[3334,3333,3333]);assert.equal(parts.reduce((sum,value)=>sum+value,0),10000);});
test("anonimato remove pessoa e identificação privada exige pessoa",()=>{assert.deepEqual(contributionIdentity("ANONIMA",77),{personId:null,publicName:"Anônimo"});assert.deepEqual(contributionIdentity("IDENTIFICADA_PRIVADA",77),{personId:77,publicName:"Contribuinte privado"});assert.throws(()=>contributionIdentity("IDENTIFICADA",null));});
test("transferência exige contas distintas e valor positivo",()=>{assert.equal(canTransfer(1,2,100),true);assert.equal(canTransfer(1,1,100),false);assert.equal(canTransfer(1,2,0),false);});
test("máscara incremental e valores colados preservam centavos",()=>{assert.equal(moneyDigitsToCents("5"),5);assert.equal(moneyDigitsToCents("500"),500);assert.equal(normalizePastedMoneyToCents("1.250,50"),125050);assert.equal(normalizePastedMoneyToCents("R$ 1.250,50"),125050);assert.equal(normalizePastedMoneyToCents("1250"),125000);});
test("rateio percentual informa falta e excesso até fechar 100%",()=>{assert.deepEqual(allocationPercentageStatus([{ruleType:"PERCENTUAL",percentageBasisPoints:6000},{ruleType:"PERCENTUAL",percentageBasisPoints:4000}]),{totalBasisPoints:10000,integral:true,valid:true,missingBasisPoints:0,excessBasisPoints:0});assert.equal(allocationPercentageStatus([{ruleType:"PERCENTUAL",percentageBasisPoints:9500}]).missingBasisPoints,500);assert.equal(allocationPercentageStatus([{ruleType:"PERCENTUAL",percentageBasisPoints:10500}]).excessBasisPoints,500);});
test("rateio combina valor fixo, percentual sobre a base original e saldo restante",()=>{const result=calculateAllocation(1_000_000,[{recipientName:"Pastor",ruleType:"FIXO",fixedAmountCents:150_000},{recipientName:"Convenção",ruleType:"PERCENTUAL",percentageBasisPoints:1500},{recipientName:"Igreja",ruleType:"RESTANTE"}]);assert.equal(result.valid,true);assert.deepEqual(result.results.map(item=>item.calculatedAmountCents),[150_000,150_000,700_000]);assert.equal(result.allocatedCents,1_000_000);});
test("rateio bloqueia excesso e dois saldos restantes",()=>{const excess=calculateAllocation(1_000_000,[{recipientName:"Fixo",ruleType:"FIXO",fixedAmountCents:700_000},{recipientName:"Percentual",ruleType:"PERCENTUAL",percentageBasisPoints:5000}]);assert.equal(excess.valid,false);assert.equal(excess.excessCents,200_000);assert.equal(validateAllocationRules([{ruleType:"RESTANTE"},{ruleType:"RESTANTE"}]).code,"SALDO_RESTANTE_DUPLICADO");});
test("rateio de centavos fecha exatamente e de forma determinística",()=>{const result=calculateAllocation(10_001,[{recipientName:"A",ruleType:"PERCENTUAL",percentageBasisPoints:5000},{recipientName:"B",ruleType:"PERCENTUAL",percentageBasisPoints:3000},{recipientName:"C",ruleType:"PERCENTUAL",percentageBasisPoints:2000}]);assert.deepEqual(result.results.map(item=>item.calculatedAmountCents),[5000,3000,2001]);assert.equal(result.results.reduce((sum,item)=>sum+item.calculatedAmountCents,0),10_001);});
test("rateio preserva a destinação financeira sem depender do nome",()=>{const result=calculateAllocation(1_000_000,[{recipientName:"Dirigente",ruleType:"PERCENTUAL",percentageBasisPoints:3000,financialDestination:"REPASSAR"},{recipientName:"Matriz",ruleType:"PERCENTUAL",percentageBasisPoints:4000,financialDestination:"REPASSAR"},{recipientName:"Congregação",ruleType:"PERCENTUAL",percentageBasisPoints:3000,financialDestination:"MANTER_NA_UNIDADE"}]);assert.deepEqual(result.results.map(item=>[item.calculatedAmountCents,item.financialDestination]),[[300_000,"REPASSAR"],[400_000,"REPASSAR"],[300_000,"MANTER_NA_UNIDADE"]]);assert.equal(result.results.filter(item=>item.financialDestination==="REPASSAR").reduce((sum,item)=>sum+item.calculatedAmountCents,0),700_000);assert.equal(result.results.filter(item=>item.financialDestination==="MANTER_NA_UNIDADE").reduce((sum,item)=>sum+item.calculatedAmountCents,0),300_000);});
test("reabertura direta pertence à Matriz ou ao proprietário no contexto do cliente",()=>{assert.equal(canReopenPeriod({scope:"MATRIZ",boundMatrixId:20,isPlatformOwner:false},{matrixId:20}),true);assert.equal(canReopenPeriod({scope:"FILIAL",boundMatrixId:20,isPlatformOwner:false},{matrixId:20}),false);assert.equal(canReopenPeriod({scope:"MATRIZ",boundMatrixId:99,isPlatformOwner:false},{matrixId:20}),false);assert.equal(canReopenPeriod({scope:"PLATAFORMA",boundMatrixId:null,isPlatformOwner:true,platformTenantContextActive:false},{matrixId:20}),false);assert.equal(canReopenPeriod({scope:"PLATAFORMA",boundMatrixId:null,isPlatformOwner:true,platformTenantContextActive:true},{matrixId:20}),true);});
test("competência sugerida é o mês anterior e respeita a virada do ano",()=>{assert.equal(previousMonthCompetency(new Date("2026-08-12T12:00:00Z")),"2026-07");assert.equal(previousMonthCompetency(new Date("2027-01-03T12:00:00Z")),"2026-12");});
