import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { DatabaseSync } from "node:sqlite";

function apply(db,name){for(const sql of readFileSync(new URL(`../drizzle/${name}.sql`,import.meta.url),"utf8").split("--> statement-breakpoint").map(value=>value.trim()).filter(Boolean))db.exec(sql);}
function fixture(){const db=new DatabaseSync(":memory:");db.exec(`PRAGMA foreign_keys=ON;
CREATE TABLE tenants(id INTEGER PRIMARY KEY);
CREATE TABLE organizational_units(id INTEGER PRIMARY KEY,tenant_id INTEGER,type TEXT,name TEXT,parent_id INTEGER,status TEXT,archived_at TEXT,UNIQUE(id,tenant_id));
CREATE TABLE organizational_functions(id INTEGER PRIMARY KEY,tenant_id INTEGER,name TEXT,status TEXT,UNIQUE(id,tenant_id));
CREATE TABLE auth_users(id INTEGER PRIMARY KEY,status TEXT,archived_at TEXT);
CREATE TABLE tenant_memberships(id INTEGER PRIMARY KEY,user_id INTEGER,tenant_id INTEGER,display_name TEXT,role_name TEXT,scope TEXT,scope_unit_id INTEGER,status TEXT,archived_at TEXT,UNIQUE(id,tenant_id));
CREATE TABLE membership_permissions(membership_id INTEGER,permission TEXT,created_at TEXT,PRIMARY KEY(membership_id,permission));
CREATE TABLE user_permissions(user_id INTEGER,permission TEXT,created_at TEXT,PRIMARY KEY(user_id,permission));
CREATE TABLE platform_owners(singleton_id INTEGER PRIMARY KEY,user_id INTEGER);
CREATE TABLE people(id INTEGER PRIMARY KEY,tenant_id INTEGER,full_name TEXT,birth_date TEXT,sex TEXT,cpf TEXT,phone TEXT,whatsapp TEXT,linked_auth_user_id INTEGER,UNIQUE(id,tenant_id));
CREATE TABLE help_articles(id INTEGER PRIMARY KEY,tenant_id INTEGER,slug TEXT,title TEXT,summary TEXT,content TEXT,category TEXT,display_order INTEGER,target_profiles TEXT,required_permission TEXT,related_route TEXT,published INTEGER,is_new_feature INTEGER,released_at TEXT,version TEXT,created_by_user_id INTEGER,published_at TEXT,created_at TEXT,updated_at TEXT,UNIQUE(tenant_id,slug));
CREATE TABLE help_article_reads(user_id INTEGER,article_id INTEGER,viewed_at TEXT,PRIMARY KEY(user_id,article_id));
INSERT INTO tenants VALUES(1),(2),(1770000000000000);INSERT INTO organizational_units VALUES(10,1,'CONVENCAO','Convenção A',NULL,'ATIVO',NULL),(20,1,'MATRIZ','Matriz A',10,'ATIVO',NULL),(30,1,'FILIAL','Filial A',20,'ATIVO',NULL),(110,2,'CONVENCAO','Convenção B',NULL,'ATIVO',NULL),(120,2,'MATRIZ','Matriz B',110,'ATIVO',NULL);INSERT INTO organizational_functions VALUES(80,1,'Pastor','ATIVO'),(180,2,'Pastor','ATIVO');INSERT INTO auth_users VALUES(1,'ATIVO',NULL),(2,'ATIVO',NULL);INSERT INTO tenant_memberships VALUES(1,1,1,'Admin A','Administrador da Convenção','CONVENCAO',10,'ATIVO',NULL),(2,2,2,'Admin B','Administrador da Convenção','CONVENCAO',110,'ATIVO',NULL);INSERT INTO people VALUES(1001,1,'Pessoa A','1990-01-01','FEMININO','11111111111','1111','1111',1),(2001,2,'Pessoa B',NULL,NULL,NULL,NULL,NULL,2);INSERT INTO platform_owners VALUES(1,1);`);apply(db,"0019_departments_ebd");apply(db,"0022_finance_core");return db;}

test("0022 instala núcleo financeiro, permissões e guias",()=>{const db=fixture();for(const table of ["finance_accounts","finance_categories","finance_payment_methods","finance_cost_centers","finance_funds","finance_campaigns","finance_movements","finance_contributions","finance_obligations","finance_installments","finance_transfers","finance_attachments","finance_audit"])assert.ok(db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").get(table),table);assert.equal(db.prepare("SELECT COUNT(*) total FROM help_articles WHERE category='Financeiro'").get().total,15);assert.equal(db.prepare("SELECT COUNT(*) total FROM membership_permissions WHERE membership_id=1 AND permission LIKE 'FINANCEIRO_%'").get().total,14);assert.equal(db.prepare("SELECT COUNT(*) total FROM finance_categories WHERE tenant_id=1").get().total,5);assert.equal(db.prepare("SELECT COUNT(*) total FROM finance_categories WHERE tenant_id=1770000000000000").get().total,5);assert.equal(typeof db.prepare("SELECT id FROM finance_categories WHERE tenant_id=1770000000000000 LIMIT 1").get().id,"number");});
test("tenant, transferência e privacidade são protegidos no banco",()=>{const db=fixture();db.exec(`INSERT INTO finance_accounts VALUES(1,1,20,'Caixa','CAIXA_FISICO',NULL,0,'2026-08-11','ATIVA',1,'2026-08-11','2026-08-11');INSERT INTO finance_accounts VALUES(2,1,20,'Banco','CONTA_CORRENTE',NULL,0,'2026-08-11','ATIVA',1,'2026-08-11','2026-08-11');INSERT INTO finance_accounts VALUES(3,2,120,'Outro tenant','CAIXA_FISICO',NULL,0,'2026-08-11','ATIVA',2,'2026-08-11','2026-08-11');INSERT INTO finance_movements(id,tenant_id,unit_id,account_id,direction,amount_cents,occurred_on,competency,description,source,privacy,created_by_user_id,created_at) VALUES(10,1,20,1,'ENTRADA',1000,'2026-08-11','2026-08','Oferta','MANUAL','ANONIMA',1,'2026-08-11');INSERT INTO finance_contributions VALUES(11,1,10,'OFERTA',NULL,'ANONIMA','2026-08-11');`);assert.throws(()=>db.exec("INSERT INTO finance_contributions VALUES(12,1,10,'OFERTA',1001,'ANONIMA','2026-08-11')"));assert.throws(()=>db.exec("INSERT INTO finance_movements(id,tenant_id,unit_id,account_id,direction,amount_cents,occurred_on,competency,description,source,privacy,created_by_user_id,created_at) VALUES(13,1,20,3,'ENTRADA',1000,'2026-08-11','2026-08','IDOR','MANUAL','ANONIMA',1,'2026-08-11')"));assert.throws(()=>db.exec("INSERT INTO finance_transfers(id,tenant_id,unit_id,origin_account_id,destination_account_id,amount_cents,occurred_on,out_movement_id,in_movement_id,created_by_user_id,created_at) VALUES(20,1,20,1,1,100,'2026-08-11',10,10,1,'2026-08-11')"));});
test("idempotência bloqueia baixa e estorno duplicados",()=>{const db=fixture();db.exec(`INSERT INTO finance_accounts VALUES(1,1,20,'Caixa','CAIXA_FISICO',NULL,0,'2026-08-11','ATIVA',1,'2026-08-11','2026-08-11');INSERT INTO finance_movements(id,tenant_id,unit_id,account_id,direction,amount_cents,occurred_on,competency,description,source,privacy,idempotency_key,created_by_user_id,created_at) VALUES(10,1,20,1,'ENTRADA',1000,'2026-08-11','2026-08','Recebimento','CONTA_RECEBER','IDENTIFICADA_PRIVADA','installment:1',1,'2026-08-11');`);assert.throws(()=>db.exec("INSERT INTO finance_movements(id,tenant_id,unit_id,account_id,direction,amount_cents,occurred_on,competency,description,source,privacy,idempotency_key,created_by_user_id,created_at) VALUES(11,1,20,1,'ENTRADA',1000,'2026-08-11','2026-08','Duplicado','CONTA_RECEBER','IDENTIFICADA_PRIVADA','installment:1',1,'2026-08-11')"));});
