import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import test from "node:test";
import {DatabaseSync} from "node:sqlite";
function apply(db){for(const sql of readFileSync(new URL("../drizzle/0017_help_and_exports.sql",import.meta.url),"utf8").split("--> statement-breakpoint").map(x=>x.trim()).filter(Boolean))db.exec(sql);}
function fixture(){const db=new DatabaseSync(":memory:");db.exec("PRAGMA foreign_keys=ON;CREATE TABLE tenants(id INTEGER PRIMARY KEY);CREATE TABLE auth_users(id INTEGER PRIMARY KEY);CREATE TABLE organizational_units(id INTEGER PRIMARY KEY);CREATE TABLE tenant_memberships(id INTEGER PRIMARY KEY,scope TEXT,status TEXT,archived_at TEXT,role_name TEXT);CREATE TABLE membership_permissions(membership_id INTEGER,permission TEXT,created_at TEXT,PRIMARY KEY(membership_id,permission));CREATE TABLE platform_owners(singleton_id INTEGER PRIMARY KEY,user_id INTEGER);CREATE TABLE user_permissions(user_id INTEGER,permission TEXT,created_at TEXT,PRIMARY KEY(user_id,permission));INSERT INTO tenants VALUES(1),(2);INSERT INTO auth_users VALUES(1),(2);INSERT INTO organizational_units VALUES(10);INSERT INTO tenant_memberships VALUES(1,'CONVENCAO','ATIVO',NULL,'Administrador da Convenção'),(2,'FILIAL','ATIVO',NULL,'Usuário');INSERT INTO platform_owners VALUES(1,1);");apply(db);return db;}
test("0017 cria ajuda, leitura e auditoria de exportação",()=>{const db=fixture();for(const table of ["help_articles","help_article_reads","data_export_audit"])assert.ok(db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").get(table));assert.equal(db.prepare("SELECT COUNT(*) total FROM help_articles WHERE published=1").get().total,9);});
test("0017 concede exportação completa somente ao alcance máximo inicial",()=>{const db=fixture();assert.equal(db.prepare("SELECT COUNT(*) total FROM membership_permissions WHERE membership_id=1 AND permission='DADOS_EXPORTAR_COMPLETO'").get().total,1);assert.equal(db.prepare("SELECT COUNT(*) total FROM membership_permissions WHERE membership_id=2 AND permission LIKE 'DADOS_EXPORTAR%'").get().total,0);assert.equal(db.prepare("SELECT COUNT(*) total FROM user_permissions WHERE permission='DADOS_EXPORTAR_COMPLETO'").get().total,1);});
test("leitura é individual e exportações registram somente metadados",()=>{const db=fixture();db.exec("INSERT INTO help_article_reads VALUES(1,17001,'2026-08-11');INSERT INTO data_export_audit(actor_user_id,tenant_id,export_type,modules,format,record_count,scope_unit_id,status,created_at) VALUES(1,1,'members','membros','XLSX',3,10,'CONCLUIDA','2026-08-11')");assert.equal(db.prepare("SELECT COUNT(*) total FROM help_article_reads WHERE user_id=2").get().total,0);const columns=db.prepare("PRAGMA table_info(data_export_audit)").all().map(x=>x.name);for(const forbidden of ["password_hash","token","file_data"])assert.equal(columns.includes(forbidden),false);});
