import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import test from "node:test";
import {DatabaseSync} from "node:sqlite";
function apply(db){for(const sql of readFileSync(new URL("../drizzle/0019_departments_ebd.sql",import.meta.url),"utf8").split("--> statement-breakpoint").map(value=>value.trim()).filter(Boolean))db.exec(sql);}
function fixture(){const db=new DatabaseSync(":memory:");db.exec(`PRAGMA foreign_keys=ON;
 CREATE TABLE tenants(id INTEGER PRIMARY KEY);
 CREATE TABLE organizational_units(id INTEGER PRIMARY KEY,tenant_id INTEGER,type TEXT,name TEXT,status TEXT,archived_at TEXT,UNIQUE(id,tenant_id));
 CREATE TABLE auth_users(id INTEGER PRIMARY KEY,status TEXT,archived_at TEXT);
 CREATE TABLE tenant_memberships(id INTEGER PRIMARY KEY,user_id INTEGER,tenant_id INTEGER,display_name TEXT,role_name TEXT,scope TEXT,scope_unit_id INTEGER,status TEXT,archived_at TEXT,UNIQUE(id,tenant_id));
 CREATE TABLE membership_permissions(membership_id INTEGER,permission TEXT,created_at TEXT,PRIMARY KEY(membership_id,permission));
 CREATE TABLE user_permissions(user_id INTEGER,permission TEXT,created_at TEXT,PRIMARY KEY(user_id,permission));
 CREATE TABLE platform_owners(singleton_id INTEGER PRIMARY KEY,user_id INTEGER);
 CREATE TABLE people(id INTEGER PRIMARY KEY,tenant_id INTEGER,full_name TEXT,linked_auth_user_id INTEGER,UNIQUE(id,tenant_id));
 CREATE TABLE help_articles(id INTEGER PRIMARY KEY,tenant_id INTEGER,slug TEXT,title TEXT,summary TEXT,content TEXT,category TEXT,display_order INTEGER,target_profiles TEXT,required_permission TEXT,related_route TEXT,published INTEGER,is_new_feature INTEGER,released_at TEXT,version TEXT,created_by_user_id INTEGER,published_at TEXT,created_at TEXT,updated_at TEXT,UNIQUE(tenant_id,slug));
 CREATE TABLE help_article_reads(user_id INTEGER,article_id INTEGER,viewed_at TEXT,PRIMARY KEY(user_id,article_id));
 INSERT INTO tenants VALUES(1),(2);INSERT INTO organizational_units VALUES(10,1,'CONVENCAO','Convenção A','ATIVO',NULL),(20,1,'MATRIZ','Matriz A','ATIVO',NULL),(30,1,'FILIAL','Filial A','ATIVO',NULL),(110,2,'CONVENCAO','Convenção B','ATIVO',NULL);INSERT INTO auth_users VALUES(1,'ATIVO',NULL),(2,'ATIVO',NULL);INSERT INTO tenant_memberships VALUES(1,1,1,'Admin A','Administrador da Convenção','CONVENCAO',10,'ATIVO',NULL),(2,2,2,'Admin B','Administrador da Convenção','CONVENCAO',110,'ATIVO',NULL);INSERT INTO people VALUES(1001,1,'Pessoa A',1),(2001,2,'Pessoa B',2);INSERT INTO platform_owners VALUES(1,1);`);apply(db);return db;}
function department(db,id=5001,tenant=1,unit=20,convention=10,matrix=20){db.prepare("INSERT INTO departments(id,tenant_id,name,type,unit_id,convention_id,matrix_id,status,enabled_features,absence_alert_threshold,created_by_user_id,created_at,updated_at) VALUES(?,?,?,'ESCOLA_BIBLICA',?,?,?,'ATIVO','[\"EBD\"]',3,1,'2026-08-11','2026-08-11')").run(id,tenant,`EBD ${id}`,unit,convention,matrix);}
test("0019 cria todas as estruturas e artigos de ajuda",()=>{const db=fixture();for(const table of ["departments","department_roles","department_participants","department_access","department_events","department_activities","department_attendance","department_communications","ebd_classes","ebd_class_teachers","ebd_enrollments","ebd_meetings","ebd_attendance","ebd_visitors","ebd_class_summaries","ebd_closures","department_audit"])assert.ok(db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").get(table),table);assert.equal(db.prepare("SELECT COUNT(*) total FROM help_articles WHERE version='28'").get().total,8);assert.equal(db.prepare("SELECT COUNT(*) total FROM membership_permissions WHERE membership_id=1 AND permission LIKE 'EBD_%'").get().total,11);});
test("FK composta bloqueia pessoa e acesso de outro tenant",()=>{const db=fixture();department(db);assert.throws(()=>db.prepare("INSERT INTO department_participants(department_id,tenant_id,person_id,joined_at,status,created_at,updated_at) VALUES(5001,1,2001,'2026-08-11','ATIVO','2026-08-11','2026-08-11')").run());assert.throws(()=>db.prepare("INSERT INTO department_access(department_id,tenant_id,membership_id,permissions_json,status,created_at,updated_at) VALUES(5001,1,2,'[]','ATIVO','2026-08-11','2026-08-11')").run());});
test("troca de classe preserva histórico e impede duas matrículas ativas",()=>{const db=fixture();department(db);db.exec("INSERT INTO ebd_classes VALUES(6001,1,5001,'Primários',NULL,NULL,NULL,'ATIVO','2026-08-11','2026-08-11');INSERT INTO ebd_classes VALUES(6002,1,5001,'Juniores',NULL,NULL,NULL,'ATIVO','2026-08-11','2026-08-11');INSERT INTO ebd_enrollments VALUES(7001,1,5001,6001,1001,'2026-08-11','ATIVO',NULL,NULL,'2026-08-11','2026-08-11')");assert.throws(()=>db.exec("INSERT INTO ebd_enrollments VALUES(7002,1,5001,6002,1001,'2026-08-11','ATIVO',NULL,NULL,'2026-08-11','2026-08-11')"));db.exec("UPDATE ebd_enrollments SET status='TRANSFERIDO',left_at='2026-08-12' WHERE id=7001;INSERT INTO ebd_enrollments VALUES(7002,1,5001,6002,1001,'2026-08-12','ATIVO',NULL,NULL,'2026-08-12','2026-08-12')");assert.equal(db.prepare("SELECT COUNT(*) total FROM ebd_enrollments WHERE person_id=1001").get().total,2);});
test("fechamento soma classes sem cálculo manual",()=>{const db=fixture();department(db);db.exec("INSERT INTO ebd_classes VALUES(6001,1,5001,'Primários',NULL,NULL,NULL,'ATIVO','2026-08-11','2026-08-11');INSERT INTO ebd_classes VALUES(6002,1,5001,'Adultos',NULL,NULL,NULL,'ATIVO','2026-08-11','2026-08-11');INSERT INTO ebd_meetings VALUES(8001,1,5001,'2026-08-16',NULL,NULL,'ABERTO',1,1,NULL,NULL,'2026-08-11','2026-08-11');INSERT INTO ebd_class_summaries VALUES(8001,6001,1,20,18,2,0,3,15,19,4200,NULL,'FINALIZADA',1,1,'2026-08-16','2026-08-16');INSERT INTO ebd_class_summaries VALUES(8001,6002,1,30,25,3,2,1,20,27,8000,NULL,'FINALIZADA',1,1,'2026-08-16','2026-08-16')");const totals=db.prepare("SELECT SUM(enrolled_count) enrolled,SUM(present_count) present,SUM(visitor_count) visitors,SUM(offering_cents) offering FROM ebd_class_summaries WHERE meeting_id=8001 AND status='FINALIZADA'").get();assert.deepEqual({...totals},{enrolled:50,present:43,visitors:4,offering:12200});});
test("índices suportam milhares de frequências históricas",()=>{const db=fixture();department(db);db.exec("INSERT INTO ebd_classes VALUES(6001,1,5001,'Adultos',NULL,NULL,NULL,'ATIVO','2026-08-11','2026-08-11')");const meeting=db.prepare("INSERT INTO ebd_meetings VALUES(?,1,5001,?,NULL,NULL,'FINALIZADO',1,1,1,?,'2026-08-11','2026-08-11')"),attendance=db.prepare("INSERT INTO ebd_attendance VALUES(?,6001,1,1001,'PRESENTE',1,'2026-08-11')");db.exec("BEGIN");for(let i=1;i<=1000;i++){const meetingDate=new Date(Date.UTC(2020,0,i)).toISOString().slice(0,10);meeting.run(9000+i,meetingDate,'2026-08-11');attendance.run(9000+i);}db.exec("COMMIT");assert.equal(db.prepare("SELECT COUNT(*) total FROM ebd_attendance WHERE tenant_id=1 AND person_id=1001").get().total,1000);const indexes=db.prepare("PRAGMA index_list('ebd_attendance')").all().map(row=>row.name);assert.ok(indexes.includes("ebd_attendance_person_history_idx"));});
