import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { DatabaseSync } from "node:sqlite";

function apply(db,name){for(const sql of readFileSync(new URL(`../drizzle/${name}.sql`,import.meta.url),"utf8").split("--> statement-breakpoint").map(value=>value.trim()).filter(Boolean))db.exec(sql);}

function fixture(){const db=new DatabaseSync(":memory:");db.exec(`PRAGMA foreign_keys=ON;
CREATE TABLE tenants(id INTEGER PRIMARY KEY);
CREATE TABLE organizational_units(id INTEGER PRIMARY KEY,tenant_id INTEGER,type TEXT,name TEXT,parent_id INTEGER,status TEXT,archived_at TEXT,UNIQUE(id,tenant_id));
CREATE TABLE organizational_functions(id INTEGER PRIMARY KEY,tenant_id INTEGER,name TEXT,status TEXT,UNIQUE(id,tenant_id));
CREATE TABLE auth_users(id INTEGER PRIMARY KEY,status TEXT,archived_at TEXT);
CREATE TABLE tenant_memberships(id INTEGER PRIMARY KEY,user_id INTEGER,tenant_id INTEGER,display_name TEXT,role_name TEXT,scope TEXT,scope_unit_id INTEGER,status TEXT,archived_at TEXT,UNIQUE(id,tenant_id));
CREATE TABLE membership_permissions(membership_id INTEGER,permission TEXT,created_at TEXT,PRIMARY KEY(membership_id,permission));
CREATE TABLE user_permissions(user_id INTEGER,permission TEXT,created_at TEXT,PRIMARY KEY(user_id,permission));
CREATE TABLE platform_owners(singleton_id INTEGER PRIMARY KEY,user_id INTEGER);
CREATE TABLE people(id INTEGER PRIMARY KEY,tenant_id INTEGER,full_name TEXT,birth_date TEXT,sex TEXT,cpf TEXT,phone TEXT,whatsapp TEXT,linked_auth_user_id INTEGER,UNIQUE(id,tenant_id));
CREATE TABLE help_articles(id INTEGER PRIMARY KEY,tenant_id INTEGER,slug TEXT,title TEXT,summary TEXT,content TEXT,category TEXT,display_order INTEGER,target_profiles TEXT,required_permission TEXT,related_route TEXT,published INTEGER,is_new_feature INTEGER,released_at TEXT,version TEXT,created_by_user_id INTEGER,published_at TEXT,created_at TEXT,updated_at TEXT,UNIQUE(tenant_id,slug));
CREATE TABLE help_article_reads(user_id INTEGER,article_id INTEGER,viewed_at TEXT,PRIMARY KEY(user_id,article_id));
INSERT INTO tenants VALUES(1),(2),(1770000000000000);
INSERT INTO organizational_units VALUES(10,1,'CONVENCAO','Convenção A',NULL,'ATIVO',NULL),(20,1,'MATRIZ','Matriz A',10,'ATIVO',NULL),(30,1,'FILIAL','Filial A',20,'ATIVO',NULL),(110,2,'CONVENCAO','Convenção B',NULL,'ATIVO',NULL),(120,2,'MATRIZ','Matriz B',110,'ATIVO',NULL);
INSERT INTO organizational_functions VALUES(80,1,'Pastor','ATIVO'),(180,2,'Pastor','ATIVO');
INSERT INTO auth_users VALUES(1,'ATIVO',NULL),(2,'ATIVO',NULL),(3,'ATIVO',NULL),(4,'ATIVO',NULL);
INSERT INTO tenant_memberships VALUES(1,1,1,'Admin Convenção','Administrador da Convenção','CONVENCAO',10,'ATIVO',NULL),(2,2,2,'Admin B','Administrador da Convenção','CONVENCAO',110,'ATIVO',NULL),(3,3,1,'Admin Matriz','Administrador da Matriz','MATRIZ',20,'ATIVO',NULL),(4,4,1,'Financeiro Filial','Financeiro','FILIAL',30,'ATIVO',NULL);
INSERT INTO people VALUES(1001,1,'Pessoa A','1990-01-01','FEMININO','11111111111','1111','1111',1),(2001,2,'Pessoa B',NULL,NULL,NULL,NULL,NULL,2);
INSERT INTO platform_owners VALUES(1,1);`);apply(db,"0019_departments_ebd");apply(db,"0022_finance_core");apply(db,"0023_finance_periods_and_quick_entry");return db;}

test("0023 instala períodos, sessões, permissões restritas e guias",()=>{const db=fixture();for(const table of ["finance_allocation_configs","finance_allocation_rules","finance_periods","finance_period_allocation_rules","finance_period_reopenings","finance_closure_versions","finance_quick_sessions"])assert.ok(db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").get(table),table);assert.equal(db.prepare("SELECT COUNT(*) total FROM help_articles WHERE version='34'").get().total,11);assert.equal(db.prepare("SELECT COUNT(*) total FROM membership_permissions WHERE membership_id=3 AND permission IN ('FINANCEIRO_CAIXA_ABRIR','FINANCEIRO_CAIXA_FECHAR','FINANCEIRO_CAIXA_REABRIR','FINANCEIRO_RATEIO_VISUALIZAR','FINANCEIRO_RATEIO_CONFIGURAR','FINANCEIRO_RATEIO_PERIODO_ALTERAR','FINANCEIRO_LANCAMENTO_RAPIDO')").get().total,7);assert.equal(db.prepare("SELECT COUNT(*) total FROM membership_permissions WHERE membership_id=4 AND permission LIKE 'FINANCEIRO_RATEIO_%'").get().total,0);assert.equal(db.prepare("SELECT COUNT(*) total FROM user_permissions WHERE user_id=1 AND permission='FINANCEIRO_CAIXA_REABRIR'").get().total,0);const columns=db.prepare("PRAGMA table_info(finance_movements)").all().map(row=>row.name);assert.ok(columns.includes("period_id"));assert.ok(columns.includes("quick_session_id"));});

test("cada unidade mantém configuração própria e o snapshot mensal não muda",()=>{const db=fixture();db.exec(`INSERT INTO finance_allocation_configs(id,tenant_id,unit_id,version,status,created_by_user_id,updated_by_user_id,created_at,updated_at) VALUES(501,1,20,1,'ATIVA',3,3,'2026-08-01','2026-08-01'),(502,1,30,1,'ATIVA',3,3,'2026-08-01','2026-08-01');
INSERT INTO finance_allocation_rules(id,tenant_id,config_id,recipient_name,recipient_type,rule_type,percentage_basis_points,calculation_base,display_order,active,created_at,updated_at) VALUES(601,1,501,'Matriz','MATRIZ','PERCENTUAL',6000,'RECEITAS_PARTICIPANTES',1,1,'2026-08-01','2026-08-01'),(602,1,501,'Convenção','CONVENCAO','PERCENTUAL',4000,'RECEITAS_PARTICIPANTES',2,1,'2026-08-01','2026-08-01'),(603,1,502,'Filial','IGREJA','PERCENTUAL',7000,'RECEITAS_PARTICIPANTES',1,1,'2026-08-01','2026-08-01'),(604,1,502,'Missões','MISSOES','PERCENTUAL',3000,'RECEITAS_PARTICIPANTES',2,1,'2026-08-01','2026-08-01');
INSERT INTO finance_periods(id,tenant_id,unit_id,unit_type,matrix_id,competency,status,lifecycle_state,allocation_config_id,allocation_config_version,opened_at,opened_by_user_id,version,created_at,updated_at) VALUES(701,1,20,'MATRIZ',20,'2026-08','ABERTO','ABERTO',501,1,'2026-08-01',3,1,'2026-08-01','2026-08-01');
INSERT INTO finance_period_allocation_rules(id,tenant_id,period_id,source_rule_id,recipient_name,recipient_type,rule_type,percentage_basis_points,calculation_base,participating_category_ids_json,display_order,snapshot_version,created_at) SELECT id+1000,tenant_id,701,id,recipient_name,recipient_type,rule_type,percentage_basis_points,calculation_base,'[]',display_order,1,'2026-08-01' FROM finance_allocation_rules WHERE config_id=501;
UPDATE finance_allocation_rules SET percentage_basis_points=5000 WHERE id=601;`);assert.equal(db.prepare("SELECT percentage_basis_points value FROM finance_period_allocation_rules WHERE period_id=701 AND source_rule_id=601").get().value,6000);assert.equal(db.prepare("SELECT percentage_basis_points value FROM finance_allocation_rules WHERE id=601").get().value,5000);assert.equal(db.prepare("SELECT COUNT(*) total FROM finance_allocation_configs WHERE tenant_id=1").get().total,2);assert.throws(()=>db.exec("INSERT INTO finance_periods(id,tenant_id,unit_id,unit_type,matrix_id,competency,status,lifecycle_state,allocation_config_id,allocation_config_version,opened_at,opened_by_user_id,version,created_at,updated_at) VALUES(702,1,20,'MATRIZ',20,'2026-08','ABERTO','ABERTO',501,1,'2026-08-01',3,1,'2026-08-01','2026-08-01')"));});

test("fechamentos preservam versões, escopo e índices operacionais",()=>{const db=fixture();db.exec(`INSERT INTO finance_allocation_configs(id,tenant_id,unit_id,version,status,created_by_user_id,updated_by_user_id,created_at,updated_at) VALUES(501,1,20,1,'ATIVA',3,3,'2026-08-01','2026-08-01');
INSERT INTO finance_periods(id,tenant_id,unit_id,unit_type,matrix_id,competency,status,lifecycle_state,allocation_config_id,allocation_config_version,opened_at,opened_by_user_id,version,created_at,updated_at) VALUES(701,1,20,'MATRIZ',20,'2026-08','FECHADO','FECHADO',501,1,'2026-08-01',3,3,'2026-08-01','2026-08-01');
INSERT INTO finance_closure_versions(id,tenant_id,period_id,version,total_entries_cents,total_expenses_cents,restricted_resources_cents,balance_cents,movement_count,rules_snapshot_json,totals_snapshot_json,closed_by_user_id,closed_at) VALUES(801,1,701,1,10000,1000,0,9000,2,'[]','{}',3,'2026-08-10'),(802,1,701,2,12000,1000,0,11000,3,'[]','{}',3,'2026-08-11');`);assert.deepEqual(db.prepare("SELECT version FROM finance_closure_versions WHERE period_id=701 ORDER BY version").all().map(row=>row.version),[1,2]);assert.throws(()=>db.exec("INSERT INTO finance_periods(id,tenant_id,unit_id,unit_type,matrix_id,competency,status,lifecycle_state,allocation_config_id,allocation_config_version,opened_at,opened_by_user_id,version,created_at,updated_at) VALUES(703,1,120,'MATRIZ',120,'2026-08','ABERTO','ABERTO',501,1,'2026-08-01',3,1,'2026-08-01','2026-08-01')"));for(const index of ["finance_periods_unit_status_idx","finance_movements_period_idx","finance_quick_sessions_resume_idx"])assert.ok(db.prepare("SELECT name FROM sqlite_master WHERE type='index' AND name=?").get(index),index);});
