import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { DatabaseSync } from "node:sqlite";

function apply(db,name){for(const sql of readFileSync(new URL(`../drizzle/${name}.sql`,import.meta.url),"utf8").split("--> statement-breakpoint").map(value=>value.trim()).filter(Boolean))db.exec(sql);}
function fixture(){const db=new DatabaseSync(":memory:");db.exec(`PRAGMA foreign_keys=ON;
CREATE TABLE tenants(id INTEGER PRIMARY KEY);
CREATE TABLE organizational_units(id INTEGER PRIMARY KEY,tenant_id INTEGER,type TEXT,name TEXT,parent_id INTEGER,status TEXT,archived_at TEXT,UNIQUE(id,tenant_id));
CREATE TABLE organizational_functions(id INTEGER PRIMARY KEY,tenant_id INTEGER,name TEXT,status TEXT,UNIQUE(id,tenant_id));
CREATE TABLE auth_users(id INTEGER PRIMARY KEY,status TEXT,archived_at TEXT);
CREATE TABLE tenant_memberships(id INTEGER PRIMARY KEY,user_id INTEGER,tenant_id INTEGER,display_name TEXT,role_name TEXT,scope TEXT,scope_unit_id INTEGER,status TEXT,archived_at TEXT,UNIQUE(id,tenant_id));
CREATE TABLE membership_permissions(membership_id INTEGER,permission TEXT,created_at TEXT,PRIMARY KEY(membership_id,permission));
CREATE TABLE user_permissions(user_id INTEGER,permission TEXT,created_at TEXT,PRIMARY KEY(user_id,permission));
CREATE TABLE platform_owners(singleton_id INTEGER PRIMARY KEY,user_id INTEGER);
CREATE TABLE people(id INTEGER PRIMARY KEY,tenant_id INTEGER,full_name TEXT,birth_date TEXT,sex TEXT,cpf TEXT,phone TEXT,whatsapp TEXT,linked_auth_user_id INTEGER,UNIQUE(id,tenant_id));
CREATE TABLE help_articles(id INTEGER PRIMARY KEY,tenant_id INTEGER,slug TEXT,title TEXT,summary TEXT,content TEXT,category TEXT,display_order INTEGER,target_profiles TEXT,required_permission TEXT,related_route TEXT,published INTEGER,is_new_feature INTEGER,released_at TEXT,version TEXT,created_by_user_id INTEGER,published_at TEXT,created_at TEXT,updated_at TEXT,UNIQUE(tenant_id,slug));
CREATE TABLE help_article_reads(user_id INTEGER,article_id INTEGER,viewed_at TEXT,PRIMARY KEY(user_id,article_id));
INSERT INTO tenants VALUES(1),(2);INSERT INTO organizational_units VALUES(10,1,'CONVENCAO','Convenção A',NULL,'ATIVO',NULL),(20,1,'MATRIZ','Matriz A',10,'ATIVO',NULL),(30,1,'FILIAL','Filial A',20,'ATIVO',NULL),(31,1,'FILIAL','Filial B',20,'ATIVO',NULL),(110,2,'CONVENCAO','Convenção B',NULL,'ATIVO',NULL),(120,2,'MATRIZ','Matriz B',110,'ATIVO',NULL);INSERT INTO organizational_functions VALUES(80,1,'Pastor','ATIVO'),(180,2,'Pastor','ATIVO');INSERT INTO auth_users VALUES(1,'ATIVO',NULL),(2,'ATIVO',NULL);INSERT INTO tenant_memberships VALUES(1,1,1,'Admin A','Administrador da Convenção','CONVENCAO',10,'ATIVO',NULL),(2,2,2,'Admin B','Administrador da Convenção','CONVENCAO',110,'ATIVO',NULL);INSERT INTO people VALUES(1001,1,'Pessoa A','1990-01-01','FEMININO','11111111111','1111','1111',1),(1002,1,'Pessoa B',NULL,NULL,NULL,NULL,NULL,NULL),(2001,2,'Pessoa Outro Tenant',NULL,NULL,NULL,NULL,NULL,2);INSERT INTO platform_owners VALUES(1,1);`);apply(db,"0019_departments_ebd");apply(db,"0020_ebd_students_secretary");apply(db,"0024_member_scope_and_transfer_search");return db;}

test("0024 adiciona direção, limite de busca e artigos de ajuda",()=>{const db=fixture();const columns=db.prepare("PRAGMA table_info(secretary_requests)").all().map(row=>row.name);assert.ok(columns.includes("request_direction"));assert.ok(db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='secretary_transfer_search_limits'").get());assert.ok(db.prepare("SELECT name FROM sqlite_master WHERE type='index' AND name='secretary_requests_pending_destination_idx'").get());assert.equal(db.prepare("SELECT COUNT(*) total FROM help_articles WHERE version='35'").get().total,3);db.exec("INSERT INTO secretary_requests(id,tenant_id,person_id,request_type,origin_unit_id,destination_unit_id,status,version,requested_by_user_id,requested_at,updated_at) VALUES(1,1,1001,'TRANSFERENCIA_INTERNA',20,30,'PENDENTE',1,1,'2026-08-12','2026-08-12')");assert.equal(db.prepare("SELECT request_direction direction FROM secretary_requests WHERE id=1").get().direction,"SAIDA");assert.throws(()=>db.exec("INSERT INTO secretary_requests(id,tenant_id,person_id,request_type,request_direction,status,version,requested_by_user_id,requested_at,updated_at) VALUES(2,1,1002,'TRANSFERENCIA_INTERNA','INVALIDA','PENDENTE',1,1,'2026-08-12','2026-08-12')"));});

test("limite de pesquisa e solicitações permanecem isolados por tenant",()=>{const db=fixture();db.exec("INSERT INTO secretary_transfer_search_limits VALUES(1,1,1,'2026-08-12','2026-08-12')");assert.throws(()=>db.exec("INSERT INTO secretary_transfer_search_limits VALUES(2,999,1,'2026-08-12','2026-08-12')"));assert.throws(()=>db.exec("INSERT INTO secretary_requests(id,tenant_id,person_id,request_type,request_direction,origin_unit_id,destination_unit_id,status,version,requested_by_user_id,requested_at,updated_at) VALUES(3,1,2001,'TRANSFERENCIA_INTERNA','RECEBIMENTO',120,30,'PENDENTE',1,1,'2026-08-12','2026-08-12')"));});

test("inserção condicional bloqueia duplo clique e conflito pendente",()=>{const db=fixture();db.exec("INSERT INTO secretary_requests(id,tenant_id,person_id,request_type,request_direction,origin_unit_id,destination_unit_id,status,version,requested_by_user_id,requested_at,updated_at) VALUES(4,1,1001,'TRANSFERENCIA_INTERNA','RECEBIMENTO',20,30,'PENDENTE',1,1,'2026-08-12','2026-08-12')");const result=db.prepare("INSERT INTO secretary_requests(id,tenant_id,person_id,request_type,request_direction,origin_unit_id,destination_unit_id,reason,notes,status,department_resolution,ebd_resolution,requested_by_user_id,requested_at,updated_at) SELECT ?,?,?,'TRANSFERENCIA_INTERNA',?,?,?,?,?,'PENDENTE',?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM secretary_requests WHERE tenant_id=? AND person_id=? AND status IN ('PENDENTE','EM_ANALISE'))").run(5,1,1001,"RECEBIMENTO",20,30,null,null,"REVISAR","REVISAR",1,"2026-08-12","2026-08-12",1,1001);assert.equal(result.changes,0);assert.equal(db.prepare("SELECT COUNT(*) total FROM secretary_requests WHERE tenant_id=1 AND person_id=1001 AND status='PENDENTE'").get().total,1);});
