import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { DatabaseSync } from "node:sqlite";
function apply(d,file){for(const sql of readFileSync(new URL(file,import.meta.url),"utf8").split("--> statement-breakpoint").map(x=>x.trim()).filter(Boolean))d.exec(sql);}
function fixture(){const d=new DatabaseSync(":memory:");d.exec("PRAGMA foreign_keys=ON;CREATE TABLE tenants(id INTEGER PRIMARY KEY);CREATE TABLE organizational_units(id INTEGER PRIMARY KEY,tenant_id INTEGER NOT NULL,type TEXT NOT NULL,parent_id INTEGER,archived_at TEXT);CREATE TABLE organizational_functions(id INTEGER PRIMARY KEY,tenant_id INTEGER NOT NULL);CREATE TABLE auth_users(id INTEGER PRIMARY KEY);CREATE TABLE tenant_memberships(id INTEGER PRIMARY KEY,scope TEXT NOT NULL,status TEXT NOT NULL,archived_at TEXT);CREATE TABLE membership_permissions(membership_id INTEGER NOT NULL,permission TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(membership_id,permission));CREATE TABLE user_permissions(user_id INTEGER NOT NULL,permission TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(user_id,permission));CREATE TABLE platform_owners(singleton_id INTEGER PRIMARY KEY,user_id INTEGER NOT NULL);INSERT INTO tenants VALUES(1),(2);INSERT INTO organizational_units VALUES(10,1,'MATRIZ',1,NULL),(20,1,'FILIAL',10,NULL),(11,2,'MATRIZ',2,NULL),(21,2,'FILIAL',11,NULL);INSERT INTO organizational_functions VALUES(30,1),(31,2);INSERT INTO auth_users VALUES(1);INSERT INTO tenant_memberships VALUES(1,'CONVENCAO','ATIVO',NULL);INSERT INTO platform_owners VALUES(1,1);");apply(d,"../drizzle/0015_people_members.sql");apply(d,"../drizzle/0016_member_extensions.sql");return d;}
const person=(id,tenant,unit,branch)=>`INSERT INTO people(id,tenant_id,member_number,full_name,status,children_count,matrix_id,branch_id,created_by_user_id,created_at,updated_at) VALUES(${id},${tenant},${id},'Pessoa','MEMBRO_ATIVO',0,${unit},${branch??"NULL"},1,'x','x')`;
test("0016 cria título, campos dinâmicos e pré-cadastros",()=>{const d=fixture();assert.ok(d.prepare("SELECT voter_title FROM people").all());for(const table of ["member_custom_fields","member_custom_values","member_pre_registration_forms","member_pre_registrations","member_pre_registration_photos"])assert.ok(d.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(table));assert.equal(d.prepare("SELECT COUNT(*) n FROM membership_permissions WHERE permission LIKE 'PRECADASTROS_%'").get().n,4);});
test("campos e formulários permanecem isolados por tenant",()=>{const d=fixture();d.exec(person(100,1,10,20));d.exec("INSERT INTO member_custom_fields(id,tenant_id,name,normalized_name,field_type,required,status,display_order,section_name,show_admin,show_public,show_print,created_by_user_id,created_at,updated_at) VALUES(50,1,'Uniforme','uniforme','TEXTO_CURTO',0,'ATIVO',0,'Extra',1,1,1,1,'x','x')");assert.throws(()=>d.exec("INSERT INTO member_custom_values VALUES(100,1,999,'x',1,'x','x')"),/FOREIGN KEY/);assert.throws(()=>d.exec("INSERT INTO member_custom_values VALUES(100,2,50,'x',1,'x','x')"),/FOREIGN KEY/);});
test("envio público nasce pendente e não cria membro",()=>{const d=fixture();d.exec("INSERT INTO member_pre_registration_forms(id,tenant_id,name,token_hash,token_prefix,unit_id,status,created_by_user_id,created_at,updated_at) VALUES(60,1,'Ficha','hash-seguro','prefixo',20,'ATIVO',1,'x','x');INSERT INTO member_pre_registrations(id,tenant_id,form_id,full_name,matrix_id,branch_id,payload_json,consent_at,consent_version,source_hash,created_at,updated_at) VALUES(70,1,60,'Candidato',10,20,'{}','x','v1','origem','x','x')");assert.equal(d.prepare("SELECT status FROM member_pre_registrations WHERE id=70").get().status,"PENDENTE");assert.equal(d.prepare("SELECT COUNT(*) n FROM people").get().n,0);});
test("desativar campo preserva valores e rollback remove somente a extensão",()=>{const d=fixture();d.exec(person(100,1,10,20));d.exec("INSERT INTO member_custom_fields(id,tenant_id,name,normalized_name,field_type,required,status,display_order,section_name,show_admin,show_public,show_print,created_by_user_id,created_at,updated_at) VALUES(50,1,'Uniforme','uniforme','TEXTO_CURTO',0,'ATIVO',0,'Extra',1,1,1,1,'x','x');INSERT INTO member_custom_values VALUES(100,1,50,'Azul',1,'x','x');UPDATE member_custom_fields SET status='INATIVO' WHERE id=50");assert.equal(d.prepare("SELECT value_text FROM member_custom_values").get().value_text,"Azul");d.exec(readFileSync(new URL("../database/rollback/0016_member_extensions.down.sql",import.meta.url),"utf8"));assert.ok(d.prepare("SELECT 1 FROM people").get());assert.equal(d.prepare("SELECT 1 FROM sqlite_master WHERE name='member_custom_fields'").get(),undefined);});
