DROP TABLE IF EXISTS auditoria_administracao;
DROP TABLE IF EXISTS usuario_permissoes_diretas;

DELETE FROM permissoes
WHERE codigo IN (
  'USUARIOS_VISUALIZAR',
  'USUARIOS_CRIAR',
  'USUARIOS_EDITAR',
  'USUARIOS_DESATIVAR',
  'USUARIOS_REDEFINIR_SENHA',
  'UNIDADES_VISUALIZAR',
  'UNIDADES_CRIAR',
  'UNIDADES_EDITAR',
  'ACESSOS_VISUALIZAR'
);

ALTER TABLE auditoria_autenticacao DROP COLUMN ip_endereco;
