export type ExportRow=Record<string,unknown>;
export type ExportFileEntry={name:string;data:Uint8Array};
const encoder=new TextEncoder();
export const bytes=(value:string)=>encoder.encode(value);
export const safeJson=(value:unknown)=>JSON.stringify(value,null,2);
function csvValue(value:unknown){const text=value===null||value===undefined?"":typeof value==="object"?JSON.stringify(value):String(value);return `"${text.replaceAll('"','""')}"`;}
export function toCsv(rows:ExportRow[],headers:string[]){return `\uFEFF${headers.map(csvValue).join(";")}\r\n${rows.map(row=>headers.map(header=>csvValue(row[header])).join(";")).join("\r\n")}`;}
const crcTable=(()=>{const table=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;table[n]=c>>>0;}return table;})();
export function crc32(data:Uint8Array){let crc=0xffffffff;for(const b of data)crc=crcTable[(crc^b)&0xff]^(crc>>>8);return (crc^0xffffffff)>>>0;}
function u16(view:DataView,offset:number,value:number){view.setUint16(offset,value,true);}function u32(view:DataView,offset:number,value:number){view.setUint32(offset,value>>>0,true);}
function concat(parts:Uint8Array[]){const size=parts.reduce((sum,p)=>sum+p.length,0),out=new Uint8Array(size);let offset=0;for(const p of parts){out.set(p,offset);offset+=p.length;}return out;}
export function zipStore(entries:ExportFileEntry[]){const locals:Uint8Array[]=[],centrals:Uint8Array[]=[];let offset=0;for(const entry of entries){const name=bytes(entry.name),crc=crc32(entry.data),local=new Uint8Array(30+name.length),lv=new DataView(local.buffer);u32(lv,0,0x04034b50);u16(lv,4,20);u16(lv,6,0x800);u16(lv,8,0);u32(lv,14,crc);u32(lv,18,entry.data.length);u32(lv,22,entry.data.length);u16(lv,26,name.length);local.set(name,30);locals.push(local,entry.data);const central=new Uint8Array(46+name.length),cv=new DataView(central.buffer);u32(cv,0,0x02014b50);u16(cv,4,20);u16(cv,6,20);u16(cv,8,0x800);u16(cv,10,0);u32(cv,16,crc);u32(cv,20,entry.data.length);u32(cv,24,entry.data.length);u16(cv,28,name.length);u32(cv,38,0);u32(cv,42,offset);central.set(name,46);centrals.push(central);offset+=local.length+entry.data.length;}const central=concat(centrals),end=new Uint8Array(22),ev=new DataView(end.buffer);u32(ev,0,0x06054b50);u16(ev,8,entries.length);u16(ev,10,entries.length);u32(ev,12,central.length);u32(ev,16,offset);return concat([...locals,central,end]);}
function xml(value:unknown){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"}[c]!));}
function columnName(index:number){let name="";for(let n=index+1;n;n=Math.floor((n-1)/26))name=String.fromCharCode(65+((n-1)%26))+name;return name;}
export function xlsx(rows:ExportRow[],headers:string[]){const all=[headers,...rows.map(row=>headers.map(header=>row[header]))];const sheet=all.map((row,r)=>`<row r="${r+1}">${row.map((value,c)=>{const ref=`${columnName(c)}${r+1}`;if(typeof value==="number"&&Number.isFinite(value))return `<c r="${ref}"${r===0?' s="1"':''}><v>${value}</v></c>`;return `<c r="${ref}" t="inlineStr"${r===0?' s="1"':''}><is><t xml:space="preserve">${xml(typeof value==="object"?JSON.stringify(value):value)}</t></is></c>`;}).join("")}</row>`).join("");return zipStore([
  {name:"[Content_Types].xml",data:bytes('<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>')},
  {name:"_rels/.rels",data:bytes('<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>')},
  {name:"xl/workbook.xml",data:bytes('<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Membros" sheetId="1" r:id="rId1"/></sheets></workbook>')},
  {name:"xl/_rels/workbook.xml.rels",data:bytes('<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>')},
  {name:"xl/styles.xml",data:bytes('<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF087D72"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/></cellXfs></styleSheet>')},
  {name:"xl/worksheets/sheet1.xml",data:bytes(`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetFormatPr defaultRowHeight="15"/><sheetData>${sheet}</sheetData><autoFilter ref="A1:${columnName(Math.max(0,headers.length-1))}${Math.max(1,all.length)}"/></worksheet>`)},
]);}
