"use client";

import { AlertTriangle, Archive, Edit3, FolderKanban, Landmark, LoaderCircle, RotateCcw, Scale, Settings2, Tags, X } from "lucide-react";
import { useMemo, useState } from "react";
import { readApi, StatusBadge } from "@/components/admin/admin-ui";

type Row=Record<string,unknown>;
type Options={units:Row[];departments:Row[]};
type Entity="ACCOUNT"|"CATEGORY"|"PAYMENT_METHOD"|"COST_CENTER";
type ManagedResult={entity:Entity;record:Row;message:string};
type Editor={kind:"account"|"adjust"|"category"|"method"|"costCenter";row:Row}|null;

const money=(value:unknown)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(value||0)/100);
const moneyInput=(value:unknown)=>(Number(value||0)/100).toFixed(2).replace(".",",");
const label=(value:unknown)=>String(value??"").replaceAll("_"," ").toLocaleLowerCase("pt-BR").replace(/^./,letter=>letter.toUpperCase());
const today=()=>new Date().toISOString().slice(0,10);
function formCents(value:FormDataEntryValue|null){const cleaned=String(value||"").replace(/R\$|\s/g,"").replaceAll(".","").replace(",",".");const parsed=Number(cleaned);return Number.isFinite(parsed)?Math.round(parsed*100):Number.NaN;}
function selectedId(form:FormData,name:string){const value=Number(form.get(name));return Number.isInteger(value)&&value>0?value:null;}

function FilterBar({value,onChange,activeLabel="Ativas",archivedLabel="Arquivadas"}:{value:string;onChange:(value:string)=>void;activeLabel?:string;archivedLabel?:string}){
  return <div className="finance-registry-filter" role="group" aria-label="Filtrar por situação">{[["active",activeLabel],["archived",archivedLabel],["all","Todas"]].map(([key,text])=><button type="button" key={key} className={value===key?"active":""} onClick={()=>onChange(key)}>{text}</button>)}</div>;
}

function DialogShell({title,eyebrow="Financeiro",onClose,children}:{title:string;eyebrow?:string;onClose:()=>void;children:React.ReactNode}){
  return <div className="dialog-backdrop"><section className="dialog-card finance-dialog finance-registry-dialog" role="dialog" aria-modal="true"><header><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><button type="button" onClick={onClose} aria-label="Fechar"><X/></button></header>{children}</section></div>;
}

function AccountDialog({row,busy,onClose,onSave}:{row:Row;busy:boolean;onClose:()=>void;onSave:(body:Row)=>void}){
  const hasMovements=Number(row.movement_count||0)>0;
  return <DialogShell title="Editar conta" onClose={onClose}><form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);onSave({action:"ACCOUNT_UPDATE",id:row.id,name:form.get("name"),description:form.get("description"),accountType:form.get("accountType"),institution:form.get("institution"),agency:form.get("agency"),accountNumber:form.get("accountNumber"),pixKey:form.get("pixKey"),notes:form.get("notes"),initialBalanceCents:hasMovements?Number(row.initial_balance_cents):formCents(form.get("initialBalance")),initialBalanceDate:hasMovements?row.initial_balance_date:form.get("initialBalanceDate")});}}><div className="form-grid">
    <label className="field-group"><span>Nome</span><input name="name" defaultValue={String(row.name||"")} required maxLength={120}/></label>
    <label className="field-group"><span>Tipo</span><select name="accountType" defaultValue={String(row.account_type)} required><option value="CAIXA_FISICO">Caixa físico</option><option value="CONTA_CORRENTE">Conta corrente</option><option value="POUPANCA">Poupança</option><option value="PIX">PIX</option><option value="COFRE">Cofre</option><option value="CARTEIRA">Carteira</option><option value="OUTRO">Outro</option></select></label>
    <label className="field-group form-span-2"><span>Descrição</span><input name="description" defaultValue={String(row.description||"")} maxLength={300}/></label>
    <label className="field-group"><span>Instituição</span><input name="institution" defaultValue={String(row.institution||"")} maxLength={120}/></label>
    <label className="field-group"><span>Agência</span><input name="agency" defaultValue={String(row.agency||"")} maxLength={30}/></label>
    <label className="field-group"><span>Número da conta</span><input name="accountNumber" defaultValue={String(row.account_number||"")} maxLength={50}/></label>
    <label className="field-group"><span>Chave PIX</span><input name="pixKey" defaultValue={String(row.pix_key||"")} maxLength={160}/></label>
    <label className="field-group"><span>Saldo inicial</span><input name="initialBalance" inputMode="decimal" defaultValue={moneyInput(row.initial_balance_cents)} disabled={hasMovements} required/><small>{hasMovements?"Bloqueado porque a conta já possui movimentos. Use Ajustar saldo.":"Pode ser corrigido até o primeiro movimento."}</small></label>
    <label className="field-group"><span>Data do saldo inicial</span><input type="date" name="initialBalanceDate" defaultValue={String(row.initial_balance_date||today())} disabled={hasMovements} required/></label>
    <label className="field-group form-span-2"><span>Observações</span><textarea name="notes" defaultValue={String(row.notes||"")} rows={3} maxLength={800}/></label>
  </div><div className="dialog-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Edit3/>}{busy?"Salvando...":"Salvar alterações"}</button></div></form></DialogShell>;
}

function AdjustmentDialog({row,busy,onClose,onSave}:{row:Row;busy:boolean;onClose:()=>void;onSave:(body:Row)=>void}){
  const [correct,setCorrect]=useState(moneyInput(row.balance_cents));const parsed=formCents(correct),difference=Number.isFinite(parsed)?parsed-Number(row.balance_cents):0;
  return <DialogShell title="Ajustar saldo" eyebrow="Correção auditável" onClose={onClose}><div className="finance-adjustment-summary"><span>Saldo calculado<strong>{money(row.balance_cents)}</strong></span><span>Diferença do ajuste<strong className={difference<0?"finance-negative":"finance-positive"}>{difference?`${difference<0?"− ":"+ "}${money(Math.abs(difference))}`:"Sem diferença"}</strong></span></div><form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);onSave({action:"ACCOUNT_ADJUST",id:row.id,correctBalanceCents:formCents(form.get("correctBalance")),occurredOn:form.get("occurredOn"),reason:form.get("reason")});}}><div className="form-grid">
    <label className="field-group"><span>Saldo correto</span><input name="correctBalance" inputMode="decimal" value={correct} onChange={event=>setCorrect(event.target.value)} required/></label>
    <label className="field-group"><span>Data do ajuste</span><input type="date" name="occurredOn" defaultValue={today()} required/></label>
    <label className="field-group form-span-2"><span>Motivo obrigatório</span><textarea name="reason" rows={4} minLength={5} maxLength={500} placeholder="Explique a diferença encontrada..." required/></label>
  </div><p className="finance-audit-note"><Scale size={18}/>O saldo atual não será sobrescrito. O sistema criará um movimento de ajuste e preservará o histórico anterior.</p><div className="dialog-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={busy||!difference}>{busy?<LoaderCircle className="spin"/>:<Scale/>}{busy?"Registrando...":"Registrar ajuste"}</button></div></form></DialogShell>;
}

function CategoryDialog({row,busy,onClose,onSave}:{row:Row;busy:boolean;onClose:()=>void;onSave:(body:Row)=>void}){
  return <DialogShell title="Editar categoria" onClose={onClose}><form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);onSave({action:"CATEGORY_UPDATE",id:row.id,name:form.get("name"),description:form.get("description"),kind:form.get("kind"),participatesAllocation:form.get("participatesAllocation")==="on",requiresFund:form.get("requiresFund")==="on"});}}><div className="form-grid">
    <label className="field-group"><span>Nome</span><input name="name" defaultValue={String(row.name||"")} required maxLength={120}/></label>
    <label className="field-group"><span>Natureza</span><select name="kind" defaultValue={String(row.kind)} required><option value="RECEITA">Receita</option><option value="DESPESA">Despesa</option></select></label>
    <label className="field-group form-span-2"><span>Descrição</span><input name="description" defaultValue={String(row.description||"")} maxLength={300}/></label>
    <label className="finance-check"><input type="checkbox" name="participatesAllocation" defaultChecked={Boolean(row.participates_allocation)}/> Participa do rateio</label>
    <label className="finance-check"><input type="checkbox" name="requiresFund" defaultChecked={Boolean(row.requires_fund)}/> Exige fundo vinculado</label>
  </div><div className="dialog-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Edit3/>}{busy?"Salvando...":"Salvar alterações"}</button></div></form></DialogShell>;
}

function AuxiliaryDialog({kind,row,options,busy,onClose,onSave}:{kind:"method"|"costCenter";row:Row;options:Options;busy:boolean;onClose:()=>void;onSave:(body:Row)=>void}){
  const costCenter=kind==="costCenter";
  return <DialogShell title={costCenter?"Editar centro de custo":"Editar forma de pagamento"} onClose={onClose}><form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);onSave(costCenter?{action:"COST_CENTER_UPDATE",id:row.id,name:form.get("name"),description:form.get("description"),centerType:form.get("centerType"),departmentId:selectedId(form,"departmentId")}:{action:"PAYMENT_METHOD_UPDATE",id:row.id,name:form.get("name"),description:form.get("description")});}}><div className="form-grid">
    <label className="field-group"><span>Nome</span><input name="name" defaultValue={String(row.name||"")} required maxLength={costCenter?120:80}/></label>
    {costCenter?<label className="field-group"><span>Tipo</span><select name="centerType" defaultValue={String(row.center_type)}><option value="DEPARTAMENTO">Departamento</option><option value="MINISTERIO">Ministério</option><option value="EBD">EBD</option><option value="SECRETARIA">Secretaria</option><option value="OUTRO">Outro</option></select></label>:null}
    <label className="field-group form-span-2"><span>Descrição</span><input name="description" defaultValue={String(row.description||"")} maxLength={300}/></label>
    {costCenter?<label className="field-group form-span-2"><span>Departamento vinculado</span><select name="departmentId" defaultValue={String(row.department_id||"")}><option value="">Nenhum</option>{options.departments.map(item=><option key={String(item.id)} value={String(item.id)}>{String(item.name)}</option>)}</select></label>:null}
  </div><div className="dialog-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Edit3/>}{busy?"Salvando...":"Salvar alterações"}</button></div></form></DialogShell>;
}

export function FinanceRegistrySections({section,accounts,categories,paymentMethods,costCenters,options,canManage,onChanged,onError}:{section:"accounts"|"categories"|"settings";accounts:Row[];categories:Row[];paymentMethods:Row[];costCenters:Row[];options:Options;canManage:boolean;onChanged:(entity:Entity,record:Row,message:string)=>void;onError:(message:string)=>void}){
  const [accountFilter,setAccountFilter]=useState("active"),[categoryFilter,setCategoryFilter]=useState("active"),[methodFilter,setMethodFilter]=useState("active"),[centerFilter,setCenterFilter]=useState("active"),[editor,setEditor]=useState<Editor>(null),[busy,setBusy]=useState(false);
  const accountRows=useMemo(()=>accounts.filter(row=>accountFilter==="all"||(accountFilter==="active"?row.status==="ATIVA":row.status!=="ATIVA")),[accounts,accountFilter]);
  const categoryRows=useMemo(()=>categories.filter(row=>categoryFilter==="all"||(categoryFilter==="active"?row.status==="ATIVA":row.status!=="ATIVA")),[categories,categoryFilter]);
  const methodRows=useMemo(()=>paymentMethods.filter(row=>methodFilter==="all"||(methodFilter==="active"?row.status==="ATIVO":row.status!=="ATIVO")),[paymentMethods,methodFilter]);
  const centerRows=useMemo(()=>costCenters.filter(row=>centerFilter==="all"||(centerFilter==="active"?row.status==="ATIVO":row.status!=="ATIVO")),[costCenters,centerFilter]);
  async function manage(body:Row){setBusy(true);try{const response=await readApi<{result:ManagedResult}>(await fetch("/api/finance/manage",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}));onChanged(response.result.entity,response.result.record,response.result.message);setEditor(null);}catch(error){onError(error instanceof Error?error.message:"Não foi possível concluir a operação.");}finally{setBusy(false);}}
  async function toggle(entity:Entity,row:Row,active:boolean){const noun=entity==="ACCOUNT"?"conta":entity==="CATEGORY"?"categoria":entity==="PAYMENT_METHOD"?"forma de pagamento":"centro de custo";if(!active&&!window.confirm(`Arquivar esta ${noun}? O histórico será preservado e ela sairá dos novos lançamentos.`))return;const action=`${entity}_${active?"RESTORE":"ARCHIVE"}`;await manage({action,id:row.id});}

  if(section==="accounts")return <><section className="content-card finance-section"><div className="finance-section-head finance-registry-head"><div><h2>Contas financeiras</h2><p>Saldo atual calculado pelas movimentações, nunca digitado livremente.</p></div><FilterBar value={accountFilter} onChange={setAccountFilter}/></div><div className="finance-cards finance-registry-cards">{accountRows.length?accountRows.map(row=>{const negative=Number(row.balance_cents)<0,active=row.status==="ATIVA";return <article key={String(row.id)}><Landmark/><span><strong>{String(row.name)}</strong><small>{label(row.account_type)}{row.institution?` · ${String(row.institution)}`:""} · saldo inicial {money(row.initial_balance_cents)}</small>{negative?<em className="finance-negative-label"><AlertTriangle size={14}/>Saldo negativo</em>:null}</span><div className="finance-account-balance"><small>Saldo atual</small><b className={negative?"finance-negative":""}>{money(row.balance_cents)}</b></div><StatusBadge status={String(row.status)}/>{canManage?<div className="finance-row-actions"><button onClick={()=>setEditor({kind:"account",row})}><Edit3/>Editar</button>{Number(row.movement_count)>0?<button onClick={()=>setEditor({kind:"adjust",row})}><Scale/>Ajustar saldo</button>:null}<button className={active?"danger-action":"restore-action"} onClick={()=>void toggle("ACCOUNT",row,!active)}>{active?<Archive/>:<RotateCcw/>}{active?"Arquivar":"Reativar"}</button></div>:null}</article>}):<div className="finance-empty-inline">Nenhuma conta neste filtro.</div>}</div></section>{editor?.kind==="account"?<AccountDialog row={editor.row} busy={busy} onClose={()=>setEditor(null)} onSave={body=>void manage(body)}/>:null}{editor?.kind==="adjust"?<AdjustmentDialog row={editor.row} busy={busy} onClose={()=>setEditor(null)} onSave={body=>void manage(body)}/>:null}</>;

  if(section==="categories")return <><section className="content-card finance-section"><div className="finance-section-head finance-registry-head"><div><h2>Categorias financeiras</h2><p>O mesmo ID é preservado após edições e arquivamentos.</p></div><FilterBar value={categoryFilter} onChange={setCategoryFilter}/></div><div className="finance-cards finance-registry-cards">{categoryRows.length?categoryRows.map(row=>{const active=row.status==="ATIVA";return <article key={String(row.id)}><Tags/><span><strong>{String(row.name)}</strong><small>{label(row.kind)} · {row.participates_allocation?"participa do rateio":"fora do rateio"} · {row.requires_fund?"exige fundo":"fundo opcional"}</small>{row.description?<small>{String(row.description)}</small>:null}</span><StatusBadge status={String(row.status)}/>{canManage?<div className="finance-row-actions"><button onClick={()=>setEditor({kind:"category",row})}><Edit3/>Editar</button><button className={active?"danger-action":"restore-action"} onClick={()=>void toggle("CATEGORY",row,!active)}>{active?<Archive/>:<RotateCcw/>}{active?"Arquivar":"Reativar"}</button></div>:null}</article>}):<div className="finance-empty-inline">Nenhuma categoria neste filtro.</div>}</div></section>{editor?.kind==="category"?<CategoryDialog row={editor.row} busy={busy} onClose={()=>setEditor(null)} onSave={body=>void manage(body)}/>:null}</>;

  const auxiliary=(title:string,icon:React.ReactNode,rows:Row[],filter:string,setFilter:(value:string)=>void,entity:Entity,kind:"method"|"costCenter")=><section className="content-card finance-section"><div className="finance-section-head finance-registry-head"><div className="finance-aux-title">{icon}<div><h2>{title}</h2><p>Edite ou arquive sem remover referências antigas.</p></div></div><FilterBar value={filter} onChange={setFilter} activeLabel="Ativos" archivedLabel="Arquivados"/></div><div className="finance-cards finance-registry-cards">{rows.length?rows.map(row=>{const active=row.status==="ATIVO";return <article key={String(row.id)}>{kind==="method"?<Settings2/>:<FolderKanban/>}<span><strong>{String(row.name)}</strong><small>{kind==="costCenter"?label(row.center_type):String(row.description||"Disponível para novos lançamentos")}</small></span><StatusBadge status={String(row.status)}/>{canManage?<div className="finance-row-actions"><button onClick={()=>setEditor({kind,row})}><Edit3/>Editar</button><button className={active?"danger-action":"restore-action"} onClick={()=>void toggle(entity,row,!active)}>{active?<Archive/>:<RotateCcw/>}{active?"Arquivar":"Reativar"}</button></div>:null}</article>}):<div className="finance-empty-inline">Nenhum cadastro neste filtro.</div>}</div></section>;
  return <><div className="finance-settings-stack">{auxiliary("Formas de pagamento",<Settings2/>,methodRows,methodFilter,setMethodFilter,"PAYMENT_METHOD","method")}{auxiliary("Centros de custo",<FolderKanban/>,centerRows,centerFilter,setCenterFilter,"COST_CENTER","costCenter")}</div>{editor&&(editor.kind==="method"||editor.kind==="costCenter")?<AuxiliaryDialog kind={editor.kind} row={editor.row} options={options} busy={busy} onClose={()=>setEditor(null)} onSave={body=>void manage(body)}/>:null}</>;
}
