"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, CheckCircle2, KeyRound, LoaderCircle, LockKeyhole, Plus, RefreshCw, Settings2, UnlockKeyhole, X, Zap } from "lucide-react";
import { readApi, StatusBadge, Toast } from "@/components/admin/admin-ui";
import { useWorkspace } from "@/components/protected-shell";

type Row = Record<string, unknown>;
type Options = { units: Row[]; destinationUnits?: Row[]; departments?: Row[] };
type Workspace = {
  unit: { id: number; name: string; type: string; matrixId: number };
  competency: string;
  competencySource: "OPEN_PERIOD" | "LATEST_PERIOD" | "PREVIOUS_MONTH";
  periods: Row[];
  config: ({ id: number; version: number; rules: Row[]; history?: Row[] }) | null;
  period: (Row & { rules: Row[]; ruleHistory?: Row[]; closures: Row[]; totals: Row | null; allocationPreview?: Row }) | null;
  sessions: Row[];
  reopenRequest: Row | null;
  pendingRequests: Row[];
  permissions: { canOpen: boolean; canClose: boolean; canReopen: boolean; canRequestReopen: boolean; canApproveReopen: boolean; canUseApprovedReopen: boolean; canConfigure: boolean; canAlterPeriod: boolean; canQuick: boolean };
};
type Rule = { recipientName: string; recipientType: string; ruleType: "PERCENTUAL" | "FIXO" | "RESTANTE"; financialDestination: "" | "REPASSAR" | "MANTER_NA_UNIDADE"; destinationUnitId: string; destinationDepartmentId: string; percentage: string; fixedAmount: string; description: string; active: boolean };

const previousMonth = () => { const current = new Date(), date = new Date(Date.UTC(current.getUTCFullYear(), current.getUTCMonth() - 1, 1)); return `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, "0")}`; };
const money = (value: unknown) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(value || 0) / 100);
const inputMoney = (value: unknown) => (Number(value || 0) / 100).toLocaleString("pt-BR", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const moneyCents = (value: string) => Math.round((Number(value.trim().replace(/^R\$\s*/i, "").replaceAll(".", "").replace(",", ".")) || 0) * 100);
const dateTime = (value: unknown) => value ? new Date(String(value)).toLocaleString("pt-BR") : "—";
const label = (value: unknown) => String(value ?? "").replaceAll("_", " ").toLocaleLowerCase("pt-BR").replace(/^./, (character) => character.toUpperCase());
const mapRules = (rows: Row[]): Rule[] => rows.map((row) => ({ recipientName: String(row.recipient_name || ""), recipientType: String(row.recipient_type || "OUTRO"), ruleType: String(row.rule_type || "PERCENTUAL") as Rule["ruleType"], financialDestination: String(row.financial_destination || "REPASSAR") as Rule["financialDestination"], destinationUnitId: row.destination_unit_id ? String(row.destination_unit_id) : "", destinationDepartmentId: row.destination_department_id ? String(row.destination_department_id) : "", percentage: (Number(row.percentage_basis_points || 0) / 100).toLocaleString("pt-BR", { maximumFractionDigits: 2 }), fixedAmount: inputMoney(row.fixed_amount_cents), description: String(row.description || ""), active: row.active !== 0 }));
const payloadRules = (rules: Rule[]) => rules.map((rule) => ({ ...rule, destinationUnitId: rule.destinationUnitId ? Number(rule.destinationUnitId) : null, destinationDepartmentId: rule.destinationDepartmentId ? Number(rule.destinationDepartmentId) : null, percentage: Number(rule.percentage.replace(",", ".")), fixedAmountCents: moneyCents(rule.fixedAmount) }));
const emptyRule = (): Rule => ({ recipientName: "", recipientType: "OUTRO", ruleType: "PERCENTUAL", financialDestination: "", destinationUnitId: "", destinationDepartmentId: "", percentage: "0", fixedAmount: "0,00", description: "", active: true });
const ruleValue = (row: Row) => row.rule_type === "FIXO" ? money(row.fixed_amount_cents) : row.rule_type === "RESTANTE" ? "Saldo restante" : `${(Number(row.percentage_basis_points || 0) / 100).toLocaleString("pt-BR")}%`;

function RuleEditor({ rules, disabled, options, onChange }: { rules: Rule[]; disabled: boolean; options: Options; onChange: (rules: Rule[]) => void }) {
  const update = (index: number, next: Partial<Rule>) => onChange(rules.map((rule, position) => position === index ? { ...rule, ...next } : rule));
  return <div className="allocation-editor allocation-editor-v3">{rules.map((rule, index) => <article key={index}>
    <span className="allocation-order">{index + 1}</span>
    <label><span>Destinatário</span><input value={rule.recipientName} disabled={disabled} placeholder="Ex.: Pastor, Matriz, Missões" onChange={(event) => update(index, { recipientName: event.target.value })}/></label>
    <label><span>Tipo de cálculo</span><select value={rule.ruleType} disabled={disabled} onChange={(event) => update(index, { ruleType: event.target.value as Rule["ruleType"] })}><option value="PERCENTUAL">Percentual</option><option value="FIXO">Valor fixo</option><option value="RESTANTE">Saldo restante</option></select></label>
    <label className="allocation-destination"><span>Destino financeiro</span><select value={rule.financialDestination} disabled={disabled} required onChange={(event) => update(index, { financialDestination: event.target.value as Rule["financialDestination"] })}><option value="">Selecione</option><option value="REPASSAR">Repassar para outro destinatário</option><option value="MANTER_NA_UNIDADE">Permanecer no caixa desta unidade</option></select><small>{rule.financialDestination === "MANTER_NA_UNIDADE" ? "Permanece disponível para despesas da própria unidade." : rule.financialDestination === "REPASSAR" ? "Será tratado como obrigação de repasse externo." : "Defina como o valor será tratado."}</small></label>
    {rule.financialDestination === "REPASSAR" ? <><label><span>Unidade que receberá</span><select value={rule.destinationUnitId} disabled={disabled} required onChange={(event) => update(index, { destinationUnitId: event.target.value, destinationDepartmentId: "" })}><option value="">Selecione Convenção, Matriz ou Filial</option>{(options.destinationUnits || options.units).map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.name)} · {label(item.type)}</option>)}</select></label><label><span>Departamento (opcional)</span><select value={rule.destinationDepartmentId} disabled={disabled} onChange={(event) => update(index, { destinationDepartmentId: event.target.value })}><option value="">Nenhum departamento específico</option>{(options.departments || []).filter((item) => String(item.unit_id) === rule.destinationUnitId).map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.name)}</option>)}</select></label></> : null}
    {rule.ruleType === "PERCENTUAL" ? <label className="allocation-percent"><span>Percentual (%)</span><div><input inputMode="decimal" value={rule.percentage} disabled={disabled} onChange={(event) => update(index, { percentage: event.target.value.replace(/[^\d,.]/g, "") })}/><b>%</b></div></label> : null}
    {rule.ruleType === "FIXO" ? <label className="allocation-percent"><span>Valor (R$)</span><div><input inputMode="decimal" value={rule.fixedAmount} disabled={disabled} onChange={(event) => update(index, { fixedAmount: event.target.value.replace(/[^\d.,]/g, "") })} onBlur={(event) => update(index, { fixedAmount: inputMoney(moneyCents(event.target.value)) })}/><b>R$</b></div></label> : null}
    {rule.ruleType === "RESTANTE" ? <div className="allocation-rest-label"><span>Saldo restante</span><small>Recebe exatamente o valor disponível após as demais divisões.</small></div> : null}
    {!disabled ? <button type="button" className="allocation-remove" onClick={() => onChange(rules.filter((_, position) => position !== index))} aria-label="Arquivar divisão"><X/></button> : null}
  </article>)}</div>;
}

function AllocationPreview({ preview }: { preview: Row }) {
  const results = Array.isArray(preview.results) ? preview.results as Row[] : [];
  return <section className={`allocation-preview ${preview.valid ? "valid" : "invalid"}`}><div className="finance-section-head"><div><p className="eyebrow">{preview.source === "CLOSURE_SNAPSHOT" ? `Snapshot imutável · fechamento v${String(preview.closureVersion)}` : "Cálculo em tempo real"}</p><h3>{preview.source === "CLOSURE_SNAPSHOT" ? "Rateio do fechamento" : "Prévia do Rateio"}</h3></div><StatusBadge status={preview.valid ? "VALIDO" : "REVISAR"}/></div>
    <div className="allocation-preview-totals"><span>Total de entradas<strong>{money(preview.totalEntriesCents)}</strong></span><span>Recursos fora do rateio<strong>{money(preview.excludedResourcesCents)}</strong></span><span>Base elegível<strong>{money(preview.eligibleBaseCents)}</strong></span></div>
    <div className="allocation-preview-results">{results.map((result, index) => <article key={String(result.ruleId || index)}><span><strong>{String(result.recipientName)}</strong><small>{label(result.ruleType)} · {result.financialDestination === "MANTER_NA_UNIDADE" ? "Permanece na própria unidade" : "Repassar"}</small></span><b>{money(result.calculatedAmountCents)}</b></article>)}</div>
    <div className="allocation-preview-totals allocation-destination-totals"><span>Rateio total<strong>{money(preview.allocatedCents)}</strong></span><span>Destinado à própria unidade<strong>{money(preview.ownUnitAllocationCents)}</strong></span><span>Calculado para repasse<strong>{money(preview.calculatedToTransferCents)}</strong></span><span>Pendente de repasse<strong>{money(preview.pendingTransferCents)}</strong></span></div>
    {!results.length ? <p className="finance-warning"><AlertTriangle/> Nenhuma regra de rateio foi vinculada a este período.</p> : Number(preview.excessCents || 0) > 0 ? <p className="finance-warning"><AlertTriangle/> As divisões ultrapassam a base disponível em {money(preview.excessCents)}. O fechamento será bloqueado.</p> : Number(preview.unallocatedCents || 0) > 0 ? <p className="finance-warning"><AlertTriangle/> Valor não distribuído: {money(preview.unallocatedCents)}.</p> : <p className="finance-snapshot-note"><CheckCircle2/> A soma calculada fecha exatamente a base elegível.</p>}
  </section>;
}

export function FinancePeriodManager({ mode, options }: { mode: "caixa" | "rateio"; options: Options }) {
  const { session } = useWorkspace(), automaticUnit = useRef(""), [unitId, setUnitId] = useState(String(options.units[0]?.id || "")), [competency, setCompetency] = useState(previousMonth()), [workspace, setWorkspace] = useState<Workspace | null>(null), [loading, setLoading] = useState(false), [dialog, setDialog] = useState<"open" | "close" | "reopen" | "request" | null>(null), [busy, setBusy] = useState(false), [toast, setToast] = useState({ message: "", kind: "success" as "success" | "error" }), [rules, setRules] = useState<Rule[]>([]);
  const accept = useCallback((result: Workspace, automatic = false) => { if (automatic) setCompetency(result.competency); setWorkspace(result); setRules(mapRules(result.config?.rules || [])); }, []);
  const load = useCallback(async () => { if (!unitId) return; setLoading(true); try { const body = await readApi<{ result: Workspace }>(await fetch(`/api/finance/periods?unitId=${unitId}&competency=${competency}`, { cache: "no-store" })); accept(body.result); } catch (error) { setToast({ message: error instanceof Error ? error.message : "Não foi possível carregar o caixa.", kind: "error" }); } finally { setLoading(false); } }, [unitId, competency, accept]);
  useEffect(() => { let active = true; if (!unitId) return; const automatic = automaticUnit.current !== unitId, url = automatic ? `/api/finance/periods?unitId=${unitId}` : `/api/finance/periods?unitId=${unitId}&competency=${competency}`; void fetch(url, { cache: "no-store" }).then((response) => readApi<{ result: Workspace }>(response)).then((body) => { if (active) { automaticUnit.current = unitId; accept(body.result, automatic); } }).catch((error) => { if (active) setToast({ message: error instanceof Error ? error.message : "Não foi possível carregar o caixa.", kind: "error" }); }); return () => { active = false; }; }, [unitId, competency, accept]);
  const total = useMemo(() => rules.reduce((sum, rule) => sum + (rule.ruleType === "PERCENTUAL" ? Number(rule.percentage.replace(",", ".")) || 0 : 0), 0), [rules]);
  const remainderCount = rules.filter((rule) => rule.ruleType === "RESTANTE").length, validRules = rules.length > 0 && total <= 100 && remainderCount <= 1 && rules.every((rule) => rule.recipientName.trim() && rule.financialDestination && (rule.financialDestination !== "REPASSAR" || rule.destinationUnitId) && (rule.ruleType !== "FIXO" || moneyCents(rule.fixedAmount) > 0));
  async function saveRules() { if (!workspace) return; setBusy(true); try { await readApi(await fetch("/api/finance/allocation", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ unitId: workspace.unit.id, rules: payloadRules(rules) }) })); setToast({ message: "Configuração própria da unidade salva. Novos caixas usarão esta versão.", kind: "success" }); await load(); } catch (error) { setToast({ message: error instanceof Error ? error.message : "Não foi possível salvar o rateio.", kind: "error" }); } finally { setBusy(false); } }
  async function operate(form: FormData) { if (!workspace || !dialog) return; setBusy(true); try { if(dialog==="request"){await readApi(await fetch("/api/finance/reopen-requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({periodId:workspace.period?.id,reason:form.get("reason"),password:form.get("password")})}));setToast({message:"Solicitação enviada ao administrador da Matriz.",kind:"success"});}else{const action = dialog === "open" ? "OPEN" : dialog === "close" ? "CLOSE" : "REOPEN"; await readApi(await fetch("/api/finance/periods", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, unitId: workspace.unit.id, competency, password: form.get("password"), periodId: workspace.period?.id, requestId:workspace.permissions.canUseApprovedReopen?workspace.reopenRequest?.id:null, reason: form.get("reason"), notes: form.get("notes") }) })); setToast({ message: action === "OPEN" ? "Caixa aberto e regras mensais preservadas." : action === "CLOSE" ? "Caixa fechado e snapshot versionado." : "Caixa reaberto para correções auditadas.", kind: "success" });}setDialog(null);await load(); } catch (error) { setToast({ message: error instanceof Error ? error.message : "Não foi possível concluir a operação.", kind: "error" }); } finally { setBusy(false); } }
  async function decide(requestId:number,action:"APPROVE"|"REJECT"){const password=window.prompt("Confirme sua senha para registrar a decisão:");if(!password)return;const decisionReason=action==="REJECT"?window.prompt("Informe o motivo da recusa:")||"":"";if(action==="REJECT"&&decisionReason.trim().length<5){setToast({message:"Informe o motivo da recusa.",kind:"error"});return;}setBusy(true);try{await readApi(await fetch("/api/finance/reopen-requests",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId,action,password,decisionReason})}));setToast({message:action==="APPROVE"?"Autorização única concedida por 48 horas.":"Solicitação recusada.",kind:"success"});await load();}catch(error){setToast({message:error instanceof Error?error.message:"Não foi possível registrar a decisão.",kind:"error"});}finally{setBusy(false);}}
  if (!options.units.length) return <section className="content-card finance-section finance-empty-inline">Nenhuma Matriz ou Filial disponível no seu escopo.</section>;
  return <section className="finance-period-space"><div className="content-card finance-period-selector"><label><span>Unidade financeira</span><select value={unitId} onChange={(event) => setUnitId(event.target.value)}>{options.units.map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.name)} · {label(item.type)}</option>)}</select></label><label><span>Caixa / Período</span><select value={workspace?.periods.some(item=>String(item.competency)===competency)?competency:""} onChange={(event)=>event.target.value&&setCompetency(event.target.value)}><option value="">Nova competência</option>{workspace?.periods.map(item=><option key={String(item.id)} value={String(item.competency)}>{String(item.competency).split("-").reverse().join("/")} — {item.lifecycle_state==="REABERTO"?"🟠 REABERTO":item.status==="FECHADO"?"🔒 FECHADO":"🟢 ABERTO"}</option>)}</select><small>Escolha um caixa fechado para localizar a ação Reabrir Caixa.</small></label><label><span>Competência</span><input type="month" value={competency} onChange={(event) => setCompetency(event.target.value)}/><small>{workspace?.competencySource === "OPEN_PERIOD" ? "Caixa aberto carregado automaticamente." : workspace?.competencySource === "LATEST_PERIOD" ? "Período mais recente carregado automaticamente." : "Informe a competência que deseja abrir."}</small></label><button className="secondary-button" onClick={() => void load()} disabled={loading}>{loading ? <LoaderCircle className="spin"/> : <RefreshCw/>} Atualizar</button></div>
    {workspace && mode === "rateio" ? <section className="content-card finance-section"><div className="finance-section-head"><div><p className="eyebrow">Configuração própria</p><h2>Rateio · {workspace.unit.name}</h2><p className="finance-helper">Esta configuração pertence somente a esta unidade. Cada regra de repasse deve indicar a unidade que receberá o valor.</p></div>{workspace.permissions.canConfigure ? <button className="primary-button" onClick={() => void saveRules()} disabled={busy || !validRules}>{busy ? <LoaderCircle className="spin"/> : <Settings2/>} Salvar configuração</button> : null}</div><div className={`allocation-total ${validRules ? "valid" : "invalid"}`}><strong>Percentuais: {total.toLocaleString("pt-BR", { maximumFractionDigits: 2 })}%</strong><span>{remainderCount > 1 ? <><AlertTriangle/> Use somente um Saldo Restante</> : total > 100 ? <><AlertTriangle/> Percentuais excedem 100%</> : <><CheckCircle2/> Cálculo sobre a base original</>}</span></div><RuleEditor rules={rules} disabled={!workspace.permissions.canConfigure} options={options} onChange={setRules}/>{workspace.permissions.canConfigure ? <button className="secondary-button allocation-add" onClick={() => setRules((current) => [...current, emptyRule()])}><Plus/> Adicionar divisão</button> : <p className="finance-warning"><AlertTriangle/> Você pode visualizar, mas não alterar as regras desta unidade.</p>}<div className="finance-snapshot-note"><LockKeyhole/><p><strong>Configuração padrão não altera o histórico.</strong> Ao abrir um caixa, destinatários, tipos, valores, ordem e categorias elegíveis são copiados para a competência.</p></div>{workspace.config?.history?.length ? <p className="finance-helper">Histórico preservado: {workspace.config.history.length} versão(ões) recente(s).</p> : null}</section> : null}
    {workspace && mode === "caixa" ? <><section className={`content-card finance-period-hero ${workspace.period?.lifecycle_state === "REABERTO" ? "reopened" : workspace.period?.status === "FECHADO" ? "closed" : "open"}`}><div className="period-status-icon">{workspace.period?.status === "FECHADO" ? <LockKeyhole/> : <UnlockKeyhole/>}</div><div><p className="eyebrow">{workspace.unit.name} · {competency.split("-").reverse().join("/")}</p><h2>{!workspace.period ? "Caixa ainda não aberto" : workspace.period.lifecycle_state === "REABERTO" ? "🟠 CAIXA REABERTO" : workspace.period.status === "FECHADO" ? "🔒 CAIXA FECHADO" : "🟢 CAIXA ABERTO"}</h2><p>{!workspace.period ? "Configure o rateio e abra o período para lançar." : workspace.period.lifecycle_state === "REABERTO" ? "Este período havia sido fechado e está aberto para correções autorizadas." : workspace.period.status === "FECHADO" ? "O fechamento oficial está preservado. Usuários autorizados podem consultar o relatório ou reabrir este período para correções auditadas." : `Aberto por ${String(workspace.period.opened_by_name || session.user.name)} em ${dateTime(workspace.period.opened_at)}.`}</p></div><div className="period-actions">{!workspace.period && workspace.permissions.canOpen ? <button className="primary-button" onClick={() => setDialog("open")} disabled={!workspace.config}><UnlockKeyhole/> Abrir Caixa</button> : null}{workspace.period?.status === "ABERTO" && workspace.permissions.canQuick ? <Link className="primary-button" href={`/painel/financeiro/rapido?periodo=${workspace.period.id}`}><Zap/> Lançamento Rápido</Link> : null}{workspace.period?.status === "ABERTO" && workspace.permissions.canClose ? <button className="danger-outline-button" onClick={() => setDialog("close")}><LockKeyhole/> Fechar Caixa</button> : null}{workspace.period?.status === "FECHADO" ? <Link className="secondary-button" href="/painel/financeiro?aba=relatorios">Visualizar relatório</Link> : null}{workspace.period?.status === "FECHADO" && (workspace.permissions.canReopen || workspace.permissions.canUseApprovedReopen) ? <button className="danger-outline-button reopen-period-button" onClick={() => setDialog("reopen")}><UnlockKeyhole/> {workspace.permissions.canUseApprovedReopen&&!workspace.permissions.canReopen?"Reabrir Caixa — autorizado":"Reabrir Caixa"}</button> : null}{workspace.period?.status === "FECHADO" && workspace.permissions.canRequestReopen && workspace.reopenRequest?.status!=="PENDENTE" && !workspace.permissions.canUseApprovedReopen ? <button className="primary-button" onClick={() => setDialog("request")}><KeyRound/> Solicitar reabertura</button> : null}</div></section>
      {!workspace.config ? <section className="content-card finance-section finance-warning-card"><AlertTriangle/><div><h3>Esta unidade ainda não possui configuração de rateio</h3><p>{workspace.permissions.canConfigure ? "Abra a aba Rateio e configure agora." : "Solicite a configuração a um administrador autorizado."}</p></div></section> : <section className="content-card finance-section"><h2>Regras deste período</h2><p className="finance-helper">{workspace.period ? "Snapshot mensal preservado — alterações futuras no padrão não modificarão este caixa." : "Estas regras serão copiadas exclusivamente para a competência ao abrir o caixa."}</p><div className="period-rules">{(workspace.period?.rules || workspace.config.rules).map((rule, index) => {const destination=(options.destinationUnits||options.units).find((item)=>Number(item.id)===Number(rule.destination_unit_id));return <article key={String(rule.id || index)}><span>{String(rule.recipient_name)}<small>{label(rule.rule_type)} · {rule.financial_destination === "MANTER_NA_UNIDADE" ? `Permanece em ${workspace.unit.name}` : `Repassar para ${String(destination?.name || "unidade definida")}`}</small></span><strong>{ruleValue(rule)}</strong></article>;})}</div>{workspace.period?.status === "ABERTO" && workspace.permissions.canAlterPeriod ? <PeriodRuleEditor key={`${workspace.period.id}:${workspace.period.version}`} workspace={workspace} options={options} onSaved={load}/> : null}{workspace.period?.allocationPreview ? <AllocationPreview preview={workspace.period.allocationPreview}/> : null}</section>}
      {workspace.pendingRequests.length ? <section className="content-card finance-section"><div className="finance-section-head"><div><p className="eyebrow">Autorizações pendentes</p><h2>Solicitações das Filiais</h2></div></div><div className="finance-cards">{workspace.pendingRequests.map(request=><article key={String(request.id)}><KeyRound/><span><strong>{String(request.requester_name)} · {String(request.unit_name)}</strong><small>Caixa {String(request.competency).split("-").reverse().join("/")} · {String(request.reason)}</small></span><button className="secondary-button" disabled={busy} onClick={()=>void decide(Number(request.id),"REJECT")}>Recusar</button><button className="primary-button" disabled={busy} onClick={()=>void decide(Number(request.id),"APPROVE")}>Autorizar uma vez</button></article>)}</div></section>:null}
      {workspace.period ? <section className="finance-kpis finance-period-kpis"><article><span>Entradas<strong>{money(workspace.period.totals?.total_entries_cents)}</strong></span></article><article><span>Base elegível<strong>{money(workspace.period.allocationPreview?.eligibleBaseCents)}</strong></span></article><article><span>Fora do rateio<strong>{money(workspace.period.allocationPreview?.excludedResourcesCents)}</strong></span></article><article><span>Fechamentos preservados<strong>{String(workspace.period.closures.length)}</strong></span></article></section> : null}
      {workspace.sessions.length ? <section className="content-card finance-section"><h2>Sessões de lançamento</h2><div className="finance-cards">{workspace.sessions.map((item) => <article key={String(item.id)}><Zap/><span><strong>{String(item.user_name)}</strong><small>{String(item.entry_count)} lançamentos · {money(item.total_cents)} · {label(item.status)}</small></span>{item.status === "EM_ANDAMENTO" && Number(item.user_id) === session.user.id ? <Link className="secondary-button" href={`/painel/financeiro/rapido?sessao=${item.id}`}>Retomar</Link> : <StatusBadge status={String(item.status)}/>}</article>)}</div></section> : null}</> : null}
    {workspace?.period?.status === "FECHADO" && workspace.reopenRequest?.status === "PENDENTE" ? <section className="content-card finance-section finance-warning-card"><AlertTriangle/><div><h3>Solicitação aguardando a Matriz</h3><p>O administrador da Matriz foi notificado. A autorização, quando aprovada, valerá somente para este caixa e uma única reabertura.</p></div></section> : null}
    {workspace?.period?.status === "FECHADO" && !workspace.permissions.canReopen && !workspace.permissions.canRequestReopen ? <section className="content-card finance-section finance-warning-card"><AlertTriangle/><div><h3>Reabertura controlada</h3><p>Solicite ao administrador que habilite a permissão adequada no seu cadastro de usuário.</p></div></section> : null}
    {dialog && workspace ? <SensitiveDialog action={dialog} workspace={workspace} busy={busy} onClose={() => setDialog(null)} onSubmit={operate}/> : null}<Toast {...toast} onClose={() => setToast({ ...toast, message: "" })}/>
  </section>;
}

function SensitiveDialog({ action, workspace, busy, onClose, onSubmit }: { action: "open" | "close" | "reopen" | "request"; workspace: Workspace; busy: boolean; onClose: () => void; onSubmit: (form: FormData) => void }) {
  const title = action === "open" ? "Confirmar e Abrir Caixa" : action === "close" ? "Fechar Caixa" : action === "request" ? "Solicitar reabertura" : "Confirmar Reabertura";
  return <div className="dialog-backdrop"><section className="dialog-card finance-sensitive-dialog" role="dialog" aria-modal="true"><header><div className="dialog-icon"><KeyRound/></div><div><p className="eyebrow">Operação sensível</p><h2>{title}</h2></div><button className="icon-button" onClick={onClose} aria-label="Fechar"><X/></button></header><div className="sensitive-summary"><span>Unidade <strong>{workspace.unit.name}</strong></span><span>Competência <strong>{workspace.competency.split("-").reverse().join("/")}</strong></span></div>{action === "open" ? <p>As regras exibidas serão copiadas e vinculadas exclusivamente a este período.</p> : action === "close" ? <p>O fechamento validará a base, bloqueará lançamentos e preservará regras e cálculos.</p> : action === "request" ? <p>A Matriz receberá uma notificação. Se aprovada, a permissão valerá uma única vez e somente para este caixa.</p> : <p className="finance-danger-note">A reabertura permitirá correções auditadas sem apagar fechamentos anteriores.</p>}<form onSubmit={(event) => { event.preventDefault(); onSubmit(new FormData(event.currentTarget)); }}>{action === "open" ? <label className="field-group"><span>Observações opcionais</span><textarea name="notes" rows={2}/></label> : null}{action === "reopen" || action === "request" ? <label className="field-group"><span>Motivo da reabertura</span><textarea name="reason" rows={4} minLength={10} required defaultValue={action==="reopen"&&workspace.permissions.canUseApprovedReopen?String(workspace.reopenRequest?.reason||""):undefined}/></label> : null}<label className="field-group"><span>Confirme sua senha</span><input name="password" type="password" autoComplete="current-password" required/></label><small>A senha é validada no servidor e não fica armazenada.</small><div className="dialog-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancelar</button><button className={action === "open" || action === "request" ? "primary-button" : "danger-outline-button"} disabled={busy}>{busy ? <LoaderCircle className="spin"/> : action === "open" ? <UnlockKeyhole/> : <LockKeyhole/>}{title}</button></div></form></section></div>;
}

function PeriodRuleEditor({ workspace, options, onSaved }: { workspace: Workspace; options: Options; onSaved: () => Promise<void> }) {
  const historical = workspace.period?.lifecycle_state === "REABERTO", [editing, setEditing] = useState(false), [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [localRules, setLocalRules] = useState<Rule[]>(() => mapRules(workspace.period?.rules || []));
  const total = localRules.reduce((sum, rule) => sum + (rule.ruleType === "PERCENTUAL" ? Number(rule.percentage.replace(",", ".")) || 0 : 0), 0), valid = localRules.length > 0 && total <= 100 && localRules.filter((rule) => rule.ruleType === "RESTANTE").length <= 1 && localRules.every((rule) => rule.recipientName.trim() && rule.financialDestination && (rule.financialDestination !== "REPASSAR" || rule.destinationUnitId) && (rule.ruleType !== "FIXO" || moneyCents(rule.fixedAmount) > 0));
  async function save(form: FormData) { if (!workspace.period) return; setBusy(true); setMessage(""); try { await readApi(await fetch("/api/finance/periods", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ periodId: workspace.period.id, password: form.get("password"), reason: form.get("reason"), rules: payloadRules(localRules) }) })); setMessage("Rateio do período corrigido e auditado. A configuração padrão permaneceu inalterada."); setEditing(false); await onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível corrigir o rateio."); } finally { setBusy(false); } }
  if (!editing) return <div className="finance-historical-action"><div><strong>{historical ? "Correção histórica autorizada" : "Regra própria do caixa aberto"}</strong><p>Altere somente o snapshot desta competência, sem modificar o padrão atual.</p></div><button className={historical ? "danger-outline-button" : "secondary-button"} onClick={() => setEditing(true)}><Settings2/> {historical ? "Corrigir rateio do período" : "Alterar rateio do período"}</button>{message ? <small>{message}</small> : null}</div>;
  return <form className="finance-historical-editor" onSubmit={(event) => { event.preventDefault(); void save(new FormData(event.currentTarget)); }}><div className="finance-section-head"><div><p className="eyebrow">{historical ? "Auditoria reforçada" : "Caixa aberto"}</p><h3>Rateio deste período</h3></div><strong className={valid ? "valid" : "invalid"}>{total.toLocaleString("pt-BR")}%</strong></div><RuleEditor rules={localRules} disabled={false} options={options} onChange={setLocalRules}/><button type="button" className="secondary-button" onClick={() => setLocalRules((current) => [...current, emptyRule()])}><Plus/> Adicionar divisão</button><label className="field-group"><span>Motivo da alteração {historical ? "(obrigatório)" : "(opcional)"}</span><textarea name="reason" minLength={historical ? 10 : undefined} required={historical}/></label>{historical ? <label className="field-group"><span>Confirme sua senha</span><input name="password" type="password" autoComplete="current-password" required/></label> : null}{message ? <p className="finance-warning">{message}</p> : null}<div className="dialog-actions"><button type="button" className="secondary-button" onClick={() => setEditing(false)}>Cancelar</button><button className={historical ? "danger-outline-button" : "primary-button"} disabled={busy || !valid}>{busy ? <LoaderCircle className="spin"/> : <Settings2/>} Salvar regra do período</button></div></form>;
}
