"use client";
import {Bell,Check,CheckCheck,ChevronLeft,ChevronRight,LoaderCircle} from "lucide-react";
import {useEffect,useState} from "react";
import {AdminPageHeader,readApi,Toast} from "@/components/admin/admin-ui";
import {relativeNotificationTime} from "@/components/notification-center";
import type {NotificationPage,NotificationRecord} from "@/lib/notifications/types";
export function NotificationsPage(){const [filter,setFilter]=useState<"all"|"unread"|"read">("all"),[page,setPage]=useState(1),[result,setResult]=useState<NotificationPage>({items:[],page:1,pageSize:12,total:0,totalPages:1,unread:0}),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0),[toast,setToast]=useState({message:"",kind:"success" as "success"|"error"});
  useEffect(()=>{const controller=new AbortController();void(async()=>{setLoading(true);try{const body=await readApi<{result:NotificationPage}>(await fetch(`/api/notifications?status=${filter}&page=${page}&pageSize=12`,{cache:"no-store",signal:controller.signal}));setResult(body.result);}catch(e){if(!controller.signal.aborted)setToast({message:e instanceof Error?e.message:"Não foi possível carregar as notificações.",kind:"error"});}finally{if(!controller.signal.aborted)setLoading(false);}})();return()=>controller.abort();},[filter,page,refresh]);
  async function markRead(notification:NotificationRecord,navigate=false){try{const body=await readApi<{route:string|null}>(await fetch(`/api/notifications/${notification.id}/read`,{method:"POST"}));if(navigate&&body.route){window.location.assign(body.route);return;}setRefresh(value=>value+1);}catch(e){setToast({message:e instanceof Error?e.message:"Não foi possível atualizar a notificação.",kind:"error"});}}
  async function markAll(){try{await readApi(await fetch("/api/notifications/read-all",{method:"POST"}));setToast({message:"Todas as notificações foram marcadas como lidas.",kind:"success"});setRefresh(value=>value+1);}catch(e){setToast({message:e instanceof Error?e.message:"Não foi possível atualizar as notificações.",kind:"error"});}}
  return <><AdminPageHeader eyebrow="Alertas e pendências" title="Notificações" description="Acompanhe acontecimentos relacionados à sua instituição, unidade, perfil e permissões." action={result.unread?<button className="secondary-button compact-button" onClick={()=>void markAll()}><CheckCheck size={18}/>Marcar todas como lidas</button>:undefined}/><section className="notification-filter-bar"><div>{([['all','Todas'],['unread',`Não lidas${result.unread?` (${result.unread})`:''}`],['read','Lidas']] as const).map(([value,label])=><button key={value} className={filter===value?"active":""} onClick={()=>{setFilter(value);setPage(1);}}>{label}</button>)}</div><span>{result.total} registro{result.total===1?"":"s"}</span></section><section className="content-card notification-history">{loading?<div className="notification-empty page-empty"><LoaderCircle className="spin"/><span>Carregando notificações...</span></div>:null}{!loading&&!result.items.length?<div className="notification-empty page-empty"><Bell size={34}/><h2>Nenhuma notificação encontrada</h2><p>Quando surgir algo que precisa da sua atenção, aparecerá aqui.</p></div>:result.items.map(notification=><article key={notification.id} className={notification.readAt?"":"notification-unread"}><button className="notification-history-main" onClick={()=>void markRead(notification,true)}><span className={`notification-history-dot priority-${notification.priority.toLowerCase()}`}/><span><span className="notification-meta"><em>{notification.contextLabel}</em><small>{relativeNotificationTime(notification.createdAt)}</small></span><strong>{notification.title}</strong><p>{notification.message}</p><small>{notification.type.replaceAll("_"," ")}</small></span><ChevronRight size={18}/></button>{!notification.readAt?<button className="secondary-button compact-button" onClick={()=>void markRead(notification)}><Check size={16}/>Marcar como lida</button>:<span className="read-label"><Check size={15}/>Lida</span>}</article>)}</section>{result.totalPages>1?<nav className="notification-pagination" aria-label="Paginação"><button disabled={page<=1} onClick={()=>setPage(value=>value-1)}><ChevronLeft size={17}/>Anterior</button><span>Página {page} de {result.totalPages}</span><button disabled={page>=result.totalPages} onClick={()=>setPage(value=>value+1)}>Próxima<ChevronRight size={17}/></button></nav>:null}<Toast {...toast} onClose={()=>setToast({...toast,message:""})}/></>;
}
