"use client";
import Link from "next/link";
import {Bell,Check,CheckCheck,ChevronRight,ClipboardList,Info,LoaderCircle,X} from "lucide-react";
import {useCallback,useEffect,useRef,useState} from "react";
import type {NotificationPage,NotificationPriority,NotificationRecord} from "@/lib/notifications/types";
import {notificationBadge} from "@/lib/notifications/policy";

export function relativeNotificationTime(value:string){const diff=Date.now()-new Date(value).getTime(),minutes=Math.floor(diff/60000);if(minutes<1)return"Agora";if(minutes<60)return`Há ${minutes} min`;const hours=Math.floor(minutes/60);if(hours<24)return`Há ${hours} h`;if(hours<48)return"Ontem";return new Intl.DateTimeFormat("pt-BR",{timeZone:"America/Belem"}).format(new Date(value));}
const priorityLabel:Record<NotificationPriority,string>={INFO:"Informação",ATENCAO:"Atenção",IMPORTANTE:"Importante",CRITICA:"Crítica"};
function NotificationIcon({notification}:{notification:NotificationRecord}){return notification.type==="MEMBRO_PRECADASTRO_RECEBIDO"?<ClipboardList size={18}/>:<Info size={18}/>;}
export function NotificationCenter({contextKey}:{contextKey:string}){const [open,setOpen]=useState(false),[count,setCount]=useState(0),[items,setItems]=useState<NotificationRecord[]>([]),[loading,setLoading]=useState(false);const root=useRef<HTMLDivElement>(null);
  const refresh=useCallback(async(withList=false)=>{try{if(withList){setLoading(true);const response=await fetch("/api/notifications?page=1&pageSize=6",{cache:"no-store"});if(response.ok){const body=await response.json() as {result:NotificationPage};setItems(body.result.items);setCount(body.result.unread);}}else{const response=await fetch("/api/notifications/count",{cache:"no-store"});if(response.ok){const body=await response.json() as {count:number};setCount(body.count);}}}finally{setLoading(false);}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void refresh(false),0);const interval=window.setInterval(()=>{if(document.visibilityState==="visible")void refresh(open);},45_000);return()=>{window.clearTimeout(timer);window.clearInterval(interval);};},[refresh,open,contextKey]);
  useEffect(()=>{function outside(event:MouseEvent){if(root.current&&!root.current.contains(event.target as Node))setOpen(false);}function escape(event:KeyboardEvent){if(event.key==="Escape")setOpen(false);}document.addEventListener("mousedown",outside);document.addEventListener("keydown",escape);return()=>{document.removeEventListener("mousedown",outside);document.removeEventListener("keydown",escape);};},[]);
  async function toggle(){const next=!open;setOpen(next);if(next)await refresh(true);}
  async function markRead(notification:NotificationRecord,navigate=false){const response=await fetch(`/api/notifications/${notification.id}/read`,{method:"POST"});if(response.ok){const body=await response.json() as {route?:string|null};setItems(current=>current.map(item=>item.id===notification.id?{...item,readAt:item.readAt??new Date().toISOString()}:item));if(!notification.readAt)setCount(current=>Math.max(0,current-1));if(navigate&&body.route)window.location.assign(body.route);}}
  async function markAll(){const response=await fetch("/api/notifications/read-all",{method:"POST"});if(response.ok){const readAt=new Date().toISOString();setItems(current=>current.map(item=>({...item,readAt:item.readAt??readAt})));setCount(0);}}
  return <div className="notification-center" ref={root}><button className="notification-bell" type="button" onClick={()=>void toggle()} aria-label={`Notificações${count?`, ${count} não lidas`:""}`} aria-expanded={open}><Bell size={21}/>{count?<span aria-hidden="true">{notificationBadge(count)}</span>:null}</button>{open?<section className="notification-dropdown" aria-label="Notificações recentes"><header><div><strong>Notificações</strong><small>{count?`${count} não lida${count===1?"":"s"}`:"Tudo em dia"}</small></div><div>{count?<button type="button" onClick={()=>void markAll()} title="Marcar todas como lidas"><CheckCheck size={18}/></button>:null}<button type="button" onClick={()=>setOpen(false)} aria-label="Fechar notificações"><X size={18}/></button></div></header><div className="notification-list">{loading?<div className="notification-empty"><LoaderCircle className="spin"/><span>Atualizando...</span></div>:null}{!loading&&!items.length?<div className="notification-empty"><Bell size={27}/><strong>Nenhuma notificação</strong><span>Novos avisos aparecerão aqui.</span></div>:items.map(notification=><article key={notification.id} className={`notification-item${notification.readAt?"":" notification-unread"}`}><button className="notification-main-action" type="button" onClick={()=>void markRead(notification,true)}><span className={`notification-kind priority-${notification.priority.toLowerCase()}`}><NotificationIcon notification={notification}/></span><span><span className="notification-meta"><em>{notification.contextLabel}</em><small>{relativeNotificationTime(notification.createdAt)}</small></span><strong>{notification.title}</strong><span>{notification.message}</span><small>{priorityLabel[notification.priority]}</small></span><ChevronRight size={17}/></button>{!notification.readAt?<button className="notification-read-action" onClick={()=>void markRead(notification)} title="Marcar como lida" aria-label={`Marcar ${notification.title} como lida`}><Check size={15}/></button>:null}</article>)}</div><footer><Link href="/painel/notificacoes" onClick={()=>setOpen(false)}>Ver todas as notificações <ChevronRight size={17}/></Link></footer></section>:null}</div>;
}
