"use client";
import {useEffect,useRef,useState} from "react";
import {Camera,CheckCircle2,Church,ImagePlus,LoaderCircle,MapPin,X} from "lucide-react";
import {readApi} from "@/components/admin/admin-ui";
import {cameraFailureMessage,frontendImageError} from "@/lib/image-policy";
import {CONSENT_TEXT} from "@/lib/members/custom-fields";
import type {PublicPreRegistrationForm} from "@/lib/members/pre-registration-types";

const initial={fullName:"",birthDate:"",sex:"NAO_INFORMADO",cpf:"",rg:"",voterTitle:"",birthCity:"",birthState:"",phone:"",whatsapp:"",email:"",motherName:"",fatherName:"",maritalStatus:"NAO_INFORMADO",spouseName:"",childrenCount:"0",postalCode:"",street:"",addressNumber:"",complement:"",district:"",city:"",state:"",profession:"",workplace:"",educationLevel:"NAO_INFORMADO",theologicalEducation:"NAO_INFORMADO",churchEntryDate:"",originChurch:"",conversionDate:"",baptismDate:"",consecrationDate:""};
const education=[["NAO_INFORMADO","Não informado"],["NAO_ALFABETIZADO","Não alfabetizado"],["FUNDAMENTAL_INCOMPLETO","Fundamental incompleto"],["FUNDAMENTAL_COMPLETO","Fundamental completo"],["MEDIO_INCOMPLETO","Médio incompleto"],["MEDIO_COMPLETO","Médio completo"],["SUPERIOR_INCOMPLETO","Superior incompleto"],["SUPERIOR_COMPLETO","Superior completo"],["POS_GRADUACAO","Pós-graduação"],["MESTRADO","Mestrado"],["DOUTORADO","Doutorado"]];
const theology=[["NAO_INFORMADO","Não informado"],["NENHUMA","Nenhuma"],["BASICO","Básico"],["MEDIO","Médio"],["AVANCADO","Avançado"],["OUTRO","Outro"]];

export function PublicPreRegistration({token}:{token:string}){
 const [definition,setDefinition]=useState<PublicPreRegistrationForm|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[photo,setPhoto]=useState<File|null>(null),[preview,setPreview]=useState(""),[camera,setCamera]=useState(false),[captured,setCaptured]=useState(false),[custom,setCustom]=useState<Record<string,string|string[]>>({}),[form,setForm]=useState<Record<string,string>>(initial);
 const videoRef=useRef<HTMLVideoElement>(null),streamRef=useRef<MediaStream|null>(null),fileRef=useRef<HTMLInputElement>(null);
 const set=(key:string,value:string)=>setForm(previous=>({...previous,[key]:value}));
 useEffect(()=>{void(async()=>{try{setDefinition((await readApi<{form:PublicPreRegistrationForm}>(await fetch(`/api/public/pre-registration/${token}`,{cache:"no-store"}))).form);}catch(e){setError(e instanceof Error?e.message:"Formulário indisponível.");}})();},[token]);
 function stopCamera(){streamRef.current?.getTracks().forEach(track=>track.stop());streamRef.current=null;setCamera(false);setCaptured(false);}
 useEffect(()=>()=>streamRef.current?.getTracks().forEach(track=>track.stop()),[]);
 async function choose(file:File|null){if(!file)return;const invalid=frontendImageError(file);if(invalid){setError(invalid);return;}setPhoto(file);if(preview)URL.revokeObjectURL(preview);setPreview(URL.createObjectURL(file));stopCamera();}
 async function openCamera(){setError("");if(!navigator.mediaDevices?.getUserMedia){fileRef.current?.click();return;}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user"},audio:false});streamRef.current=stream;setCamera(true);setCaptured(false);setTimeout(()=>{if(videoRef.current)videoRef.current.srcObject=stream;},0);}catch(e){setError(cameraFailureMessage(e));fileRef.current?.click();}}
 function capture(){const video=videoRef.current;if(!video)return;const canvas=document.createElement("canvas");canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext("2d")?.drawImage(video,0,0);canvas.toBlob(blob=>{if(!blob)return;const file=new File([blob],"foto.jpg",{type:"image/jpeg"});setPhoto(file);setPreview(URL.createObjectURL(file));setCaptured(true);},"image/jpeg",.86);}
 async function cep(){setBusy(true);setError("");try{const b=await readApi<{address:Record<string,string>}>(await fetch(`/api/public/postal-code?postalCode=${encodeURIComponent(form.postalCode)}`));setForm(previous=>({...previous,...b.address,addressNumber:previous.addressNumber,complement:previous.complement||b.address.complement}));}catch(e){setError(e instanceof Error?e.message:"CEP não encontrado. Preencha manualmente.");}finally{setBusy(false);}}
 function toggle(id:number,option:string,checked:boolean){const key=String(id),selected=Array.isArray(custom[key])?custom[key]:[];setCustom({...custom,[key]:checked?[...new Set([...selected,option])]:selected.filter(value=>value!==option)});}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");try{const consent=Boolean(e.currentTarget.querySelector<HTMLInputElement>(".public-consent input")?.checked),data=new FormData();data.set("payload",JSON.stringify({...form,customValues:custom,consent}));if(photo)data.set("photo",photo);await readApi(await fetch(`/api/public/pre-registration/${token}`,{method:"POST",body:data}));setDone(true);}catch(err){setError(err instanceof Error?err.message:"Não foi possível enviar.");}finally{setBusy(false);}}
 if(error&&!definition)return <main className="public-registration-shell"><section className="public-registration-card public-result"><Church size={48}/><h1>Formulário indisponível</h1><p>{error}</p></section></main>;
 if(!definition)return <main className="public-registration-shell"><LoaderCircle className="spin"/><p>Carregando formulário seguro…</p></main>;
 if(done)return <main className="public-registration-shell"><section className="public-registration-card public-result"><CheckCircle2 size={58}/><h1>Cadastro enviado com sucesso!</h1><p>Suas informações foram encaminhadas para análise da secretaria da igreja.</p></section></main>;
 return <main className="public-registration-shell"><section className="public-registration-card"><header className="public-registration-header"><Church size={42}/><p className="eyebrow">{definition.institutionName}</p><h1>{definition.name}</h1><span>{definition.unitName??"Cadastro geral"}</span></header><form className="member-form" onSubmit={submit}>
  <section className="member-photo-editor"><div className="member-photo-preview">{preview?<img src={preview} alt="Prévia da foto"/>:<Camera/>}</div><div><strong>Foto (opcional)</strong><p>Você pode tirar uma foto ou escolher uma imagem.</p><div className="member-photo-actions"><button type="button" className="secondary-button compact-button" onClick={()=>void openCamera()}><Camera size={16}/>Tirar foto</button><button type="button" className="secondary-button compact-button" onClick={()=>fileRef.current?.click()}><ImagePlus size={16}/>Escolher foto</button></div><input ref={fileRef} hidden type="file" accept="image/png,image/jpeg,image/webp" capture="user" onChange={e=>void choose(e.target.files?.[0]??null)}/></div></section>
  <Fieldset title="Dados pessoais"><Input label="Nome completo *" value={form.fullName} change={v=>set("fullName",v)} required/><Input label="Data de nascimento" type="date" value={form.birthDate} change={v=>set("birthDate",v)}/><Select label="Sexo" value={form.sex} change={v=>set("sex",v)} options={[["NAO_INFORMADO","Não informado"],["MASCULINO","Masculino"],["FEMININO","Feminino"]]}/><Input label="CPF" value={form.cpf} change={v=>set("cpf",v)} inputMode="numeric"/><Input label="RG" value={form.rg} change={v=>set("rg",v)}/><Input label="Título de Eleitor" value={form.voterTitle} change={v=>set("voterTitle",v)} inputMode="numeric"/><Input label="Naturalidade (cidade)" value={form.birthCity} change={v=>set("birthCity",v)}/><Input label="Naturalidade (UF)" value={form.birthState} change={v=>set("birthState",v.toUpperCase())} maxLength={2}/><Input label="Nome da mãe" value={form.motherName} change={v=>set("motherName",v)}/><Input label="Nome do pai" value={form.fatherName} change={v=>set("fatherName",v)}/><Select label="Estado civil" value={form.maritalStatus} change={v=>set("maritalStatus",v)} options={[["NAO_INFORMADO","Não informado"],["SOLTEIRO","Solteiro(a)"],["CASADO","Casado(a)"],["UNIAO_ESTAVEL","União estável"],["DIVORCIADO","Divorciado(a)"],["VIUVO","Viúvo(a)"],["OUTRO","Outro"]]}/><Input label="Nome do cônjuge" value={form.spouseName} change={v=>set("spouseName",v)}/><Input label="Quantidade de filhos" type="number" value={form.childrenCount} change={v=>set("childrenCount",v)} min="0" max="99"/></Fieldset>
  <Fieldset title="Contato"><Input label="Telefone" value={form.phone} change={v=>set("phone",v)} inputMode="tel"/><Input label="WhatsApp" value={form.whatsapp} change={v=>set("whatsapp",v)} inputMode="tel"/><Input label="E-mail" type="email" value={form.email} change={v=>set("email",v)}/></Fieldset>
  <fieldset><legend>Endereço</legend><div className="form-grid"><label className="field-group"><span>CEP</span><div className="inline-field"><input value={form.postalCode} onChange={e=>set("postalCode",e.target.value)} inputMode="numeric"/><button type="button" className="secondary-button" onClick={()=>void cep()} disabled={busy}><MapPin size={16}/>Buscar</button></div></label><Input label="Logradouro" value={form.street} change={v=>set("street",v)}/><Input label="Número" value={form.addressNumber} change={v=>set("addressNumber",v)}/><Input label="Complemento" value={form.complement} change={v=>set("complement",v)}/><Input label="Bairro" value={form.district} change={v=>set("district",v)}/><Input label="Cidade" value={form.city} change={v=>set("city",v)}/><Input label="UF" value={form.state} change={v=>set("state",v.toUpperCase())} maxLength={2}/></div></fieldset>
  <Fieldset title="Formação e trabalho"><Input label="Profissão" value={form.profession} change={v=>set("profession",v)}/><Input label="Local de trabalho" value={form.workplace} change={v=>set("workplace",v)}/><Select label="Escolaridade" value={form.educationLevel} change={v=>set("educationLevel",v)} options={education}/><Select label="Formação teológica" value={form.theologicalEducation} change={v=>set("theologicalEducation",v)} options={theology}/></Fieldset>
  <Fieldset title="Informações eclesiásticas"><Input label="Igreja de origem" value={form.originChurch} change={v=>set("originChurch",v)}/><Input label="Data de entrada na igreja" type="date" value={form.churchEntryDate} change={v=>set("churchEntryDate",v)}/><Input label="Data de conversão" type="date" value={form.conversionDate} change={v=>set("conversionDate",v)}/><Input label="Data de batismo" type="date" value={form.baptismDate} change={v=>set("baptismDate",v)}/><Input label="Data de consagração" type="date" value={form.consecrationDate} change={v=>set("consecrationDate",v)}/></Fieldset>
  {definition.customFields.length?<fieldset><legend>Informações adicionais</legend><div className="form-grid">{definition.customFields.map(field=>{const key=String(field.id);if(field.fieldType==="LISTA_OPCOES"){const selected=Array.isArray(custom[key])?custom[key]:[];return <fieldset className="field-group custom-options-field form-span-2" key={field.id}><legend>{field.name}{field.required?" *":""}</legend><div className="custom-option-list">{field.options.map(option=><label key={option}><input type="checkbox" checked={selected.includes(option)} onChange={e=>toggle(field.id,option,e.target.checked)}/>{option}</label>)}</div>{field.helpText?<small>{field.helpText}</small>:null}{field.required&&!selected.length?<input className="custom-required-proxy" required aria-label={field.name} value="" onChange={()=>undefined}/>:null}</fieldset>}return <label className={`field-group ${field.fieldType==="TEXTO_LONGO"?"form-span-2":""}`} key={field.id}><span>{field.name}{field.required?" *":""}</span>{field.fieldType==="TEXTO_LONGO"?<textarea required={field.required} value={String(custom[key]??"")} onChange={e=>setCustom({...custom,[key]:e.target.value})}/>:field.fieldType==="SIM_NAO"||field.fieldType==="SELECAO_UNICA"?<select required={field.required} value={String(custom[key]??"")} onChange={e=>setCustom({...custom,[key]:e.target.value})}><option value="">Selecione</option>{(field.fieldType==="SIM_NAO"?[["SIM","Sim"],["NAO","Não"]]:field.options.map(o=>[o,o])).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select>:<input required={field.required} type={field.fieldType==="DATA"?"date":field.fieldType==="NUMERO"?"number":field.fieldType==="EMAIL"?"email":"text"} inputMode={field.fieldType==="TELEFONE"?"tel":undefined} value={String(custom[key]??"")} onChange={e=>setCustom({...custom,[key]:e.target.value})}/>}<small>{field.helpText}</small></label>})}</div></fieldset>:null}
  <label className="public-consent"><input required type="checkbox"/><span>{CONSENT_TEXT}</span></label>{error?<div className="form-error">{error}</div>:null}<button className="primary-button public-submit" disabled={busy}>{busy?<LoaderCircle className="spin"/>:<CheckCircle2/>}Enviar cadastro</button>
 </form></section>{camera?<div className="dialog-backdrop"><section className="dialog-card camera-dialog"><header className="dialog-heading"><h2>Tirar foto</h2><button className="icon-button" onClick={stopCamera} aria-label="Fechar"><X/></button></header>{captured?<img className="camera-preview" src={preview} alt="Foto capturada"/>:<video ref={videoRef} autoPlay playsInline muted/>}<footer className="dialog-actions">{captured?<><button className="secondary-button" onClick={()=>{setCaptured(false);setPhoto(null);setPreview("");}}>Tirar novamente</button><button className="primary-button" onClick={stopCamera}>Usar esta foto</button></>:<><button className="secondary-button" onClick={stopCamera}>Cancelar</button><button className="primary-button" onClick={capture}><Camera/>Tirar foto</button></>}</footer></section></div>:null}</main>;
}
function Fieldset({title,children}:{title:string;children:React.ReactNode}){return <fieldset><legend>{title}</legend><div className="form-grid">{children}</div></fieldset>}
function Input({label,value,change,type="text",required=false,inputMode,min,max,maxLength}:{label:string;value:string;change:(v:string)=>void;type?:string;required?:boolean;inputMode?:"numeric"|"tel";min?:string;max?:string;maxLength?:number}){return <label className="field-group"><span>{label}</span><input type={type} value={value} onChange={e=>change(e.target.value)} required={required} inputMode={inputMode} min={min} max={max} maxLength={maxLength}/></label>}
function Select({label,value,change,options}:{label:string;value:string;change:(v:string)=>void;options:string[][]}){return <label className="field-group"><span>{label}</span><select value={value} onChange={e=>change(e.target.value)}>{options.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>}
