DELETE FROM help_article_reads WHERE article_id BETWEEN 19001 AND 19008;
DELETE FROM help_articles WHERE id BETWEEN 19001 AND 19008;
DROP TABLE IF EXISTS department_audit;
DROP TABLE IF EXISTS ebd_closures;
DROP TABLE IF EXISTS ebd_class_summaries;
DROP TABLE IF EXISTS ebd_visitors;
DROP TABLE IF EXISTS ebd_attendance;
DROP TABLE IF EXISTS ebd_meetings;
DROP TABLE IF EXISTS ebd_enrollments;
DROP TABLE IF EXISTS ebd_class_teachers;
DROP TABLE IF EXISTS ebd_classes;
DROP TABLE IF EXISTS department_communications;
DROP TABLE IF EXISTS department_attendance;
DROP TABLE IF EXISTS department_activities;
DROP TABLE IF EXISTS department_events;
DROP TABLE IF EXISTS department_access;
DROP TABLE IF EXISTS department_participants;
DROP TABLE IF EXISTS department_roles;
DROP TABLE IF EXISTS departments;
