DELETE FROM help_articles WHERE id BETWEEN 22001 AND 22015;
DELETE FROM membership_permissions WHERE permission LIKE 'FINANCEIRO_%';
DELETE FROM user_permissions WHERE permission LIKE 'FINANCEIRO_%';
DROP TABLE IF EXISTS finance_audit;
DROP TABLE IF EXISTS finance_allocation_rule_drafts;
DROP TABLE IF EXISTS finance_attachments;
DROP TABLE IF EXISTS finance_campaign_pledge_installments;
DROP TABLE IF EXISTS finance_campaign_pledges;
DROP TABLE IF EXISTS finance_transfers;
DROP TABLE IF EXISTS finance_installments;
DROP TABLE IF EXISTS finance_obligations;
DROP TABLE IF EXISTS finance_contributions;
DROP TABLE IF EXISTS finance_movements;
DROP TABLE IF EXISTS person_financial_preferences;
DROP TABLE IF EXISTS finance_campaigns;
DROP TABLE IF EXISTS finance_funds;
DROP TABLE IF EXISTS finance_cost_centers;
DROP TABLE IF EXISTS finance_payment_methods;
DROP TABLE IF EXISTS finance_categories;
DROP TABLE IF EXISTS finance_accounts;
