DELETE FROM `help_articles` WHERE `version`='40' AND `id` BETWEEN 29001 AND 29024;
DELETE FROM `membership_permissions` WHERE `permission` IN ('FINANCEIRO_RELATORIOS_VISUALIZAR','FINANCEIRO_RELATORIOS_GERAR','FINANCEIRO_RELATORIOS_IMPRIMIR','FINANCEIRO_RELATORIOS_EXPORTAR','FINANCEIRO_RELATORIOS_MODELOS_VISUALIZAR','FINANCEIRO_RELATORIOS_MODELOS_CONFIGURAR');
DELETE FROM `user_permissions` WHERE `permission` IN ('FINANCEIRO_RELATORIOS_VISUALIZAR','FINANCEIRO_RELATORIOS_GERAR','FINANCEIRO_RELATORIOS_IMPRIMIR','FINANCEIRO_RELATORIOS_EXPORTAR','FINANCEIRO_RELATORIOS_MODELOS_VISUALIZAR','FINANCEIRO_RELATORIOS_MODELOS_CONFIGURAR');
DROP TABLE IF EXISTS `finance_reports`;
DROP TABLE IF EXISTS `finance_report_model_versions`;
DROP TABLE IF EXISTS `finance_report_models`;
