export const PERMISSION_DEFINITIONS = [
  { code: "USUARIOS_VISUALIZAR", label: "Visualizar usuários", group: "Usuários" },
  { code: "USUARIOS_CRIAR", label: "Criar usuários", group: "Usuários" },
  { code: "USUARIOS_EDITAR", label: "Editar usuários", group: "Usuários" },
  { code: "USUARIOS_DESATIVAR", label: "Ativar e desativar usuários", group: "Usuários" },
  { code: "USUARIOS_REDEFINIR_SENHA", label: "Redefinir senha e encerrar sessões", group: "Usuários" },
  { code: "UNIDADES_VISUALIZAR", label: "Visualizar unidades", group: "Unidades" },
  { code: "UNIDADES_CRIAR", label: "Criar unidades", group: "Unidades" },
  { code: "UNIDADES_EDITAR", label: "Editar, ativar e desativar unidades", group: "Unidades" },
  { code: "FUNCOES_VISUALIZAR", label: "Visualizar funções", group: "Funções" },
  { code: "FUNCOES_CRIAR", label: "Criar funções", group: "Funções" },
  { code: "FUNCOES_EDITAR", label: "Editar funções", group: "Funções" },
  { code: "FUNCOES_DESATIVAR", label: "Ativar e desativar funções", group: "Funções" },
  { code: "ACESSOS_VISUALIZAR", label: "Visualizar histórico de acessos", group: "Segurança" },
  { code: "ASSINATURA_VISUALIZAR", label: "Visualizar assinatura e cobranças", group: "Assinatura" },
  { code: "MEMBROS_VISUALIZAR", label: "Visualizar membros", group: "Membros" },
  { code: "MEMBROS_CRIAR", label: "Cadastrar membros", group: "Membros" },
  { code: "MEMBROS_EDITAR", label: "Editar membros", group: "Membros" },
  { code: "MEMBROS_ALTERAR_SITUACAO", label: "Alterar situação de membros", group: "Membros" },
  { code: "MEMBROS_TRANSFERIR", label: "Transferir membros entre unidades", group: "Membros" },
  { code: "MEMBROS_IMPRIMIR", label: "Imprimir ficha de membros", group: "Membros" },
  { code: "MEMBROS_HISTORICO_VISUALIZAR", label: "Visualizar histórico eclesiástico", group: "Membros" },
  { code: "MEMBROS_OBSERVACOES_VISUALIZAR", label: "Visualizar observações internas", group: "Membros" },
  { code: "MEMBROS_OBSERVACOES_EDITAR", label: "Editar observações internas", group: "Membros" },
  { code: "PRECADASTROS_VISUALIZAR", label: "Visualizar pré-cadastros", group: "Pré-cadastros" },
  { code: "PRECADASTROS_ANALISAR", label: "Analisar pré-cadastros", group: "Pré-cadastros" },
  { code: "PRECADASTROS_APROVAR", label: "Aprovar pré-cadastros", group: "Pré-cadastros" },
  { code: "PRECADASTROS_RECUSAR", label: "Recusar pré-cadastros", group: "Pré-cadastros" },
  { code: "CAMPOS_MEMBROS_CONFIGURAR", label: "Configurar campos da ficha", group: "Membros" },
  { code: "FORMULARIOS_PRECADASTRO_GERENCIAR", label: "Gerenciar formulários públicos", group: "Pré-cadastros" },
  { code: "DADOS_EXPORTAR", label: "Exportar dados do próprio escopo", group: "Dados e Backup" },
  { code: "DADOS_EXPORTAR_COMPLETO", label: "Exportar todos os dados da instituição", group: "Dados e Backup" },
  { code: "DEPARTAMENTO_VISUALIZAR", label: "Visualizar departamentos", group: "Departamentos" },
  { code: "DEPARTAMENTO_PARTICIPANTES_VISUALIZAR", label: "Visualizar participantes", group: "Departamentos" },
  { code: "DEPARTAMENTO_PARTICIPANTES_GERENCIAR", label: "Gerenciar participantes", group: "Departamentos" },
  { code: "DEPARTAMENTO_LIDERANCA_GERENCIAR", label: "Gerenciar liderança e acessos", group: "Departamentos" },
  { code: "DEPARTAMENTO_AGENDA_VISUALIZAR", label: "Visualizar agenda departamental", group: "Departamentos" },
  { code: "DEPARTAMENTO_AGENDA_GERENCIAR", label: "Gerenciar agenda departamental", group: "Departamentos" },
  { code: "DEPARTAMENTO_FREQUENCIA_VISUALIZAR", label: "Visualizar frequência departamental", group: "Departamentos" },
  { code: "DEPARTAMENTO_FREQUENCIA_LANCAR", label: "Lançar frequência departamental", group: "Departamentos" },
  { code: "DEPARTAMENTO_COMUNICACAO", label: "Preparar comunicações", group: "Departamentos" },
  { code: "DEPARTAMENTO_RELATORIOS", label: "Visualizar relatórios departamentais", group: "Departamentos" },
  { code: "DEPARTAMENTO_CONFIGURAR", label: "Configurar departamentos", group: "Departamentos" },
  { code: "EBD_VISUALIZAR", label: "Visualizar Escola Bíblica", group: "Escola Bíblica" },
  { code: "EBD_GERENCIAR", label: "Gerenciar Escola Bíblica", group: "Escola Bíblica" },
  { code: "EBD_CLASSES_GERENCIAR", label: "Gerenciar classes e professores", group: "Escola Bíblica" },
  { code: "EBD_ALUNOS_VISUALIZAR", label: "Visualizar alunos", group: "Escola Bíblica" },
  { code: "EBD_ALUNOS_GERENCIAR", label: "Gerenciar matrículas", group: "Escola Bíblica" },
  { code: "EBD_CHAMADA_LANCAR", label: "Fazer chamada das classes atribuídas", group: "Escola Bíblica" },
  { code: "EBD_CHAMADA_CORRIGIR", label: "Corrigir chamadas finalizadas", group: "Escola Bíblica" },
  { code: "EBD_SECRETARIA", label: "Acessar Secretaria da EBD", group: "Escola Bíblica" },
  { code: "EBD_FECHAMENTO", label: "Realizar fechamento da EBD", group: "Escola Bíblica" },
  { code: "EBD_RELATORIOS", label: "Visualizar relatórios da EBD", group: "Escola Bíblica" },
  { code: "EBD_CONFIGURAR", label: "Configurar regras da EBD", group: "Escola Bíblica" },
  { code: "SECRETARIA_VISUALIZAR", label: "Visualizar Secretaria Eclesiástica", group: "Secretaria Eclesiástica" },
  { code: "SECRETARIA_MOVIMENTACOES_VISUALIZAR", label: "Visualizar movimentações e histórico", group: "Secretaria Eclesiástica" },
  { code: "SECRETARIA_MOVIMENTACOES_GERENCIAR", label: "Gerenciar situações eclesiásticas", group: "Secretaria Eclesiástica" },
  { code: "SECRETARIA_TRANSFERENCIAS_SOLICITAR", label: "Solicitar transferências", group: "Secretaria Eclesiástica" },
  { code: "SECRETARIA_TRANSFERENCIAS_APROVAR", label: "Analisar e aprovar transferências", group: "Secretaria Eclesiástica" },
  { code: "SECRETARIA_RECEBIMENTOS_GERENCIAR", label: "Registrar recebimentos", group: "Secretaria Eclesiástica" },
  { code: "SECRETARIA_BATISMOS_GERENCIAR", label: "Gerenciar batismos", group: "Secretaria Eclesiástica" },
  { code: "SECRETARIA_CONSAGRACOES_GERENCIAR", label: "Gerenciar consagrações", group: "Secretaria Eclesiástica" },
  { code: "SECRETARIA_DOCUMENTOS_EMITIR", label: "Emitir documentos eclesiásticos", group: "Secretaria Eclesiástica" },
  { code: "SECRETARIA_DOCUMENTOS_MODELOS_GERENCIAR", label: "Gerenciar modelos de documentos", group: "Secretaria Eclesiástica" },
  { code: "SECRETARIA_RELATORIOS", label: "Visualizar relatórios da Secretaria", group: "Secretaria Eclesiástica" },
  { code: "SECRETARIA_CONFIGURAR", label: "Configurar Secretaria Eclesiástica", group: "Secretaria Eclesiástica" },
  { code: "FINANCEIRO_VISUALIZAR", label: "Visualizar Financeiro", group: "Financeiro" },
  { code: "FINANCEIRO_LANCAMENTOS_CRIAR", label: "Criar lançamentos", group: "Financeiro" },
  { code: "FINANCEIRO_LANCAMENTOS_EDITAR_ABERTO", label: "Editar lançamentos antes do fechamento", group: "Financeiro" },
  { code: "FINANCEIRO_LANCAMENTOS_EXCLUIR_ABERTO", label: "Excluir lançamentos antes do fechamento", group: "Financeiro" },
  { code: "FINANCEIRO_LANCAMENTOS_ESTORNAR", label: "Estornar lançamentos", group: "Financeiro" },
  { code: "FINANCEIRO_CONTRIBUINTES_FILIAIS_PESQUISAR", label: "Pesquisar contribuintes das Filiais", group: "Financeiro" },
  { code: "FINANCEIRO_CONTRIBUICOES_VISUALIZAR", label: "Visualizar contribuições", group: "Financeiro" },
  { code: "FINANCEIRO_CONTRIBUICOES_GERENCIAR", label: "Gerenciar contribuições", group: "Financeiro" },
  { code: "FINANCEIRO_DESPESAS_GERENCIAR", label: "Gerenciar despesas", group: "Financeiro" },
  { code: "FINANCEIRO_CONTAS_PAGAR_GERENCIAR", label: "Gerenciar contas a pagar", group: "Financeiro" },
  { code: "FINANCEIRO_CONTAS_RECEBER_GERENCIAR", label: "Gerenciar contas a receber", group: "Financeiro" },
  { code: "FINANCEIRO_TRANSFERENCIAS_GERENCIAR", label: "Gerenciar transferências", group: "Financeiro" },
  { code: "FINANCEIRO_CAMPANHAS_GERENCIAR", label: "Gerenciar campanhas e fundos", group: "Financeiro" },
  { code: "FINANCEIRO_CONTAS_CONFIGURAR", label: "Configurar contas financeiras", group: "Financeiro" },
  { code: "FINANCEIRO_CATEGORIAS_CONFIGURAR", label: "Configurar categorias", group: "Financeiro" },
  { code: "FINANCEIRO_CONFIGURAR", label: "Configurar Financeiro", group: "Financeiro" },
  { code: "FINANCEIRO_AUDITORIA_VISUALIZAR", label: "Visualizar auditoria financeira", group: "Financeiro" },
  { code: "FINANCEIRO_CAIXA_ABRIR", label: "Abrir períodos financeiros", group: "Financeiro" },
  { code: "FINANCEIRO_CAIXA_FECHAR", label: "Fechar períodos financeiros", group: "Financeiro" },
  { code: "FINANCEIRO_CAIXA_REABRIR", label: "Reabrir caixa pela Matriz", group: "Financeiro" },
  { code: "FINANCEIRO_CAIXA_REABERTURA_SOLICITAR", label: "Solicitar reabertura de caixa", group: "Financeiro" },
  { code: "FINANCEIRO_CAIXA_REABERTURA_APROVAR", label: "Aprovar reabertura solicitada", group: "Financeiro" },
  { code: "FINANCEIRO_RATEIO_VISUALIZAR", label: "Visualizar configuração de rateio", group: "Financeiro" },
  { code: "FINANCEIRO_RATEIO_CONFIGURAR", label: "Configurar rateio por unidade", group: "Financeiro" },
  { code: "FINANCEIRO_RATEIO_PERIODO_ALTERAR", label: "Alterar rateio de período reaberto", group: "Financeiro" },
  { code: "FINANCEIRO_LANCAMENTO_RAPIDO", label: "Usar lançamento rápido", group: "Financeiro" },
  { code: "FINANCEIRO_RELATORIOS_VISUALIZAR", label: "Visualizar relatórios financeiros", group: "Financeiro" },
  { code: "FINANCEIRO_RELATORIOS_GERAR", label: "Gerar relatórios financeiros", group: "Financeiro" },
  { code: "FINANCEIRO_RELATORIOS_IMPRIMIR", label: "Imprimir relatórios financeiros", group: "Financeiro" },
  { code: "FINANCEIRO_RELATORIOS_EXPORTAR", label: "Exportar relatórios financeiros", group: "Financeiro" },
  { code: "FINANCEIRO_RELATORIOS_MODELOS_VISUALIZAR", label: "Visualizar modelos de relatórios", group: "Financeiro" },
  { code: "FINANCEIRO_RELATORIOS_MODELOS_CONFIGURAR", label: "Configurar modelos de relatórios", group: "Financeiro" },
] as const;

export type PermissionCode = (typeof PERMISSION_DEFINITIONS)[number]["code"];
export const PERMISSION_CODES = PERMISSION_DEFINITIONS.map((item) => item.code) as PermissionCode[];

export function isPermissionCode(value: unknown): value is PermissionCode {
  return typeof value === "string" && PERMISSION_CODES.includes(value as PermissionCode);
}

export const ADMIN_ROUTE_PERMISSIONS = {
  "/painel/membros/pre-cadastros": "PRECADASTROS_VISUALIZAR",
  "/painel/membros/configuracao": "CAMPOS_MEMBROS_CONFIGURAR",
  "/painel/membros/formularios": "FORMULARIOS_PRECADASTRO_GERENCIAR",
  "/painel/usuarios": "USUARIOS_VISUALIZAR",
  "/painel/unidades": "UNIDADES_VISUALIZAR",
  "/painel/funcoes": "FUNCOES_VISUALIZAR",
  "/painel/acessos": "ACESSOS_VISUALIZAR",
  "/painel/assinatura": "ASSINATURA_VISUALIZAR",
  "/painel/membros": "MEMBROS_VISUALIZAR",
  "/painel/dados-exportacao": "DADOS_EXPORTAR",
  "/painel/departamentos": "DEPARTAMENTO_VISUALIZAR",
  "/painel/secretaria": "SECRETARIA_VISUALIZAR",
  "/painel/financeiro": "FINANCEIRO_VISUALIZAR",
} as const satisfies Record<string, PermissionCode>;

export function permissionForAdminPath(pathname: string): PermissionCode | null {
  const match = Object.entries(ADMIN_ROUTE_PERMISSIONS).sort(([a],[b])=>b.length-a.length)
    .find(([path]) => pathname === path || pathname.startsWith(`${path}/`));
  return match?.[1] ?? null;
}

export function hasPermission(permissions: readonly PermissionCode[], required: PermissionCode): boolean {
  return permissions.includes(required);
}
