// AUTO-GENERATED by scripts/generate-mysql-schema.mjs.
// Do not edit this file directly. Update db/schema.ts and regenerate instead.
// Conditional unique constraints that MySQL cannot model as partial indexes
// are applied by database/mysql/003_partial_unique_constraints.sql.

import {
  boolean,
  check,
  customType,
  foreignKey,
  index,
  int,
  json,
  mysqlTable,
  primaryKey,
  text,
  uniqueIndex,
  varchar,
  type AnyMySqlColumn,
} from "drizzle-orm/mysql-core";

const longBlob = customType<{ data: Buffer; driverData: Buffer }>({
  dataType() {
    return "LONGBLOB";
  },
});
import { sql } from "drizzle-orm";

export const matrices = mysqlTable("matrices", {
  id: int("id").primaryKey(),
  conventionId: int("convention_id").notNull(),
  name: varchar("name", { length: 255 }).notNull(),
  status: varchar("status", { length: 80 }).notNull().default("ATIVO"),
});

export const branches = mysqlTable("branches", {
  id: int("id").primaryKey(),
  matrixId: int("matrix_id")
    .notNull()
    .references(() => matrices.id),
  name: varchar("name", { length: 255 }).notNull(),
  status: varchar("status", { length: 80 }).notNull().default("ATIVO"),
});

export const users = mysqlTable("users", {
  id: int("id").primaryKey(),
  conventionId: int("convention_id").notNull(),
  name: varchar("name", { length: 255 }).notNull(),
  username: varchar("username", { length: 100 }).notNull().unique(),
  email: varchar("email", { length: 254 }).notNull().unique(),
  cpf: varchar("cpf", { length: 32 }).notNull().unique(),
  passwordSalt: varchar("password_salt", { length: 255 }).notNull(),
  passwordHash: varchar("password_hash", { length: 255 }).notNull(),
  roleName: varchar("role_name", { length: 255 }).notNull(),
  scope: varchar("scope", { length: 80 }).notNull(),
  boundMatrixId: int("bound_matrix_id"),
  boundBranchId: int("bound_branch_id"),
  status: varchar("status", { length: 80 }).notNull().default("ATIVO"),
  mustChangePassword: boolean("must_change_password")
    .notNull()
    .default(false),
  failedAttempts: int("failed_attempts").notNull().default(0),
  blockedUntil: varchar("blocked_until", { length: 40 }),
  lastLoginAt: varchar("last_login_at", { length: 40 }),
  lastIdentifierType: varchar("last_identifier_type", { length: 80 }),
  lastOriginSummary: varchar("last_origin_summary", { length: 191 }),
});

export const sessions = mysqlTable("sessions", {
  id: varchar("id", { length: 191 }).primaryKey(),
  tokenHash: varchar("token_hash", { length: 191 }).notNull().unique(),
  userId: int("user_id")
    .notNull()
    .references(() => users.id),
  activeMatrixId: int("active_matrix_id"),
  activeBranchId: int("active_branch_id"),
  previousLoginAt: varchar("previous_login_at", { length: 40 }),
  previousIdentifierType: varchar("previous_identifier_type", { length: 80 }),
  previousOriginSummary: varchar("previous_origin_summary", { length: 191 }),
  expiresAt: varchar("expires_at", { length: 40 }).notNull(),
  createdAt: varchar("created_at", { length: 40 }).notNull(),
  lastSeenAt: varchar("last_seen_at", { length: 40 }).notNull(),
});

export const auditLogs = mysqlTable("audit_logs", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("user_id"),
  tenantId: int("tenant_id"),
  event: varchar("event", { length: 191 }).notNull(),
  identifierType: varchar("identifier_type", { length: 80 }),
  reason: varchar("reason", { length: 191 }).notNull(),
  matrixId: int("matrix_id"),
  branchId: int("branch_id"),
  createdAt: varchar("created_at", { length: 40 }).notNull(),
});

export const tenants = mysqlTable("tenants", {
  id: int("id").primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  slug: varchar("slug", { length: 191 }).notNull().unique(),
  accessCode: varchar("access_code", { length: 191 }).notNull().unique(),
  status: varchar("status", { length: 80 }).notNull().default("ATIVO"),
  createdAt: varchar("created_at", { length: 40 }).notNull(),
  updatedAt: varchar("updated_at", { length: 40 }).notNull(),
});

// Auth foundation v2. The legacy tables above are intentionally retained so
// existing Site databases can receive this migration without destructive
// renames or data loss.
export const organizationalUnits = mysqlTable(
  "organizational_units",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id")
      .notNull()
      .references(() => tenants.id),
    type: varchar("type", { length: 80 }).notNull(),
    name: varchar("name", { length: 255 }).notNull(),
    fantasyName: varchar("fantasy_name", { length: 255 }),
    legalName: varchar("legal_name", { length: 255 }),
    cnpj: varchar("cnpj", { length: 32 }),
    usesParentCnpj: boolean("uses_parent_cnpj")
      .notNull()
      .default(false),
    phone: varchar("phone", { length: 40 }),
    whatsapp: varchar("whatsapp", { length: 40 }),
    email: varchar("email", { length: 254 }),
    postalCode: varchar("postal_code", { length: 20 }),
    street: varchar("street", { length: 191 }),
    number: varchar("number", { length: 191 }),
    complement: varchar("complement", { length: 191 }),
    district: varchar("district", { length: 191 }),
    city: varchar("city", { length: 191 }),
    state: varchar("state", { length: 191 }),
    responsibleName: varchar("responsible_name", { length: 255 }),
    foundationDate: varchar("foundation_date", { length: 40 }),
    notes: text("notes"),
    code: varchar("code", { length: 191 }).notNull().unique(),
    parentId: int("parent_id").references(
      (): AnyMySqlColumn => organizationalUnits.id,
    ),
    status: varchar("status", { length: 80 }).notNull().default("ATIVO"),
    archivedAt: varchar("archived_at", { length: 40 }),
    archivedBy: int("archived_by"),
    archivedPreviousStatus: varchar("archived_previous_status", { length: 80 }),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    uniqueIndex("organizational_units_id_tenant_unique").on(
      table.id,
      table.tenantId,
    ),
    uniqueIndex("organizational_units_hierarchy_scope_unique").on(
      table.id,
      table.parentId,
      table.tenantId,
    ),
  ],
);

export const organizationalFunctions = mysqlTable(
  "organizational_functions",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id")
      .notNull()
      .references(() => tenants.id),
    name: varchar("name", { length: 255 }).notNull(),
    normalizedName: varchar("normalized_name", { length: 255 }).notNull(),
    description: text("description"),
    status: varchar("status", { length: 80 }).notNull().default("ATIVO"),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    uniqueIndex("organizational_functions_tenant_name_unique").on(
      table.tenantId,
      table.normalizedName,
    ),
    uniqueIndex("organizational_functions_id_tenant_unique").on(
      table.id,
      table.tenantId,
    ),
  ],
);

export const authUsers = mysqlTable(
  "auth_users",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id").references(() => tenants.id),
    name: varchar("name", { length: 255 }).notNull(),
    username: varchar("username", { length: 100 }).notNull(),
    email: varchar("email", { length: 254 }).notNull(),
    cpf: varchar("cpf", { length: 32 }).notNull(),
    passwordHash: varchar("password_hash", { length: 255 }).notNull(),
    roleName: varchar("role_name", { length: 255 }).notNull(),
    scope: varchar("scope", { length: 80 }).notNull(),
    status: varchar("status", { length: 80 }).notNull().default("ATIVO"),
    mustChangePassword: boolean("must_change_password")
      .notNull()
      .default(false),
    failedAttempts: int("failed_attempts").notNull().default(0),
    blockedUntil: varchar("blocked_until", { length: 40 }),
    archivedAt: varchar("archived_at", { length: 40 }),
    archivedBy: int("archived_by"),
    archivedPreviousStatus: varchar("archived_previous_status", { length: 80 }),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    uniqueIndex("auth_users_tenant_username_unique")
      .on(table.tenantId, table.username),
    uniqueIndex("auth_users_tenant_email_unique")
      .on(table.tenantId, table.email),
    uniqueIndex("auth_users_tenant_cpf_unique")
      .on(table.tenantId, table.cpf),
  ],
);

export const userUnitLinks = mysqlTable(
  "user_unit_links",
  {
    userId: int("user_id")
      .notNull()
      .references(() => authUsers.id),
    unitId: int("unit_id")
      .notNull()
      .references(() => organizationalUnits.id),
    isPrimary: boolean("is_primary")
      .notNull()
      .default(true),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
  },
  (table) => [primaryKey({ columns: [table.userId, table.unitId] })],
);

// Organizational identities and credentials are tenant-owned. The nullable
// tenant is reserved exclusively for the singleton Platform Owner identity.
export const tenantMemberships = mysqlTable(
  "tenant_memberships",
  {
    id: int("id").primaryKey(),
    userId: int("user_id")
      .notNull()
      .references(() => authUsers.id),
    tenantId: int("tenant_id")
      .notNull()
      .references(() => tenants.id),
    displayName: varchar("display_name", { length: 255 }).notNull(),
    roleName: varchar("role_name", { length: 255 }).notNull(),
    functionId: int("function_id").references(
      () => organizationalFunctions.id,
    ),
    scope: varchar("scope", { length: 80 }).notNull(),
    scopeUnitId: int("scope_unit_id")
      .notNull()
      .references(() => organizationalUnits.id),
    status: varchar("status", { length: 80 }).notNull().default("ATIVO"),
    invitedByMembershipId: int("invited_by_membership_id"),
    acceptedAt: varchar("accepted_at", { length: 40 }),
    archivedAt: varchar("archived_at", { length: 40 }),
    archivedByMembershipId: int("archived_by_membership_id"),
    archivedPreviousStatus: varchar("archived_previous_status", { length: 80 }),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    uniqueIndex("tenant_memberships_user_tenant_unique").on(
      table.userId,
      table.tenantId,
    ),
  ],
);

export const membershipPermissions = mysqlTable(
  "membership_permissions",
  {
    membershipId: int("membership_id")
      .notNull()
      .references(() => tenantMemberships.id),
    permission: varchar("permission", { length: 191 }).notNull(),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
  },
  (table) => [primaryKey({ columns: [table.membershipId, table.permission] })],
);

export const authSessions = mysqlTable("auth_sessions", {
  id: varchar("id", { length: 191 }).primaryKey(),
  tokenHash: varchar("token_hash", { length: 191 }).notNull().unique(),
  userId: int("user_id")
    .notNull()
    .references(() => authUsers.id),
  tenantId: int("tenant_id").references(() => tenants.id),
  membershipId: int("membership_id").references(() => tenantMemberships.id),
  organizationSelectionRequired: boolean("organization_selection_required")
    .notNull()
    .default(false),
  platformContextActive: boolean("platform_context_active")
    .notNull()
    .default(false),
  selectedUnitId: int("selected_unit_id").references(
    () => organizationalUnits.id,
  ),
  previousLoginAt: varchar("previous_login_at", { length: 40 }),
  previousIdentifierType: varchar("previous_identifier_type", { length: 80 }),
  previousDeviceSummary: varchar("previous_device_summary", { length: 191 }),
  expiresAt: varchar("expires_at", { length: 40 }).notNull(),
  createdAt: varchar("created_at", { length: 40 }).notNull(),
  lastSeenAt: varchar("last_seen_at", { length: 40 }).notNull(),
});

export const tenantAccessContexts = mysqlTable("tenant_access_contexts", {
  tokenHash: varchar("token_hash", { length: 191 }).primaryKey(),
  tenantId: int("tenant_id")
    .notNull()
    .references(() => tenants.id),
  expiresAt: varchar("expires_at", { length: 40 }).notNull(),
  createdAt: varchar("created_at", { length: 40 }).notNull(),
  lastUsedAt: varchar("last_used_at", { length: 40 }).notNull(),
});

export const institutionLookupAttempts = mysqlTable(
  "institution_lookup_attempts",
  {
    id: int("id").autoincrement().primaryKey(),
    codeFingerprint: varchar("code_fingerprint", { length: 191 }).notNull(),
    success: boolean("success").notNull(),
    ipAddress: varchar("ip_address", { length: 191 }),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
  },
);

export const loginHistory = mysqlTable("login_history", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("user_id").references(() => authUsers.id),
  tenantId: int("tenant_id").references(() => tenants.id),
  identifierType: varchar("identifier_type", { length: 80 }).notNull(),
  identifierFingerprint: varchar("identifier_fingerprint", { length: 191 }).notNull(),
  success: boolean("success").notNull(),
  failureReason: varchar("failure_reason", { length: 191 }),
  ipAddress: varchar("ip_address", { length: 191 }),
  userAgent: text("user_agent"),
  deviceSummary: varchar("device_summary", { length: 191 }),
  createdAt: varchar("created_at", { length: 40 }).notNull(),
});

export const userPermissions = mysqlTable(
  "user_permissions",
  {
    userId: int("user_id")
      .notNull()
      .references(() => authUsers.id),
    permission: varchar("permission", { length: 191 }).notNull(),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
  },
  (table) => [primaryKey({ columns: [table.userId, table.permission] })],
);

export const administrationAudit = mysqlTable("administration_audit", {
  id: int("id").autoincrement().primaryKey(),
  actorUserId: int("actor_user_id")
    .notNull()
    .references(() => authUsers.id),
  actorMembershipId: int("actor_membership_id").references(
    () => tenantMemberships.id,
  ),
  tenantId: int("tenant_id")
    .notNull()
    .references(() => tenants.id),
  conventionId: int("convention_id")
    .notNull()
    .references(() => organizationalUnits.id),
  action: varchar("action", { length: 191 }).notNull(),
  entityType: varchar("entity_type", { length: 80 }).notNull(),
  entityId: int("entity_id").notNull(),
  unitId: int("unit_id").references(() => organizationalUnits.id),
  ipAddress: varchar("ip_address", { length: 191 }),
  userAgent: text("user_agent"),
  deviceSummary: varchar("device_summary", { length: 191 }),
  details: text("details"),
  createdAt: varchar("created_at", { length: 40 }).notNull(),
});

export const unitLogos = mysqlTable("unit_logos", {
  unitId: int("unit_id")
    .primaryKey()
    .references(() => organizationalUnits.id),
  imageData: longBlob("image_data").notNull(),
  mimeType: varchar("mime_type", { length: 80 }).notNull(),
  byteSize: int("byte_size").notNull(),
  updatedAt: varchar("updated_at", { length: 40 }).notNull(),
});

export const userProfilePhotos = mysqlTable("user_profile_photos", {
  userId: int("user_id")
    .primaryKey()
    .references(() => authUsers.id),
  imageData: longBlob("image_data").notNull(),
  mimeType: varchar("mime_type", { length: 80 }).notNull(),
  byteSize: int("byte_size").notNull(),
  updatedAt: varchar("updated_at", { length: 40 }).notNull(),
});

// Platform ownership is deliberately isolated from user_permissions. The
// singleton constraint prevents a normal administrative flow from delegating
// or multiplying this platform-level authority.
export const platformOwners = mysqlTable(
  "platform_owners",
  {
    singletonId: int("singleton_id").primaryKey().default(1),
    userId: int("user_id")
      .notNull()
      .references(() => authUsers.id),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    check("platform_owners_singleton_check", sql`${table.singletonId} = 1`),
    uniqueIndex("platform_owners_user_unique").on(table.userId),
  ],
);

// Unit references intentionally have no foreign keys so the audit trail
// survives the exceptional physical deletion of an empty/test unit.
export const platformAudit = mysqlTable("platform_audit", {
  id: int("id").autoincrement().primaryKey(),
  actorUserId: int("actor_user_id")
    .notNull()
    .references(() => authUsers.id),
  tenantId: int("tenant_id").references(() => tenants.id),
  action: varchar("action", { length: 191 }).notNull(),
  entityType: varchar("entity_type", { length: 80 }).notNull(),
  entityId: int("entity_id").notNull(),
  conventionId: int("convention_id"),
  unitId: int("unit_id"),
  ipAddress: varchar("ip_address", { length: 191 }),
  userAgent: text("user_agent"),
  deviceSummary: varchar("device_summary", { length: 191 }),
  details: text("details"),
  createdAt: varchar("created_at", { length: 40 }).notNull(),
});

// Commercial SaaS domain. These tables are deliberately separate from every
// future church cash-flow, tithe, offering, income or expense table.
export const commercialProfiles = mysqlTable("commercial_profiles", {
  tenantId: int("tenant_id")
    .primaryKey()
    .references(() => tenants.id),
  personType: varchar("person_type", { length: 80 }).notNull(),
  legalName: varchar("legal_name", { length: 255 }).notNull(),
  document: varchar("document", { length: 191 }),
  responsibleName: varchar("responsible_name", { length: 255 }),
  phone: varchar("phone", { length: 40 }),
  billingEmail: varchar("billing_email", { length: 254 }),
  notes: text("notes"),
  customerSince: varchar("customer_since", { length: 40 }).notNull(),
  createdAt: varchar("created_at", { length: 40 }).notNull(),
  updatedAt: varchar("updated_at", { length: 40 }).notNull(),
});

export const saasPlans = mysqlTable(
  "saas_plans",
  {
    id: int("id").primaryKey(),
    name: varchar("name", { length: 255 }).notNull(),
    description: text("description"),
    priceCents: int("price_cents").notNull(),
    billingPeriod: varchar("billing_period", { length: 191 }).notNull(),
    defaultGraceDays: int("default_grace_days").notNull().default(5),
    defaultTrialDays: int("default_trial_days").notNull().default(15),
    status: varchar("status", { length: 80 }).notNull().default("ATIVO"),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [uniqueIndex("saas_plans_name_unique").on(table.name)],
);

export const billingSettings = mysqlTable("billing_settings", {
  singletonId: int("singleton_id").primaryKey().default(1),
  warningDays: int("warning_days").notNull().default(7),
  pixKey: varchar("pix_key", { length: 191 }),
  pixKeyType: varchar("pix_key_type", { length: 80 }),
  payeeName: varchar("payee_name", { length: 255 }),
  bankName: varchar("bank_name", { length: 255 }),
  bankAgency: varchar("bank_agency", { length: 191 }),
  bankAccount: varchar("bank_account", { length: 191 }),
  instructions: text("instructions"),
  supportContact: varchar("support_contact", { length: 191 }),
  updatedAt: varchar("updated_at", { length: 40 }).notNull(),
});

export const tenantSubscriptions = mysqlTable("tenant_subscriptions", {
  id: int("id").primaryKey(),
  tenantId: int("tenant_id")
    .notNull()
    .unique()
    .references(() => tenants.id),
  planId: int("plan_id").references(() => saasPlans.id),
  contractedPriceCents: int("contracted_price_cents").notNull().default(0),
  customPriceCents: int("custom_price_cents"),
  billingPeriod: varchar("billing_period", { length: 191 }).notNull(),
  status: varchar("status", { length: 80 }).notNull(),
  startDate: varchar("start_date", { length: 40 }).notNull(),
  nextDueDate: varchar("next_due_date", { length: 40 }),
  dueDay: int("due_day"),
  graceDays: int("grace_days").notNull().default(5),
  trialStartDate: varchar("trial_start_date", { length: 40 }),
  trialEndDate: varchar("trial_end_date", { length: 40 }),
  accessUntil: varchar("access_until", { length: 40 }),
  autoRenew: boolean("auto_renew").notNull().default(true),
  notes: text("notes"),
  suspendedReason: varchar("suspended_reason", { length: 191 }),
  paymentProvider: varchar("payment_provider", { length: 191 }).notNull().default("MANUAL"),
  providerCustomerId: varchar("provider_customer_id", { length: 191 }),
  providerSubscriptionId: varchar("provider_subscription_id", { length: 191 }),
  externalReference: varchar("external_reference", { length: 191 }),
  createdAt: varchar("created_at", { length: 40 }).notNull(),
  updatedAt: varchar("updated_at", { length: 40 }).notNull(),
});

export const saasCharges = mysqlTable(
  "saas_charges",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id")
      .notNull()
      .references(() => tenants.id),
    subscriptionId: int("subscription_id")
      .notNull()
      .references(() => tenantSubscriptions.id),
    competence: varchar("competence", { length: 16 }).notNull(),
    description: text("description").notNull(),
    amountCents: int("amount_cents").notNull(),
    issuedDate: varchar("issued_date", { length: 40 }).notNull(),
    dueDate: varchar("due_date", { length: 40 }).notNull(),
    status: varchar("status", { length: 80 }).notNull().default("PENDENTE"),
    paidAt: varchar("paid_at", { length: 40 }),
    paymentMethod: varchar("payment_method", { length: 191 }),
    notes: text("notes"),
    paymentProvider: varchar("payment_provider", { length: 191 }).notNull().default("MANUAL"),
    providerChargeId: varchar("provider_charge_id", { length: 191 }),
    externalReference: varchar("external_reference", { length: 191 }),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    uniqueIndex("saas_charges_subscription_due_unique").on(
      table.subscriptionId,
      table.dueDate,
    ),
  ],
);

export const saasPayments = mysqlTable("saas_payments", {
  id: int("id").primaryKey(),
  tenantId: int("tenant_id")
    .notNull()
    .references(() => tenants.id),
  subscriptionId: int("subscription_id")
    .notNull()
    .references(() => tenantSubscriptions.id),
  chargeId: int("charge_id")
    .notNull()
    .unique()
    .references(() => saasCharges.id),
  amountCents: int("amount_cents").notNull(),
  paidDate: varchar("paid_date", { length: 40 }).notNull(),
  paymentMethod: varchar("payment_method", { length: 191 }).notNull(),
  notes: text("notes"),
  paymentProvider: varchar("payment_provider", { length: 191 }).notNull().default("MANUAL"),
  providerPaymentId: varchar("provider_payment_id", { length: 191 }),
  externalReference: varchar("external_reference", { length: 191 }).unique(),
  createdBy: int("created_by")
    .notNull()
    .references(() => authUsers.id),
  createdAt: varchar("created_at", { length: 40 }).notNull(),
});

export const commercialAudit = mysqlTable("commercial_audit", {
  id: int("id").autoincrement().primaryKey(),
  actorUserId: int("actor_user_id")
    .notNull()
    .references(() => authUsers.id),
  tenantId: int("tenant_id")
    .notNull()
    .references(() => tenants.id),
  action: varchar("action", { length: 191 }).notNull(),
  entityType: varchar("entity_type", { length: 80 }).notNull(),
  entityId: int("entity_id").notNull(),
  previousValues: text("previous_values"),
  newValues: text("new_values"),
  reason: varchar("reason", { length: 191 }),
  createdAt: varchar("created_at", { length: 40 }).notNull(),
});

// Church people are intentionally independent from authentication identities.
export const memberSequences = mysqlTable("member_sequences", {
  tenantId: int("tenant_id")
    .primaryKey()
    .references(() => tenants.id),
  lastNumber: int("last_number").notNull().default(0),
  updatedAt: varchar("updated_at", { length: 40 }).notNull(),
});

export const people = mysqlTable(
  "people",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id")
      .notNull()
      .references(() => tenants.id),
    memberNumber: int("member_number").notNull(),
    fullName: varchar("full_name", { length: 255 }).notNull(),
    status: varchar("status", { length: 80 }).notNull().default("MEMBRO_ATIVO"),
    birthDate: varchar("birth_date", { length: 40 }),
    sex: varchar("sex", { length: 191 }),
    cpf: varchar("cpf", { length: 32 }),
    rg: varchar("rg", { length: 191 }),
    voterTitle: varchar("voter_title", { length: 32 }),
    birthCity: varchar("birth_city", { length: 191 }),
    birthState: varchar("birth_state", { length: 191 }),
    phone: varchar("phone", { length: 40 }),
    whatsapp: varchar("whatsapp", { length: 40 }),
    email: varchar("email", { length: 254 }),
    motherName: varchar("mother_name", { length: 255 }),
    fatherName: varchar("father_name", { length: 255 }),
    maritalStatus: varchar("marital_status", { length: 80 }),
    spouseName: varchar("spouse_name", { length: 255 }),
    spousePersonId: int("spouse_person_id"),
    childrenCount: int("children_count").notNull().default(0),
    postalCode: varchar("postal_code", { length: 20 }),
    street: varchar("street", { length: 191 }),
    addressNumber: varchar("address_number", { length: 191 }),
    complement: varchar("complement", { length: 191 }),
    district: varchar("district", { length: 191 }),
    city: varchar("city", { length: 191 }),
    state: varchar("state", { length: 191 }),
    profession: varchar("profession", { length: 191 }),
    workplace: varchar("workplace", { length: 191 }),
    educationLevel: varchar("education_level", { length: 191 }),
    theologicalEducation: text("theological_education"),
    primaryFunctionId: int("primary_function_id"),
    matrixId: int("matrix_id").notNull(),
    branchId: int("branch_id"),
    churchEntryDate: varchar("church_entry_date", { length: 40 }),
    originChurch: varchar("origin_church", { length: 191 }),
    conversionDate: varchar("conversion_date", { length: 40 }),
    baptismDate: varchar("baptism_date", { length: 40 }),
    consecrationDate: varchar("consecration_date", { length: 40 }),
    notes: text("notes"),
    linkedAuthUserId: int("linked_auth_user_id").references(
      () => authUsers.id,
    ),
    createdByUserId: int("created_by_user_id")
      .notNull()
      .references(() => authUsers.id),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    uniqueIndex("people_tenant_member_number_unique").on(
      table.tenantId,
      table.memberNumber,
    ),
    uniqueIndex("people_tenant_cpf_unique")
      .on(table.tenantId, table.cpf),
    index("people_tenant_voter_title_idx").on(table.tenantId, table.voterTitle),
    uniqueIndex("people_id_tenant_unique").on(table.id, table.tenantId),
    foreignKey({
      columns: [table.spousePersonId, table.tenantId],
      foreignColumns: [table.id, table.tenantId],
      name: "people_spouse_tenant_fk",
    }),
    foreignKey({
      columns: [table.primaryFunctionId, table.tenantId],
      foreignColumns: [
        organizationalFunctions.id,
        organizationalFunctions.tenantId,
      ],
      name: "people_function_tenant_fk",
    }),
    foreignKey({
      columns: [table.matrixId, table.tenantId],
      foreignColumns: [organizationalUnits.id, organizationalUnits.tenantId],
      name: "people_matrix_tenant_fk",
    }),
    foreignKey({
      columns: [table.branchId, table.matrixId, table.tenantId],
      foreignColumns: [
        organizationalUnits.id,
        organizationalUnits.parentId,
        organizationalUnits.tenantId,
      ],
      name: "people_branch_matrix_tenant_fk",
    }),
  ],
);

export const personFunctions = mysqlTable(
  "person_functions",
  {
    personId: int("person_id").notNull(),
    tenantId: int("tenant_id").notNull(),
    functionId: int("function_id").notNull(),
    isPrimary: boolean("is_primary")
      .notNull()
      .default(false),
    startedAt: varchar("started_at", { length: 40 }),
    endedAt: varchar("ended_at", { length: 40 }),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.personId, table.functionId] }),
    foreignKey({
      columns: [table.personId, table.tenantId],
      foreignColumns: [people.id, people.tenantId],
      name: "person_functions_person_tenant_fk",
    }),
    foreignKey({
      columns: [table.functionId, table.tenantId],
      foreignColumns: [
        organizationalFunctions.id,
        organizationalFunctions.tenantId,
      ],
      name: "person_functions_function_tenant_fk",
    }),
  ],
);

export const personHistory = mysqlTable(
  "person_history",
  {
    id: int("id").autoincrement().primaryKey(),
    tenantId: int("tenant_id")
      .notNull()
      .references(() => tenants.id),
    personId: int("person_id").notNull(),
    eventType: varchar("event_type", { length: 80 }).notNull(),
    description: text("description").notNull(),
    eventDate: varchar("event_date", { length: 40 }),
    previousValues: text("previous_values"),
    newValues: text("new_values"),
    actorUserId: int("actor_user_id")
      .notNull()
      .references(() => authUsers.id),
    actorMembershipId: int("actor_membership_id").references(
      () => tenantMemberships.id,
    ),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.personId, table.tenantId],
      foreignColumns: [people.id, people.tenantId],
      name: "person_history_person_tenant_fk",
    }),
  ],
);

export const personRelationships = mysqlTable(
  "person_relationships",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id")
      .notNull()
      .references(() => tenants.id),
    personId: int("person_id").notNull(),
    relatedPersonId: int("related_person_id").notNull(),
    relationshipType: varchar("relationship_type", { length: 80 }).notNull(),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
  },
  (table) => [
    uniqueIndex("person_relationships_unique").on(
      table.personId,
      table.relatedPersonId,
      table.relationshipType,
    ),
    foreignKey({
      columns: [table.personId, table.tenantId],
      foreignColumns: [people.id, people.tenantId],
      name: "person_relationships_person_tenant_fk",
    }),
    foreignKey({
      columns: [table.relatedPersonId, table.tenantId],
      foreignColumns: [people.id, people.tenantId],
      name: "person_relationships_related_tenant_fk",
    }),
  ],
);

export const memberPhotos = mysqlTable(
  "member_photos",
  {
    personId: int("person_id").primaryKey(),
    tenantId: int("tenant_id")
      .notNull()
      .references(() => tenants.id),
    imageData: longBlob("image_data").notNull(),
    mimeType: varchar("mime_type", { length: 80 }).notNull(),
    byteSize: int("byte_size").notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.personId, table.tenantId],
      foreignColumns: [people.id, people.tenantId],
      name: "member_photos_person_tenant_fk",
    }),
  ],
);

export const memberCustomFields = mysqlTable(
  "member_custom_fields",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id")
      .notNull()
      .references(() => tenants.id),
    name: varchar("name", { length: 255 }).notNull(),
    normalizedName: varchar("normalized_name", { length: 255 }).notNull(),
    fieldType: varchar("field_type", { length: 80 }).notNull(),
    helpText: text("help_text"),
    required: boolean("required").notNull().default(false),
    status: varchar("status", { length: 80 }).notNull().default("ATIVO"),
    displayOrder: int("display_order").notNull().default(0),
    sectionName: varchar("section_name", { length: 255 })
      .notNull()
      .default("Informações adicionais"),
    showAdmin: boolean("show_admin")
      .notNull()
      .default(true),
    showPublic: boolean("show_public")
      .notNull()
      .default(false),
    showPrint: boolean("show_print")
      .notNull()
      .default(false),
    optionsJson: text("options_json"),
    createdByUserId: int("created_by_user_id")
      .notNull()
      .references(() => authUsers.id),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    uniqueIndex("member_custom_fields_tenant_name_unique").on(
      table.tenantId,
      table.normalizedName,
    ),
    uniqueIndex("member_custom_fields_id_tenant_unique").on(
      table.id,
      table.tenantId,
    ),
    index("member_custom_fields_tenant_status_order_idx").on(
      table.tenantId,
      table.status,
      table.displayOrder,
    ),
  ],
);

export const memberCustomValues = mysqlTable(
  "member_custom_values",
  {
    personId: int("person_id").notNull(),
    tenantId: int("tenant_id").notNull(),
    fieldId: int("field_id").notNull(),
    valueText: varchar("value_text", { length: 191 }).notNull(),
    updatedByUserId: int("updated_by_user_id")
      .notNull()
      .references(() => authUsers.id),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.personId, table.fieldId] }),
    foreignKey({
      columns: [table.personId, table.tenantId],
      foreignColumns: [people.id, people.tenantId],
      name: "member_custom_values_person_tenant_fk",
    }),
    foreignKey({
      columns: [table.fieldId, table.tenantId],
      foreignColumns: [memberCustomFields.id, memberCustomFields.tenantId],
      name: "member_custom_values_field_tenant_fk",
    }),
  ],
);

export const memberPreRegistrationForms = mysqlTable(
  "member_pre_registration_forms",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id")
      .notNull()
      .references(() => tenants.id),
    name: varchar("name", { length: 255 }).notNull(),
    tokenHash: varchar("token_hash", { length: 191 }).notNull().unique(),
    tokenPrefix: varchar("token_prefix", { length: 191 }).notNull(),
    unitId: int("unit_id"),
    status: varchar("status", { length: 80 }).notNull().default("ATIVO"),
    expiresAt: varchar("expires_at", { length: 40 }),
    createdByUserId: int("created_by_user_id")
      .notNull()
      .references(() => authUsers.id),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    uniqueIndex("member_pre_registration_forms_id_tenant_unique").on(
      table.id,
      table.tenantId,
    ),
    index("member_pre_registration_forms_tenant_status_idx").on(
      table.tenantId,
      table.status,
      table.createdAt,
    ),
    foreignKey({
      columns: [table.unitId, table.tenantId],
      foreignColumns: [organizationalUnits.id, organizationalUnits.tenantId],
      name: "pre_registration_forms_unit_tenant_fk",
    }),
  ],
);

export const memberPreRegistrations = mysqlTable(
  "member_pre_registrations",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id")
      .notNull()
      .references(() => tenants.id),
    formId: int("form_id").notNull(),
    fullName: varchar("full_name", { length: 255 }).notNull(),
    birthDate: varchar("birth_date", { length: 40 }),
    cpf: varchar("cpf", { length: 32 }),
    phone: varchar("phone", { length: 40 }),
    whatsapp: varchar("whatsapp", { length: 40 }),
    email: varchar("email", { length: 254 }),
    voterTitle: varchar("voter_title", { length: 32 }),
    matrixId: int("matrix_id"),
    branchId: int("branch_id"),
    status: varchar("status", { length: 80 }).notNull().default("PENDENTE"),
    payloadJson: text("payload_json").notNull(),
    consentAt: varchar("consent_at", { length: 40 }).notNull(),
    consentVersion: varchar("consent_version", { length: 191 }).notNull(),
    sourceHash: varchar("source_hash", { length: 191 }).notNull(),
    reviewReason: varchar("review_reason", { length: 191 }),
    reviewedByUserId: int("reviewed_by_user_id").references(
      () => authUsers.id,
    ),
    reviewedAt: varchar("reviewed_at", { length: 40 }),
    approvedMemberId: int("approved_member_id"),
    correctionTokenHash: varchar("correction_token_hash", { length: 191 }),
    correctionExpiresAt: varchar("correction_expires_at", { length: 40 }),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    uniqueIndex("member_pre_registrations_id_tenant_unique").on(
      table.id,
      table.tenantId,
    ),
    index("member_pre_registrations_tenant_status_created_idx").on(
      table.tenantId,
      table.status,
      table.createdAt,
    ),
    index("member_pre_registrations_tenant_cpf_idx").on(
      table.tenantId,
      table.cpf,
    ),
    foreignKey({
      columns: [table.formId, table.tenantId],
      foreignColumns: [
        memberPreRegistrationForms.id,
        memberPreRegistrationForms.tenantId,
      ],
      name: "pre_registrations_form_tenant_fk",
    }),
    foreignKey({
      columns: [table.matrixId, table.tenantId],
      foreignColumns: [organizationalUnits.id, organizationalUnits.tenantId],
      name: "pre_registrations_matrix_tenant_fk",
    }),
    foreignKey({
      columns: [table.branchId, table.matrixId, table.tenantId],
      foreignColumns: [
        organizationalUnits.id,
        organizationalUnits.parentId,
        organizationalUnits.tenantId,
      ],
      name: "pre_registrations_branch_matrix_tenant_fk",
    }),
    foreignKey({
      columns: [table.approvedMemberId, table.tenantId],
      foreignColumns: [people.id, people.tenantId],
      name: "pre_registrations_member_tenant_fk",
    }),
  ],
);

export const memberPreRegistrationPhotos = mysqlTable(
  "member_pre_registration_photos",
  {
    preRegistrationId: int("pre_registration_id").primaryKey(),
    tenantId: int("tenant_id").notNull(),
    imageData: longBlob("image_data").notNull(),
    mimeType: varchar("mime_type", { length: 80 }).notNull(),
    byteSize: int("byte_size").notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.preRegistrationId, table.tenantId],
      foreignColumns: [
        memberPreRegistrations.id,
        memberPreRegistrations.tenantId,
      ],
      name: "pre_registration_photos_request_tenant_fk",
    }),
  ],
);

export const memberPreRegistrationCustomValues = mysqlTable(
  "member_pre_registration_custom_values",
  {
    preRegistrationId: int("pre_registration_id").notNull(),
    tenantId: int("tenant_id").notNull(),
    fieldId: int("field_id").notNull(),
    valueText: varchar("value_text", { length: 191 }).notNull(),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.preRegistrationId, table.fieldId] }),
    foreignKey({
      columns: [table.preRegistrationId, table.tenantId],
      foreignColumns: [
        memberPreRegistrations.id,
        memberPreRegistrations.tenantId,
      ],
      name: "pre_registration_values_request_tenant_fk",
    }),
    foreignKey({
      columns: [table.fieldId, table.tenantId],
      foreignColumns: [memberCustomFields.id, memberCustomFields.tenantId],
      name: "pre_registration_values_field_tenant_fk",
    }),
  ],
);

export const memberPreRegistrationRateLimits = mysqlTable(
  "member_pre_registration_rate_limits",
  {
    rateKey: varchar("rate_key", { length: 191 }).primaryKey(),
    attempts: int("attempts").notNull().default(0),
    windowStartedAt: varchar("window_started_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
);

export const helpArticles = mysqlTable(
  "help_articles",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id").references(() => tenants.id),
    slug: varchar("slug", { length: 191 }).notNull(),
    title: varchar("title", { length: 255 }).notNull(),
    summary: text("summary").notNull(),
    content: text("content").notNull(),
    category: varchar("category", { length: 191 }).notNull(),
    displayOrder: int("display_order").notNull().default(0),
    targetProfiles: text("target_profiles").notNull().default('["TODOS"]'),
    requiredPermission: varchar("required_permission", { length: 191 }),
    relatedRoute: varchar("related_route", { length: 191 }),
    published: boolean("published")
      .notNull()
      .default(true),
    isNewFeature: boolean("is_new_feature")
      .notNull()
      .default(false),
    releasedAt: varchar("released_at", { length: 40 }),
    version: varchar("version", { length: 191 }).notNull().default("1.0"),
    createdByUserId: int("created_by_user_id").references(
      () => authUsers.id,
    ),
    publishedAt: varchar("published_at", { length: 40 }),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    index("help_articles_visibility_idx").on(
      table.published,
      table.category,
      table.displayOrder,
      table.releasedAt,
    ),
  ],
);

export const helpArticleReads = mysqlTable(
  "help_article_reads",
  {
    userId: int("user_id")
      .notNull()
      .references(() => authUsers.id),
    articleId: int("article_id")
      .notNull()
      .references(() => helpArticles.id),
    viewedAt: varchar("viewed_at", { length: 40 }).notNull(),
  },
  (table) => [primaryKey({ columns: [table.userId, table.articleId] })],
);

export const dataExportAudit = mysqlTable(
  "data_export_audit",
  {
    id: int("id").autoincrement().primaryKey(),
    actorUserId: int("actor_user_id")
      .notNull()
      .references(() => authUsers.id),
    actorMembershipId: int("actor_membership_id").references(
      () => tenantMemberships.id,
    ),
    tenantId: int("tenant_id")
      .notNull()
      .references(() => tenants.id),
    exportType: varchar("export_type", { length: 80 }).notNull(),
    modules: text("modules").notNull(),
    format: varchar("format", { length: 191 }).notNull(),
    recordCount: int("record_count").notNull().default(0),
    scopeUnitId: int("scope_unit_id").references(
      () => organizationalUnits.id,
    ),
    status: varchar("status", { length: 80 }).notNull(),
    details: text("details"),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
  },
  (table) => [
    index("data_export_audit_tenant_created_idx").on(
      table.tenantId,
      table.createdAt,
    ),
  ],
);

export const notifications = mysqlTable(
  "notifications",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id").references(() => tenants.id),
    audience: varchar("audience", { length: 191 }).notNull().default("ORGANIZATIONAL"),
    type: varchar("type", { length: 80 }).notNull(),
    title: varchar("title", { length: 255 }).notNull(),
    message: text("message").notNull(),
    priority: varchar("priority", { length: 191 }).notNull().default("INFO"),
    internalRoute: varchar("internal_route", { length: 191 }),
    sourceEntity: varchar("source_entity", { length: 191 }),
    sourceEntityId: int("source_entity_id"),
    unitId: int("unit_id").references(() => organizationalUnits.id),
    groupKey: varchar("group_key", { length: 191 }),
    metadataJson: text("metadata_json"),
    mandatory: boolean("mandatory")
      .notNull()
      .default(false),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    index("notifications_tenant_type_created_idx").on(
      table.tenantId,
      table.type,
      table.createdAt,
    ),
    index("notifications_group_key_idx").on(table.groupKey, table.createdAt),
  ],
);

export const notificationRecipients = mysqlTable(
  "notification_recipients",
  {
    notificationId: int("notification_id")
      .notNull()
      .references(() => notifications.id),
    userId: int("user_id")
      .notNull()
      .references(() => authUsers.id),
    readAt: varchar("read_at", { length: 40 }),
    archivedAt: varchar("archived_at", { length: 40 }),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.notificationId, table.userId] }),
    index("notification_recipients_user_unread_idx").on(
      table.userId,
      table.readAt,
      table.notificationId,
    ),
    index("notification_recipients_user_created_idx").on(
      table.userId,
      table.createdAt,
    ),
  ],
);

export const departments = mysqlTable(
  "departments",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id")
      .notNull()
      .references(() => tenants.id),
    name: varchar("name", { length: 255 }).notNull(),
    acronym: varchar("acronym", { length: 191 }),
    description: text("description"),
    type: varchar("type", { length: 80 }).notNull(),
    unitId: int("unit_id")
      .notNull()
      .references(() => organizationalUnits.id),
    conventionId: int("convention_id")
      .notNull()
      .references(() => organizationalUnits.id),
    matrixId: int("matrix_id").references(() => organizationalUnits.id),
    branchId: int("branch_id").references(() => organizationalUnits.id),
    status: varchar("status", { length: 80 }).notNull().default("ATIVO"),
    enabledFeatures: text("enabled_features").notNull(),
    absenceAlertThreshold: int("absence_alert_threshold")
      .notNull()
      .default(3),
    version: int("version").notNull().default(1),
    createdByUserId: int("created_by_user_id")
      .notNull()
      .references(() => authUsers.id),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    uniqueIndex("departments_id_tenant_unique").on(table.id, table.tenantId),
    uniqueIndex("departments_tenant_unit_name_unique").on(
      table.tenantId,
      table.unitId,
      table.name,
    ),
    index("departments_tenant_scope_status_idx").on(
      table.tenantId,
      table.conventionId,
      table.matrixId,
      table.branchId,
      table.status,
    ),
  ],
);
export const departmentRoles = mysqlTable(
  "department_roles",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id").notNull(),
    departmentId: int("department_id")
      .notNull()
      .references(() => departments.id),
    name: varchar("name", { length: 255 }).notNull(),
    isLeadership: boolean("is_leadership")
      .notNull()
      .default(false),
    displayOrder: int("display_order").notNull().default(0),
    status: varchar("status", { length: 80 }).notNull(),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    uniqueIndex("department_roles_tenant_department_name_unique").on(
      table.tenantId,
      table.departmentId,
      table.name,
    ),
  ],
);
export const departmentParticipants = mysqlTable(
  "department_participants",
  {
    departmentId: int("department_id")
      .notNull()
      .references(() => departments.id),
    tenantId: int("tenant_id").notNull(),
    personId: int("person_id")
      .notNull()
      .references(() => people.id),
    roleId: int("role_id").references(() => departmentRoles.id),
    joinedAt: varchar("joined_at", { length: 40 }).notNull(),
    status: varchar("status", { length: 80 }).notNull(),
    leftAt: varchar("left_at", { length: 40 }),
    exitReason: varchar("exit_reason", { length: 191 }),
    notes: text("notes"),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.departmentId, table.personId] }),
    index("department_participants_tenant_person_idx").on(
      table.tenantId,
      table.personId,
      table.status,
    ),
  ],
);
export const departmentAccess = mysqlTable(
  "department_access",
  {
    departmentId: int("department_id")
      .notNull()
      .references(() => departments.id),
    tenantId: int("tenant_id").notNull(),
    membershipId: int("membership_id")
      .notNull()
      .references(() => tenantMemberships.id),
    roleId: int("role_id").references(() => departmentRoles.id),
    permissionsJson: text("permissions_json").notNull(),
    status: varchar("status", { length: 80 }).notNull(),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.departmentId, table.membershipId] }),
    index("department_access_membership_idx").on(
      table.tenantId,
      table.membershipId,
      table.status,
    ),
  ],
);
export const departmentEvents = mysqlTable(
  "department_events",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id").notNull(),
    departmentId: int("department_id")
      .notNull()
      .references(() => departments.id),
    title: varchar("title", { length: 255 }).notNull(),
    description: text("description"),
    eventDate: varchar("event_date", { length: 40 }).notNull(),
    startTime: varchar("start_time", { length: 40 }),
    location: varchar("location", { length: 191 }),
    responsiblePersonId: int("responsible_person_id").references(
      () => people.id,
    ),
    notes: text("notes"),
    status: varchar("status", { length: 80 }).notNull(),
    createdByUserId: int("created_by_user_id")
      .notNull()
      .references(() => authUsers.id),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    index("department_events_department_date_idx").on(
      table.tenantId,
      table.departmentId,
      table.eventDate,
      table.status,
    ),
  ],
);
export const departmentActivities = mysqlTable("department_activities", {
  id: int("id").primaryKey(),
  tenantId: int("tenant_id").notNull(),
  departmentId: int("department_id")
    .notNull()
    .references(() => departments.id),
  activityDate: varchar("activity_date", { length: 40 }).notNull(),
  title: varchar("title", { length: 255 }).notNull(),
  notes: text("notes"),
  status: varchar("status", { length: 80 }).notNull(),
  version: int("version").notNull(),
  finalizedByUserId: int("finalized_by_user_id").references(
    () => authUsers.id,
  ),
  finalizedAt: varchar("finalized_at", { length: 40 }),
  createdByUserId: int("created_by_user_id")
    .notNull()
    .references(() => authUsers.id),
  createdAt: varchar("created_at", { length: 40 }).notNull(),
  updatedAt: varchar("updated_at", { length: 40 }).notNull(),
});
export const departmentAttendance = mysqlTable(
  "department_attendance",
  {
    activityId: int("activity_id")
      .notNull()
      .references(() => departmentActivities.id),
    tenantId: int("tenant_id").notNull(),
    departmentId: int("department_id")
      .notNull()
      .references(() => departments.id),
    personId: int("person_id")
      .notNull()
      .references(() => people.id),
    attendanceStatus: varchar("attendance_status", { length: 80 }).notNull(),
    notes: text("notes"),
    updatedByUserId: int("updated_by_user_id")
      .notNull()
      .references(() => authUsers.id),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.activityId, table.personId] }),
    index("department_attendance_person_idx").on(
      table.tenantId,
      table.personId,
      table.attendanceStatus,
    ),
  ],
);
export const departmentCommunications = mysqlTable(
  "department_communications",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id").notNull(),
    departmentId: int("department_id")
      .notNull()
      .references(() => departments.id),
    message: text("message").notNull(),
    audience: varchar("audience", { length: 191 }).notNull(),
    channel: varchar("channel", { length: 191 }).notNull(),
    recipientCount: int("recipient_count").notNull(),
    createdByUserId: int("created_by_user_id")
      .notNull()
      .references(() => authUsers.id),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
  },
);
export const ebdClasses = mysqlTable(
  "ebd_classes",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id").notNull(),
    departmentId: int("department_id")
      .notNull()
      .references(() => departments.id),
    name: varchar("name", { length: 255 }).notNull(),
    description: text("description"),
    ageRange: varchar("age_range", { length: 191 }),
    room: varchar("room", { length: 191 }),
    status: varchar("status", { length: 80 }).notNull(),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    uniqueIndex("ebd_classes_id_tenant_unique").on(table.id, table.tenantId),
    uniqueIndex("ebd_classes_tenant_department_name_unique").on(
      table.tenantId,
      table.departmentId,
      table.name,
    ),
  ],
);
export const ebdClassTeachers = mysqlTable(
  "ebd_class_teachers",
  {
    classId: int("class_id")
      .notNull()
      .references(() => ebdClasses.id),
    tenantId: int("tenant_id").notNull(),
    membershipId: int("membership_id")
      .notNull()
      .references(() => tenantMemberships.id),
    personId: int("person_id").references(() => people.id),
    teacherRole: varchar("teacher_role", { length: 191 }).notNull(),
    status: varchar("status", { length: 80 }).notNull(),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.classId, table.membershipId] }),
    index("ebd_class_teachers_membership_idx").on(
      table.tenantId,
      table.membershipId,
      table.status,
    ),
  ],
);
export const ebdEnrollments = mysqlTable(
  "ebd_enrollments",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id").notNull(),
    departmentId: int("department_id")
      .notNull()
      .references(() => departments.id),
    classId: int("class_id")
      .notNull()
      .references(() => ebdClasses.id),
    personId: int("person_id")
      .notNull()
      .references(() => people.id),
    enrolledAt: varchar("enrolled_at", { length: 40 }).notNull(),
    status: varchar("status", { length: 80 }).notNull(),
    leftAt: varchar("left_at", { length: 40 }),
    notes: text("notes"),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    index("ebd_enrollments_class_status_idx").on(
      table.tenantId,
      table.classId,
      table.status,
      table.personId,
    ),
  ],
);
export const ebdStudents = mysqlTable(
  "ebd_students",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id").notNull(),
    departmentId: int("department_id")
      .notNull()
      .references(() => departments.id),
    personId: int("person_id").references(() => people.id),
    fullName: varchar("full_name", { length: 255 }).notNull(),
    birthDate: varchar("birth_date", { length: 40 }),
    sex: varchar("sex", { length: 191 }),
    cpf: varchar("cpf", { length: 32 }),
    phone: varchar("phone", { length: 40 }),
    whatsapp: varchar("whatsapp", { length: 40 }),
    guardianName: varchar("guardian_name", { length: 255 }),
    guardianPhone: varchar("guardian_phone", { length: 40 }),
    notes: text("notes"),
    status: varchar("status", { length: 80 }).notNull(),
    createdByUserId: int("created_by_user_id").notNull(),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    index("ebd_students_department_name_idx").on(
      table.tenantId,
      table.departmentId,
      table.status,
      table.fullName,
    ),
  ],
);
export const ebdStudentEnrollments = mysqlTable(
  "ebd_student_enrollments",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id").notNull(),
    departmentId: int("department_id")
      .notNull()
      .references(() => departments.id),
    classId: int("class_id")
      .notNull()
      .references(() => ebdClasses.id),
    studentId: int("student_id")
      .notNull()
      .references(() => ebdStudents.id),
    enrolledAt: varchar("enrolled_at", { length: 40 }).notNull(),
    status: varchar("status", { length: 80 }).notNull(),
    leftAt: varchar("left_at", { length: 40 }),
    notes: text("notes"),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    index("ebd_student_enrollments_class_idx").on(
      table.tenantId,
      table.classId,
      table.status,
      table.studentId,
    ),
  ],
);
export const secretaryRequests = mysqlTable(
  "secretary_requests",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id").notNull(),
    personId: int("person_id")
      .notNull()
      .references(() => people.id),
    requestType: varchar("request_type", { length: 80 }).notNull(),
    requestDirection: varchar("request_direction", { length: 191 }).notNull().default("SAIDA"),
    originUnitId: int("origin_unit_id"),
    destinationUnitId: int("destination_unit_id"),
    externalChurch: varchar("external_church", { length: 191 }),
    externalCity: varchar("external_city", { length: 191 }),
    externalState: varchar("external_state", { length: 191 }),
    reason: varchar("reason", { length: 191 }),
    notes: text("notes"),
    status: varchar("status", { length: 80 }).notNull(),
    departmentResolution: text("department_resolution"),
    ebdResolution: text("ebd_resolution"),
    version: int("version").notNull(),
    requestedByUserId: int("requested_by_user_id").notNull(),
    reviewedByUserId: int("reviewed_by_user_id"),
    requestedAt: varchar("requested_at", { length: 40 }).notNull(),
    reviewedAt: varchar("reviewed_at", { length: 40 }),
    completedAt: varchar("completed_at", { length: 40 }),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    index("secretary_requests_queue_idx").on(
      table.tenantId,
      table.status,
      table.requestType,
      table.requestedAt,
    ),
    index("secretary_requests_pending_destination_idx").on(
      table.tenantId,
      table.personId,
      table.destinationUnitId,
      table.status,
    ),
  ],
);
export const secretaryTransferSearchLimits = mysqlTable(
  "secretary_transfer_search_limits",
  {
    tenantId: int("tenant_id").notNull().references(() => tenants.id),
    userId: int("user_id").notNull().references(() => authUsers.id),
    attempts: int("attempts").notNull().default(0),
    windowStartedAt: varchar("window_started_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.tenantId, table.userId] }),
    index("secretary_transfer_search_limits_window_idx").on(table.windowStartedAt, table.updatedAt),
  ],
);
export const churchMovements = mysqlTable(
  "church_movements",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id").notNull(),
    personId: int("person_id")
      .notNull()
      .references(() => people.id),
    unitId: int("unit_id").notNull(),
    movementType: varchar("movement_type", { length: 80 }).notNull(),
    requestId: int("request_id"),
    effectiveDate: varchar("effective_date", { length: 40 }).notNull(),
    previousStatus: varchar("previous_status", { length: 80 }),
    newStatus: varchar("new_status", { length: 80 }),
    previousUnitId: int("previous_unit_id"),
    destinationUnitId: int("destination_unit_id"),
    externalChurch: varchar("external_church", { length: 191 }),
    externalCity: varchar("external_city", { length: 191 }),
    externalState: varchar("external_state", { length: 191 }),
    description: text("description").notNull(),
    metadataJson: text("metadata_json").notNull(),
    status: varchar("status", { length: 80 }).notNull(),
    createdByUserId: int("created_by_user_id").notNull(),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
  },
  (table) => [
    index("church_movements_report_idx").on(
      table.tenantId,
      table.unitId,
      table.movementType,
      table.effectiveDate,
      table.status,
    ),
  ],
);
export const baptismEvents = mysqlTable(
  "baptism_events",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id").notNull(),
    unitId: int("unit_id").notNull(),
    title: varchar("title", { length: 255 }).notNull(),
    scheduledDate: varchar("scheduled_date", { length: 40 }).notNull(),
    location: varchar("location", { length: 191 }),
    responsiblePersonId: int("responsible_person_id"),
    notes: text("notes"),
    status: varchar("status", { length: 80 }).notNull(),
    version: int("version").notNull(),
    createdByUserId: int("created_by_user_id").notNull(),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    index("baptism_events_date_idx").on(
      table.tenantId,
      table.unitId,
      table.scheduledDate,
      table.status,
    ),
  ],
);
export const baptismCandidates = mysqlTable(
  "baptism_candidates",
  {
    eventId: int("event_id")
      .notNull()
      .references(() => baptismEvents.id),
    tenantId: int("tenant_id").notNull(),
    personId: int("person_id")
      .notNull()
      .references(() => people.id),
    status: varchar("status", { length: 80 }).notNull(),
    notes: text("notes"),
    completedAt: varchar("completed_at", { length: 40 }),
    updatedByUserId: int("updated_by_user_id").notNull(),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.eventId, table.personId] }),
    index("baptism_candidates_status_idx").on(
      table.tenantId,
      table.status,
      table.personId,
    ),
  ],
);
export const consecrations = mysqlTable(
  "consecrations",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id").notNull(),
    personId: int("person_id")
      .notNull()
      .references(() => people.id),
    unitId: int("unit_id").notNull(),
    previousFunctionId: int("previous_function_id"),
    newFunctionId: int("new_function_id").notNull(),
    eventDate: varchar("event_date", { length: 40 }).notNull(),
    location: varchar("location", { length: 191 }),
    responsiblePersonId: int("responsible_person_id"),
    notes: text("notes"),
    status: varchar("status", { length: 80 }).notNull(),
    version: int("version").notNull(),
    createdByUserId: int("created_by_user_id").notNull(),
    completedByUserId: int("completed_by_user_id"),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    index("consecrations_status_date_idx").on(
      table.tenantId,
      table.unitId,
      table.status,
      table.eventDate,
    ),
  ],
);
export const secretaryDocumentTemplates = mysqlTable(
  "secretary_document_templates",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id").notNull(),
    unitId: int("unit_id"),
    name: varchar("name", { length: 255 }).notNull(),
    documentType: varchar("document_type", { length: 80 }).notNull(),
    status: varchar("status", { length: 80 }).notNull(),
    currentVersion: int("current_version").notNull(),
    createdByUserId: int("created_by_user_id").notNull(),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
);
export const secretaryDocumentTemplateVersions = mysqlTable(
  "secretary_document_template_versions",
  {
    templateId: int("template_id")
      .notNull()
      .references(() => secretaryDocumentTemplates.id),
    tenantId: int("tenant_id").notNull(),
    version: int("version").notNull(),
    title: varchar("title", { length: 255 }).notNull(),
    body: text("body").notNull(),
    headerText: text("header_text"),
    footerText: text("footer_text"),
    signatureLabelsJson: text("signature_labels_json").notNull(),
    styleJson: text("style_json").notNull(),
    createdByUserId: int("created_by_user_id").notNull(),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
  },
  (table) => [primaryKey({ columns: [table.templateId, table.version] })],
);
export const secretaryDocuments = mysqlTable(
  "secretary_documents",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id").notNull(),
    unitId: int("unit_id").notNull(),
    personId: int("person_id")
      .notNull()
      .references(() => people.id),
    templateId: int("template_id")
      .notNull()
      .references(() => secretaryDocumentTemplates.id),
    templateVersion: int("template_version").notNull(),
    documentType: varchar("document_type", { length: 80 }).notNull(),
    documentNumber: varchar("document_number", { length: 191 }).notNull(),
    titleSnapshot: varchar("title_snapshot", { length: 191 }).notNull(),
    bodySnapshot: text("body_snapshot").notNull(),
    headerSnapshot: text("header_snapshot"),
    footerSnapshot: text("footer_snapshot"),
    signaturesSnapshot: text("signatures_snapshot").notNull(),
    issuedByUserId: int("issued_by_user_id").notNull(),
    issuedAt: varchar("issued_at", { length: 40 }).notNull(),
  },
  (table) => [
    index("secretary_documents_report_idx").on(
      table.tenantId,
      table.unitId,
      table.documentType,
      table.issuedAt,
    ),
  ],
);
export const ebdMeetings = mysqlTable(
  "ebd_meetings",
  {
    id: int("id").primaryKey(),
    tenantId: int("tenant_id").notNull(),
    departmentId: int("department_id")
      .notNull()
      .references(() => departments.id),
    meetingDate: varchar("meeting_date", { length: 40 }).notNull(),
    theme: varchar("theme", { length: 191 }),
    startTime: varchar("start_time", { length: 40 }),
    status: varchar("status", { length: 80 }).notNull(),
    version: int("version").notNull(),
    createdByUserId: int("created_by_user_id")
      .notNull()
      .references(() => authUsers.id),
    finalizedByUserId: int("finalized_by_user_id").references(
      () => authUsers.id,
    ),
    finalizedAt: varchar("finalized_at", { length: 40 }),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    uniqueIndex("ebd_meetings_tenant_department_date_unique").on(
      table.tenantId,
      table.departmentId,
      table.meetingDate,
    ),
  ],
);
export const ebdStudentAttendance = mysqlTable(
  "ebd_student_attendance",
  {
    meetingId: int("meeting_id")
      .notNull()
      .references(() => ebdMeetings.id),
    classId: int("class_id")
      .notNull()
      .references(() => ebdClasses.id),
    tenantId: int("tenant_id").notNull(),
    studentId: int("student_id")
      .notNull()
      .references(() => ebdStudents.id),
    attendanceStatus: varchar("attendance_status", { length: 80 }).notNull(),
    updatedByUserId: int("updated_by_user_id").notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.meetingId, table.classId, table.studentId] }),
    index("ebd_student_attendance_history_idx").on(
      table.tenantId,
      table.studentId,
      table.attendanceStatus,
      table.meetingId,
    ),
  ],
);
export const ebdAttendance = mysqlTable(
  "ebd_attendance",
  {
    meetingId: int("meeting_id")
      .notNull()
      .references(() => ebdMeetings.id),
    classId: int("class_id")
      .notNull()
      .references(() => ebdClasses.id),
    tenantId: int("tenant_id").notNull(),
    personId: int("person_id")
      .notNull()
      .references(() => people.id),
    attendanceStatus: varchar("attendance_status", { length: 80 }).notNull(),
    updatedByUserId: int("updated_by_user_id")
      .notNull()
      .references(() => authUsers.id),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.meetingId, table.classId, table.personId] }),
    index("ebd_attendance_person_history_idx").on(
      table.tenantId,
      table.personId,
      table.attendanceStatus,
      table.meetingId,
    ),
  ],
);
export const ebdVisitors = mysqlTable("ebd_visitors", {
  id: int("id").primaryKey(),
  tenantId: int("tenant_id").notNull(),
  departmentId: int("department_id")
    .notNull()
    .references(() => departments.id),
  meetingId: int("meeting_id")
    .notNull()
    .references(() => ebdMeetings.id),
  classId: int("class_id")
    .notNull()
    .references(() => ebdClasses.id),
  personId: int("person_id").references(() => people.id),
  name: varchar("name", { length: 255 }).notNull(),
  phone: varchar("phone", { length: 40 }),
  ageRange: varchar("age_range", { length: 191 }),
  invitedBy: varchar("invited_by", { length: 191 }),
  notes: text("notes"),
  createdByUserId: int("created_by_user_id")
    .notNull()
    .references(() => authUsers.id),
  createdAt: varchar("created_at", { length: 40 }).notNull(),
});
export const ebdClassSummaries = mysqlTable(
  "ebd_class_summaries",
  {
    meetingId: int("meeting_id")
      .notNull()
      .references(() => ebdMeetings.id),
    classId: int("class_id")
      .notNull()
      .references(() => ebdClasses.id),
    tenantId: int("tenant_id").notNull(),
    enrolledCount: int("enrolled_count").notNull(),
    presentCount: int("present_count").notNull(),
    absentCount: int("absent_count").notNull(),
    justifiedCount: int("justified_count").notNull(),
    visitorCount: int("visitor_count").notNull(),
    bibleCount: int("bible_count").notNull(),
    assistanceCount: int("assistance_count").notNull(),
    offeringCents: int("offering_cents").notNull(),
    notes: text("notes"),
    status: varchar("status", { length: 80 }).notNull(),
    version: int("version").notNull(),
    finalizedByUserId: int("finalized_by_user_id").references(
      () => authUsers.id,
    ),
    finalizedAt: varchar("finalized_at", { length: 40 }),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.meetingId, table.classId] }),
    index("ebd_class_summaries_status_idx").on(
      table.tenantId,
      table.meetingId,
      table.status,
    ),
  ],
);
export const ebdClosures = mysqlTable("ebd_closures", {
  meetingId: int("meeting_id")
    .primaryKey()
    .references(() => ebdMeetings.id),
  tenantId: int("tenant_id").notNull(),
  departmentId: int("department_id")
    .notNull()
    .references(() => departments.id),
  enrolledTotal: int("enrolled_total").notNull(),
  presentTotal: int("present_total").notNull(),
  absentTotal: int("absent_total").notNull(),
  justifiedTotal: int("justified_total").notNull(),
  visitorTotal: int("visitor_total").notNull(),
  bibleTotal: int("bible_total").notNull(),
  assistanceTotal: int("assistance_total").notNull(),
  offeringTotalCents: int("offering_total_cents").notNull(),
  exceptionReason: varchar("exception_reason", { length: 191 }),
  finalizedByUserId: int("finalized_by_user_id")
    .notNull()
    .references(() => authUsers.id),
  finalizedAt: varchar("finalized_at", { length: 40 }).notNull(),
  updatedAt: varchar("updated_at", { length: 40 }).notNull(),
});
export const departmentAudit = mysqlTable(
  "department_audit",
  {
    id: int("id").autoincrement().primaryKey(),
    tenantId: int("tenant_id").notNull(),
    departmentId: int("department_id")
      .notNull()
      .references(() => departments.id),
    actorUserId: int("actor_user_id")
      .notNull()
      .references(() => authUsers.id),
    actorMembershipId: int("actor_membership_id").references(
      () => tenantMemberships.id,
    ),
    action: varchar("action", { length: 191 }).notNull(),
    entityType: varchar("entity_type", { length: 80 }).notNull(),
    entityId: int("entity_id").notNull(),
    previousValues: text("previous_values"),
    newValues: text("new_values"),
    reason: varchar("reason", { length: 191 }),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
  },
  (table) => [
    index("department_audit_department_created_idx").on(
      table.tenantId,
      table.departmentId,
      table.createdAt,
    ),
  ],
);

export const financeAllocationConfigs = mysqlTable(
  "finance_allocation_configs",
  {
    id: int("id").primaryKey(), tenantId: int("tenant_id").notNull(), unitId: int("unit_id").notNull(),
    version: int("version").notNull().default(1), status: varchar("status", { length: 80 }).notNull().default("ATIVA"),
    createdByUserId: int("created_by_user_id").notNull(), updatedByUserId: int("updated_by_user_id").notNull(),
    createdAt: varchar("created_at", { length: 40 }).notNull(), updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [uniqueIndex("finance_allocation_configs_unit_unique").on(table.tenantId,table.unitId),index("finance_allocation_configs_scope_idx").on(table.tenantId,table.unitId,table.status)],
);

export const financeAllocationRules = mysqlTable(
  "finance_allocation_rules",
  {
    id: int("id").primaryKey(), tenantId: int("tenant_id").notNull(), configId: int("config_id").notNull(),
    recipientName: varchar("recipient_name", { length: 255 }).notNull(), description: text("description"), recipientType: varchar("recipient_type", { length: 80 }).notNull(),
    ruleType: varchar("rule_type", { length: 80 }).notNull().default("PERCENTUAL"), percentageBasisPoints: int("percentage_basis_points"), fixedAmountCents: int("fixed_amount_cents"), financialDestination: varchar("financial_destination", { length: 191 }).notNull().default("REPASSAR"), destinationUnitId: int("destination_unit_id"), destinationDepartmentId: int("destination_department_id"),
    calculationBase: varchar("calculation_base", { length: 191 }).notNull().default("RECEITAS_PARTICIPANTES"), displayOrder: int("display_order").notNull(), active: int("active").notNull().default(1),
    createdAt: varchar("created_at", { length: 40 }).notNull(), updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [index("finance_allocation_rules_config_idx").on(table.tenantId,table.configId,table.active,table.displayOrder)],
);

export const financePeriods = mysqlTable(
  "finance_periods",
  {
    id: int("id").primaryKey(), tenantId: int("tenant_id").notNull(), unitId: int("unit_id").notNull(), unitType: varchar("unit_type", { length: 80 }).notNull(),
    matrixId: int("matrix_id").notNull(), branchId: int("branch_id"), competency: varchar("competency", { length: 16 }).notNull(), status: varchar("status", { length: 80 }).notNull().default("ABERTO"),
    lifecycleState: varchar("lifecycle_state", { length: 191 }).notNull().default("ABERTO"), allocationConfigId: int("allocation_config_id").notNull(), allocationConfigVersion: int("allocation_config_version").notNull(),
    openedAt: varchar("opened_at", { length: 40 }).notNull(), openedByUserId: int("opened_by_user_id").notNull(), closedAt: varchar("closed_at", { length: 40 }), closedByUserId: int("closed_by_user_id"),
    reopenedAt: varchar("reopened_at", { length: 40 }), reopenedByUserId: int("reopened_by_user_id"), reopenReason: varchar("reopen_reason", { length: 191 }), reopenCount: int("reopen_count").notNull().default(0),
    closureVersion: int("closure_version").notNull().default(0), notes: text("notes"), version: int("version").notNull().default(1), createdAt: varchar("created_at", { length: 40 }).notNull(), updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [uniqueIndex("finance_periods_unit_competency_unique").on(table.tenantId,table.unitId,table.competency),index("finance_periods_scope_competency_idx").on(table.tenantId,table.matrixId,table.branchId,table.competency,table.status)],
);

export const financePeriodReopenRequests = mysqlTable(
  "finance_period_reopen_requests",
  {
    id: int("id").primaryKey(), tenantId: int("tenant_id").notNull(), periodId: int("period_id").notNull(), unitId: int("unit_id").notNull(), matrixId: int("matrix_id").notNull(), branchId: int("branch_id"),
    requesterUserId: int("requester_user_id").notNull(), requesterMembershipId: int("requester_membership_id").notNull(), requestedClosureVersion: int("requested_closure_version").notNull(), reason: varchar("reason", { length: 191 }).notNull(), status: varchar("status", { length: 80 }).notNull().default("PENDENTE"),
    requestedAt: varchar("requested_at", { length: 40 }).notNull(), expiresAt: varchar("expires_at", { length: 40 }), decidedByUserId: int("decided_by_user_id"), decidedByMembershipId: int("decided_by_membership_id"), decisionReason: varchar("decision_reason", { length: 191 }), decidedAt: varchar("decided_at", { length: 40 }), usedAt: varchar("used_at", { length: 40 }), reopenedByUserId: int("reopened_by_user_id"), createdAt: varchar("created_at", { length: 40 }).notNull(), updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    index("finance_reopen_requests_matrix_status_idx").on(table.tenantId, table.matrixId, table.status, table.requestedAt),
    index("finance_reopen_requests_requester_idx").on(table.tenantId, table.requesterUserId, table.periodId, table.requestedClosureVersion),
  ],
);

export const financePeriodAllocationRules = mysqlTable("finance_period_allocation_rules", {
  id: int("id").primaryKey(), tenantId: int("tenant_id").notNull(), periodId: int("period_id").notNull(), sourceRuleId: int("source_rule_id").notNull(),
  recipientName: varchar("recipient_name", { length: 255 }).notNull(), description: text("description"), recipientType: varchar("recipient_type", { length: 80 }).notNull(), ruleType: varchar("rule_type", { length: 80 }).notNull(),
  percentageBasisPoints: int("percentage_basis_points"), fixedAmountCents: int("fixed_amount_cents"), financialDestination: varchar("financial_destination", { length: 191 }).notNull().default("REPASSAR"), destinationUnitId: int("destination_unit_id"), destinationDepartmentId: int("destination_department_id"), calculationBase: varchar("calculation_base", { length: 191 }).notNull(),
  participatingCategoryIdsJson: text("participating_category_ids_json").notNull().default("[]"), displayOrder: int("display_order").notNull(), snapshotVersion: int("snapshot_version").notNull(), createdAt: varchar("created_at", { length: 40 }).notNull(),
});

export const financeInterunitRepasses = mysqlTable("finance_interunit_repasses", {
  id: int("id").primaryKey(), tenantId: int("tenant_id").notNull(), periodId: int("period_id").notNull(), closureVersion: int("closure_version").notNull(), ruleDisplayOrder: int("rule_display_order").notNull(), sourceRuleId: int("source_rule_id"), sourceUnitId: int("source_unit_id").notNull(), destinationUnitId: int("destination_unit_id").notNull(), destinationDepartmentId: int("destination_department_id"), kind: varchar("kind", { length: 80 }).notNull().default("NORMAL"), payerUnitId: int("payer_unit_id").notNull(), receiverUnitId: int("receiver_unit_id").notNull(), recipientName: varchar("recipient_name", { length: 255 }).notNull(), competency: varchar("competency", { length: 16 }).notNull(), expectedCents: int("expected_cents").notNull(), sentCents: int("sent_cents").notNull().default(0), receivedCents: int("received_cents").notNull().default(0), writtenOffCents: int("written_off_cents").notNull().default(0), status: varchar("status", { length: 80 }).notNull().default("PENDENTE"), supersededById: int("superseded_by_id"), createdByUserId: int("created_by_user_id").notNull(), createdAt: varchar("created_at", { length: 40 }).notNull(), updatedAt: varchar("updated_at", { length: 40 }).notNull(),
}, (table) => [uniqueIndex("finance_interunit_repasses_version_unique").on(table.tenantId,table.periodId,table.closureVersion,table.ruleDisplayOrder,table.kind,table.payerUnitId,table.receiverUnitId),index("finance_interunit_repasses_scope_idx").on(table.tenantId,table.payerUnitId,table.receiverUnitId,table.status,table.createdAt)]);

export const financeInterunitRepassEvents = mysqlTable("finance_interunit_repass_events", {
  id: int("id").primaryKey(), tenantId: int("tenant_id").notNull(), repassId: int("repass_id").notNull(), eventType: varchar("event_type", { length: 80 }).notNull(), amountCents: int("amount_cents").notNull(), accountId: int("account_id"), movementId: int("movement_id"), occurredOn: varchar("occurred_on", { length: 40 }).notNull(), reason: varchar("reason", { length: 191 }), actorUserId: int("actor_user_id").notNull(), createdAt: varchar("created_at", { length: 40 }).notNull(),
}, (table) => [index("finance_interunit_repass_events_idx").on(table.tenantId,table.repassId,table.createdAt),uniqueIndex("finance_interunit_repass_events_movement_unique").on(table.tenantId,table.movementId)]);

export const financeQuickSessions = mysqlTable(
  "finance_quick_sessions",
  {
    id: int("id").primaryKey(), tenantId: int("tenant_id").notNull(), periodId: int("period_id").notNull(), unitId: int("unit_id").notNull(), userId: int("user_id").notNull(),
    accountId: int("account_id").notNull(), defaultDate: varchar("default_date", { length: 40 }).notNull(), defaultCompetency: varchar("default_competency", { length: 191 }).notNull(), defaultContributionType: varchar("default_contribution_type", { length: 80 }).notNull(),
    defaultPaymentMethodId: int("default_payment_method_id"), status: varchar("status", { length: 80 }).notNull().default("EM_ANDAMENTO"), entryCount: int("entry_count").notNull().default(0), totalCents: int("total_cents").notNull().default(0),
    startedAt: varchar("started_at", { length: 40 }).notNull(), finishedAt: varchar("finished_at", { length: 40 }), updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [index("finance_quick_sessions_resume_idx").on(table.tenantId,table.userId,table.periodId,table.status,table.updatedAt)],
);

export const financeContributionCategoryDefaults = mysqlTable(
  "finance_contribution_category_defaults",
  {
    tenantId: int("tenant_id").notNull(),
    contributionType: varchar("contribution_type", { length: 80 }).notNull(),
    categoryId: int("category_id").notNull(),
    createdByUserId: int("created_by_user_id").notNull(),
    updatedByUserId: int("updated_by_user_id").notNull(),
    createdAt: varchar("created_at", { length: 40 }).notNull(),
    updatedAt: varchar("updated_at", { length: 40 }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.tenantId, table.contributionType] }),
    index("finance_contribution_category_defaults_category_idx").on(
      table.tenantId,
      table.categoryId,
    ),
  ],
);
